/* tslint:disable */
/* eslint-disable */
/**
 * Revaly
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 
 *
 * The version of the OpenAPI document: 2.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

import { mapValues } from '../runtime';
import type { PaymentMethodWriteResponseTransaction } from './PaymentMethodWriteResponseTransaction';
import {
    PaymentMethodWriteResponseTransactionFromJSON,
    PaymentMethodWriteResponseTransactionFromJSONTyped,
    PaymentMethodWriteResponseTransactionToJSON,
    PaymentMethodWriteResponseTransactionToJSONTyped,
} from './PaymentMethodWriteResponseTransaction';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * Response after creating or modifying a payment method
 * @export
 * @interface PaymentMethodWriteResponse
 */
export interface PaymentMethodWriteResponse {
    /**
     * 
     * @type {PaymentMethodWriteResponseTransaction}
     * @memberof PaymentMethodWriteResponse
     */
    transaction?: PaymentMethodWriteResponseTransaction | null;
    /**
     * Unique identifier for the payment method
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    paymentMethodId?: string | null;
    /**
     * Masked credit card number
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    creditCardNumber?: string | null;
    /**
     * Expiration month
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    expiryMonth?: string | null;
    /**
     * Expiration year
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    expiryYear?: string | null;
    /**
     * Masked CVV
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    cvv?: string | null;
    /**
     * Customer's first name
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    firstName?: string | null;
    /**
     * Customer's last name
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    lastName?: string | null;
    /**
     * Customer's full name
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    fullName?: string | null;
    /**
     * Customer identifier
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    customerId?: string | null;
    /**
     * 
     * @type {Address}
     * @memberof PaymentMethodWriteResponse
     */
    billingAddress?: Address | null;
    /**
     * 
     * @type {Address}
     * @memberof PaymentMethodWriteResponse
     */
    shippingAddress?: Address | null;
    /**
     * Customer's email address
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    email?: string | null;
    /**
     * Customer's phone number
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    phoneNumber?: string | null;
    /**
     * Type of payment method
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    paymentMethodType?: string | null;
    /**
     * Unique fingerprint for the payment method
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    fingerprint?: string | null;
    /**
     * Last four digits of the payment method
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    lastFourDigits?: string | null;
    /**
     * First six digits (BIN) of the payment method
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    firstSixDigits?: string | null;
    /**
     * Type of credit card
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    cardType?: string | null;
    /**
     * Date when the payment method was created
     * @type {Date}
     * @memberof PaymentMethodWriteResponse
     */
    dateCreated?: Date | null;
    /**
     * Storage state of the payment method
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    storageState?: string | null;
    /**
     * Bank Identification Number. Must contain exactly 6 or 8 digits.
     * @type {string}
     * @memberof PaymentMethodWriteResponse
     */
    bin?: string | null;
}

/**
 * Check if a given object implements the PaymentMethodWriteResponse interface.
 */
export function instanceOfPaymentMethodWriteResponse(value: object): value is PaymentMethodWriteResponse {
    // RAP fork (pipeline/typescript/config.yaml): every property is optional, so a purely
    // structural check would accept ANY object and break oneOf discrimination — match only
    // when at least one declared property is present (names inspected, never values).
    return ('transaction' in value && value['transaction'] !== undefined)
        || ('paymentMethodId' in value && value['paymentMethodId'] !== undefined)
        || ('creditCardNumber' in value && value['creditCardNumber'] !== undefined)
        || ('expiryMonth' in value && value['expiryMonth'] !== undefined)
        || ('expiryYear' in value && value['expiryYear'] !== undefined)
        || ('cvv' in value && value['cvv'] !== undefined)
        || ('firstName' in value && value['firstName'] !== undefined)
        || ('lastName' in value && value['lastName'] !== undefined)
        || ('fullName' in value && value['fullName'] !== undefined)
        || ('customerId' in value && value['customerId'] !== undefined)
        || ('billingAddress' in value && value['billingAddress'] !== undefined)
        || ('shippingAddress' in value && value['shippingAddress'] !== undefined)
        || ('email' in value && value['email'] !== undefined)
        || ('phoneNumber' in value && value['phoneNumber'] !== undefined)
        || ('paymentMethodType' in value && value['paymentMethodType'] !== undefined)
        || ('fingerprint' in value && value['fingerprint'] !== undefined)
        || ('lastFourDigits' in value && value['lastFourDigits'] !== undefined)
        || ('firstSixDigits' in value && value['firstSixDigits'] !== undefined)
        || ('cardType' in value && value['cardType'] !== undefined)
        || ('dateCreated' in value && value['dateCreated'] !== undefined)
        || ('storageState' in value && value['storageState'] !== undefined)
        || ('bin' in value && value['bin'] !== undefined);
}

export function PaymentMethodWriteResponseFromJSON(json: any): PaymentMethodWriteResponse {
    return PaymentMethodWriteResponseFromJSONTyped(json, false);
}

export function PaymentMethodWriteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodWriteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': json['transaction'] == null ? undefined : PaymentMethodWriteResponseTransactionFromJSON(json['transaction']),
        'paymentMethodId': json['paymentMethodId'] == null ? undefined : json['paymentMethodId'],
        'creditCardNumber': json['creditCardNumber'] == null ? undefined : json['creditCardNumber'],
        'expiryMonth': json['expiryMonth'] == null ? undefined : json['expiryMonth'],
        'expiryYear': json['expiryYear'] == null ? undefined : json['expiryYear'],
        'cvv': json['cvv'] == null ? undefined : json['cvv'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'billingAddress': json['billingAddress'] == null ? undefined : AddressFromJSON(json['billingAddress']),
        'shippingAddress': json['shippingAddress'] == null ? undefined : AddressFromJSON(json['shippingAddress']),
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'paymentMethodType': json['paymentMethodType'] == null ? undefined : json['paymentMethodType'],
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'lastFourDigits': json['lastFourDigits'] == null ? undefined : json['lastFourDigits'],
        'firstSixDigits': json['firstSixDigits'] == null ? undefined : json['firstSixDigits'],
        'cardType': json['cardType'] == null ? undefined : json['cardType'],
        'dateCreated': json['dateCreated'] == null ? undefined : (new Date(json['dateCreated'])),
        'storageState': json['storageState'] == null ? undefined : json['storageState'],
        'bin': json['bin'] == null ? undefined : json['bin'],
    };
}

export function PaymentMethodWriteResponseToJSON(json: any): PaymentMethodWriteResponse {
    return PaymentMethodWriteResponseToJSONTyped(json, false);
}

export function PaymentMethodWriteResponseToJSONTyped(value?: PaymentMethodWriteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction': PaymentMethodWriteResponseTransactionToJSON(value['transaction']),
        'paymentMethodId': value['paymentMethodId'],
        'creditCardNumber': value['creditCardNumber'],
        'expiryMonth': value['expiryMonth'],
        'expiryYear': value['expiryYear'],
        'cvv': value['cvv'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'fullName': value['fullName'],
        'customerId': value['customerId'],
        'billingAddress': AddressToJSON(value['billingAddress']),
        'shippingAddress': AddressToJSON(value['shippingAddress']),
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'paymentMethodType': value['paymentMethodType'],
        'fingerprint': value['fingerprint'],
        'lastFourDigits': value['lastFourDigits'],
        'firstSixDigits': value['firstSixDigits'],
        'cardType': value['cardType'],
        'dateCreated': value['dateCreated'] == null ? value['dateCreated'] : value['dateCreated'].toISOString(),
        'storageState': value['storageState'],
        'bin': value['bin'],
    };
}

