/* tslint:disable */
/* eslint-disable */
/**
 * Revaly
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

import { mapValues } from '../runtime';
import type { PaymentPlanData } from './PaymentPlanData';
import {
    PaymentPlanDataFromJSON,
    PaymentPlanDataFromJSONTyped,
    PaymentPlanDataToJSON,
    PaymentPlanDataToJSONTyped,
} from './PaymentPlanData';
import type { TransactionResponseDetails } from './TransactionResponseDetails';
import {
    TransactionResponseDetailsFromJSON,
    TransactionResponseDetailsFromJSONTyped,
    TransactionResponseDetailsToJSON,
    TransactionResponseDetailsToJSONTyped,
} from './TransactionResponseDetails';
import type { StoredCredentialResponse } from './StoredCredentialResponse';
import {
    StoredCredentialResponseFromJSON,
    StoredCredentialResponseFromJSONTyped,
    StoredCredentialResponseToJSON,
    StoredCredentialResponseToJSONTyped,
} from './StoredCredentialResponse';
import type { Recovery } from './Recovery';
import {
    RecoveryFromJSON,
    RecoveryFromJSONTyped,
    RecoveryToJSON,
    RecoveryToJSONTyped,
} from './Recovery';
import type { PaymentMethodResponse } from './PaymentMethodResponse';
import {
    PaymentMethodResponseFromJSON,
    PaymentMethodResponseFromJSONTyped,
    PaymentMethodResponseToJSON,
    PaymentMethodResponseToJSONTyped,
} from './PaymentMethodResponse';

/**
 * Complete transaction information including processing details
 * @export
 * @interface TransactionResponse
 */
export interface TransactionResponse {
    /**
     * Unique identifier for the transaction
     * @type {string}
     * @memberof TransactionResponse
     */
    transactionId?: string | null;
    /**
     * Date and time when the transaction was processed (ISO 8601)
     * @type {Date}
     * @memberof TransactionResponse
     */
    transactionDate?: Date | null;
    /**
     * Current status of the transaction (1 = Approved, 2 = Declined, 3 = Error)
     * @type {number}
     * @memberof TransactionResponse
     */
    transactionStatus?: number | null;
    /**
     * Human-readable message about the transaction result
     * @type {string}
     * @memberof TransactionResponse
     */
    message?: string | null;
    /**
     * Gateway-specific response code
     * @type {string}
     * @memberof TransactionResponse
     */
    responseCode?: string | null;
    /**
     * Type of transaction performed. Passthrough of the processing platform's transaction type — not a closed set. Payment operations return "Charge", "Authorize", "Capture", "Void" or "Refund" (refund cancellation returns "Refund"). Transaction lookups can additionally return types created by other platform flows, e.g. "Verify", "SuccessfulPayment", "RefundedPayment", "CreateCreditCard", "UpdatePaymentMethod", "RedactPaymentMethod", "RecachePaymentMethod", "CreateGatewayPaymentMethod". Treat unrecognized values as informational.
     * @type {string}
     * @memberof TransactionResponse
     */
    transactionType?: string | null;
    /**
     * Merchant-provided transaction identifier
     * @type {string}
     * @memberof TransactionResponse
     */
    merchantTransactionId?: string | null;
    /**
     * Customer identifier associated with the transaction
     * @type {string}
     * @memberof TransactionResponse
     */
    customerId?: string | null;
    /**
     * Gateway-specific token for the transaction
     * @type {string}
     * @memberof TransactionResponse
     */
    gatewayRoutingId?: string | null;
    /**
     * Transaction currency code (ISO 4217)
     * @type {string}
     * @memberof TransactionResponse
     */
    currency?: string | null;
    /**
     * Transaction amount in smallest currency unit (e.g., cents for USD)
     * @type {number}
     * @memberof TransactionResponse
     */
    amount?: number | null;
    /**
     * Payment gateway used for processing
     * @type {string}
     * @memberof TransactionResponse
     */
    gatewayType?: string | null;
    /**
     * Gateway-specific transaction identifier
     * @type {string}
     * @memberof TransactionResponse
     */
    gatewayTransactionId?: string | null;
    /**
     * Authorization code returned by the acquiring bank or network
     * @type {string}
     * @memberof TransactionResponse
     */
    acquirerAuthCode?: string | null;
    /**
     * Transaction identifier of the inline retry attempt when one was executed
     * @type {string}
     * @memberof TransactionResponse
     */
    inlineRetryPreviousTransactionId?: string | null;
    /**
     * Original merchant transaction identifier before an inline retry was executed
     * @type {string}
     * @memberof TransactionResponse
     */
    inlineRetryPreviousMerchantTransactionId?: string | null;
    /**
     * Indicates that an inline retry attempt occurred
     * @type {boolean}
     * @memberof TransactionResponse
     */
    isInlineRetry?: boolean | null;
    /**
     * Date for retry attempt (if applicable)
     * @type {Date}
     * @memberof TransactionResponse
     */
    retryDate?: Date | null;
    /**
     * Merchant-initiated transaction stored credential ID
     * @type {string}
     * @memberof TransactionResponse
     */
    mitStoredTransactionId?: string | null;
    /**
     * 
     * @type {StoredCredentialResponse}
     * @memberof TransactionResponse
     */
    storedCredential?: StoredCredentialResponse | null;
    /**
     * Order identifier from the merchant system
     * @type {string}
     * @memberof TransactionResponse
     */
    orderId?: string | null;
    /**
     * Merchant-supplied text intended for the customer's card or bank statement, echoed back bounded to 255 characters. Adapted per gateway (length/charset) at submission and never blocks the charge.
     * @type {string}
     * @memberof TransactionResponse
     */
    statementDescriptor?: string | null;
    /**
     * Customer's IP address at time of transaction
     * @type {string}
     * @memberof TransactionResponse
     */
    customerIp?: string | null;
    /**
     * Recovery state indicator (0 = not engaged, 1+ = recovery level)
     * @type {number}
     * @memberof TransactionResponse
     */
    engagedRecoveryState?: number | null;
    /**
     * Transaction description or notes
     * @type {string}
     * @memberof TransactionResponse
     */
    description?: string | null;
    /**
     * Additional gateway-specific fields
     * @type {{ [key: string]: any; }}
     * @memberof TransactionResponse
     */
    gatewayFields?: { [key: string]: any; } | null;
    /**
     * Additional gateway-specific response details returned directly from the processor
     * @type {{ [key: string]: any; }}
     * @memberof TransactionResponse
     */
    gatewaySpecificResponseFields?: { [key: string]: any; } | null;
    /**
     * 
     * @type {PaymentPlanData}
     * @memberof TransactionResponse
     */
    paymentPlanData?: PaymentPlanData | null;
    /**
     * 
     * @type {Recovery}
     * @memberof TransactionResponse
     */
    recovery?: Recovery | null;
    /**
     * 
     * @type {TransactionResponseDetails}
     * @memberof TransactionResponse
     */
    response?: TransactionResponseDetails | null;
    /**
     * 
     * @type {PaymentMethodResponse}
     * @memberof TransactionResponse
     */
    paymentMethod?: PaymentMethodResponse | null;
}

/**
 * Check if a given object implements the TransactionResponse interface.
 */
export function instanceOfTransactionResponse(value: object): value is TransactionResponse {
    // RAP fork (pipeline/typescript/config.yaml): every property is optional, so a purely
    // structural check would accept ANY object and break oneOf discrimination — match only
    // when at least one declared property is present (names inspected, never values).
    return ('transactionId' in value && value['transactionId'] !== undefined)
        || ('transactionDate' in value && value['transactionDate'] !== undefined)
        || ('transactionStatus' in value && value['transactionStatus'] !== undefined)
        || ('message' in value && value['message'] !== undefined)
        || ('responseCode' in value && value['responseCode'] !== undefined)
        || ('transactionType' in value && value['transactionType'] !== undefined)
        || ('merchantTransactionId' in value && value['merchantTransactionId'] !== undefined)
        || ('customerId' in value && value['customerId'] !== undefined)
        || ('gatewayRoutingId' in value && value['gatewayRoutingId'] !== undefined)
        || ('currency' in value && value['currency'] !== undefined)
        || ('amount' in value && value['amount'] !== undefined)
        || ('gatewayType' in value && value['gatewayType'] !== undefined)
        || ('gatewayTransactionId' in value && value['gatewayTransactionId'] !== undefined)
        || ('acquirerAuthCode' in value && value['acquirerAuthCode'] !== undefined)
        || ('inlineRetryPreviousTransactionId' in value && value['inlineRetryPreviousTransactionId'] !== undefined)
        || ('inlineRetryPreviousMerchantTransactionId' in value && value['inlineRetryPreviousMerchantTransactionId'] !== undefined)
        || ('isInlineRetry' in value && value['isInlineRetry'] !== undefined)
        || ('retryDate' in value && value['retryDate'] !== undefined)
        || ('mitStoredTransactionId' in value && value['mitStoredTransactionId'] !== undefined)
        || ('storedCredential' in value && value['storedCredential'] !== undefined)
        || ('orderId' in value && value['orderId'] !== undefined)
        || ('statementDescriptor' in value && value['statementDescriptor'] !== undefined)
        || ('customerIp' in value && value['customerIp'] !== undefined)
        || ('engagedRecoveryState' in value && value['engagedRecoveryState'] !== undefined)
        || ('description' in value && value['description'] !== undefined)
        || ('gatewayFields' in value && value['gatewayFields'] !== undefined)
        || ('gatewaySpecificResponseFields' in value && value['gatewaySpecificResponseFields'] !== undefined)
        || ('paymentPlanData' in value && value['paymentPlanData'] !== undefined)
        || ('recovery' in value && value['recovery'] !== undefined)
        || ('response' in value && value['response'] !== undefined)
        || ('paymentMethod' in value && value['paymentMethod'] !== undefined);
}

export function TransactionResponseFromJSON(json: any): TransactionResponse {
    return TransactionResponseFromJSONTyped(json, false);
}

export function TransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'transactionDate': json['transactionDate'] == null ? undefined : (new Date(json['transactionDate'])),
        'transactionStatus': json['transactionStatus'] == null ? undefined : json['transactionStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'responseCode': json['responseCode'] == null ? undefined : json['responseCode'],
        'transactionType': json['transactionType'] == null ? undefined : json['transactionType'],
        'merchantTransactionId': json['merchantTransactionId'] == null ? undefined : json['merchantTransactionId'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'gatewayRoutingId': json['gatewayRoutingId'] == null ? undefined : json['gatewayRoutingId'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'gatewayType': json['gatewayType'] == null ? undefined : json['gatewayType'],
        'gatewayTransactionId': json['gatewayTransactionId'] == null ? undefined : json['gatewayTransactionId'],
        'acquirerAuthCode': json['acquirerAuthCode'] == null ? undefined : json['acquirerAuthCode'],
        'inlineRetryPreviousTransactionId': json['inlineRetryPreviousTransactionId'] == null ? undefined : json['inlineRetryPreviousTransactionId'],
        'inlineRetryPreviousMerchantTransactionId': json['inlineRetryPreviousMerchantTransactionId'] == null ? undefined : json['inlineRetryPreviousMerchantTransactionId'],
        'isInlineRetry': json['isInlineRetry'] == null ? undefined : json['isInlineRetry'],
        'retryDate': json['retryDate'] == null ? undefined : (new Date(json['retryDate'])),
        'mitStoredTransactionId': json['mitStoredTransactionId'] == null ? undefined : json['mitStoredTransactionId'],
        'storedCredential': json['storedCredential'] == null ? undefined : StoredCredentialResponseFromJSON(json['storedCredential']),
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'statementDescriptor': json['statementDescriptor'] == null ? undefined : json['statementDescriptor'],
        'customerIp': json['customerIp'] == null ? undefined : json['customerIp'],
        'engagedRecoveryState': json['engagedRecoveryState'] == null ? undefined : json['engagedRecoveryState'],
        'description': json['description'] == null ? undefined : json['description'],
        'gatewayFields': json['gatewayFields'] == null ? undefined : json['gatewayFields'],
        'gatewaySpecificResponseFields': json['gatewaySpecificResponseFields'] == null ? undefined : json['gatewaySpecificResponseFields'],
        'paymentPlanData': json['paymentPlanData'] == null ? undefined : PaymentPlanDataFromJSON(json['paymentPlanData']),
        'recovery': json['recovery'] == null ? undefined : RecoveryFromJSON(json['recovery']),
        'response': json['response'] == null ? undefined : TransactionResponseDetailsFromJSON(json['response']),
        'paymentMethod': json['paymentMethod'] == null ? undefined : PaymentMethodResponseFromJSON(json['paymentMethod']),
    };
}

export function TransactionResponseToJSON(json: any): TransactionResponse {
    return TransactionResponseToJSONTyped(json, false);
}

export function TransactionResponseToJSONTyped(value?: TransactionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionId': value['transactionId'],
        'transactionDate': value['transactionDate'] == null ? value['transactionDate'] : value['transactionDate'].toISOString(),
        'transactionStatus': value['transactionStatus'],
        'message': value['message'],
        'responseCode': value['responseCode'],
        'transactionType': value['transactionType'],
        'merchantTransactionId': value['merchantTransactionId'],
        'customerId': value['customerId'],
        'gatewayRoutingId': value['gatewayRoutingId'],
        'currency': value['currency'],
        'amount': value['amount'],
        'gatewayType': value['gatewayType'],
        'gatewayTransactionId': value['gatewayTransactionId'],
        'acquirerAuthCode': value['acquirerAuthCode'],
        'inlineRetryPreviousTransactionId': value['inlineRetryPreviousTransactionId'],
        'inlineRetryPreviousMerchantTransactionId': value['inlineRetryPreviousMerchantTransactionId'],
        'isInlineRetry': value['isInlineRetry'],
        'retryDate': value['retryDate'] == null ? value['retryDate'] : value['retryDate'].toISOString(),
        'mitStoredTransactionId': value['mitStoredTransactionId'],
        'storedCredential': StoredCredentialResponseToJSON(value['storedCredential']),
        'orderId': value['orderId'],
        'statementDescriptor': value['statementDescriptor'],
        'customerIp': value['customerIp'],
        'engagedRecoveryState': value['engagedRecoveryState'],
        'description': value['description'],
        'gatewayFields': value['gatewayFields'],
        'gatewaySpecificResponseFields': value['gatewaySpecificResponseFields'],
        'paymentPlanData': PaymentPlanDataToJSON(value['paymentPlanData']),
        'recovery': RecoveryToJSON(value['recovery']),
        'response': TransactionResponseDetailsToJSON(value['response']),
        'paymentMethod': PaymentMethodResponseToJSON(value['paymentMethod']),
    };
}

