version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/languages/typescript"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/languages/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/languages/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/languages/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/languages/dotnet"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/languages/java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
