# coding: utf-8

"""
    Revaly

    Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header. 

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.

    RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
    Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
    (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreditCard(BaseModel):
    """
    Credit card details for payment processing
    """ # noqa: E501
    number: Annotated[str, Field(strict=True)] = Field(description="Credit card number (will be tokenized)", json_schema_extra={"examples": ["4242424242424242"]})
    card_verification_code: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Card verification code (CVV/CVC)", alias="cardVerificationCode", json_schema_extra={"examples": ["123"]})
    expiry_month: Annotated[str, Field(strict=True)] = Field(description="Expiration month (01-12)", alias="expiryMonth", json_schema_extra={"examples": ["12"]})
    expiry_year: Annotated[str, Field(strict=True)] = Field(description="Expiration year (YYYY)", alias="expiryYear", json_schema_extra={"examples": ["2025"]})
    company: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Card issuing company", json_schema_extra={"examples": ["Visa"]})
    card_type: Optional[StrictStr] = Field(default=None, description="Type of credit card", alias="cardType", json_schema_extra={"examples": ["visa"]})
    __properties: ClassVar[List[str]] = ["number", "cardVerificationCode", "expiryMonth", "expiryYear", "company", "cardType"]

    @field_validator('number')
    def number_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{13,19}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{13,19}$/")
        return value

    @field_validator('card_verification_code')
    def card_verification_code_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9]{3,4}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{3,4}$/")
        return value

    @field_validator('expiry_month')
    def expiry_month_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(0[1-9]|1[0-2])$", value):
            raise ValueError(r"must validate the regular expression /^(0[1-9]|1[0-2])$/")
        return value

    @field_validator('expiry_year')
    def expiry_year_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^20[0-9]{2}$", value):
            raise ValueError(r"must validate the regular expression /^20[0-9]{2}$/")
        return value

    @field_validator('card_type')
    def card_type_validate_enum(cls, value):
        """Open vocabulary (RAP ADR-SDK-023 override): accept unknown enum values.

        The spec's enums are open vocabularies (ADR-SDK-007/010) — new server-side
        values must never break deserialization on success paths, so unknown wire
        values pass through verbatim instead of raising ValueError.
        """
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreditCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if card_verification_code (nullable) is None
        # and model_fields_set contains the field
        if self.card_verification_code is None and "card_verification_code" in self.model_fields_set:
            _dict['cardVerificationCode'] = None

        # set to None if company (nullable) is None
        # and model_fields_set contains the field
        if self.company is None and "company" in self.model_fields_set:
            _dict['company'] = None

        # set to None if card_type (nullable) is None
        # and model_fields_set contains the field
        if self.card_type is None and "card_type" in self.model_fields_set:
            _dict['cardType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreditCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "number": obj.get("number"),
            "cardVerificationCode": obj.get("cardVerificationCode"),
            "expiryMonth": obj.get("expiryMonth"),
            "expiryYear": obj.get("expiryYear"),
            "company": obj.get("company"),
            "cardType": obj.get("cardType")
        })
        return _obj


