/*
 * Revaly
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 
 *
 * The version of the OpenAPI document: 2.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */


package co.revaly.sdk.core.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import co.revaly.sdk.core.model.Address;
import co.revaly.sdk.core.model.CreditCard;
import co.revaly.sdk.core.model.GatewayPaymentMethod;
import co.revaly.sdk.core.model.VaultPaymentMethod;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import co.revaly.sdk.core.ApiClient;
/**
 * Payment method details for either credit card or gatewayPaymentMethodId
 */
@JsonPropertyOrder({
  PaymentMethod.JSON_PROPERTY_FIRST_NAME,
  PaymentMethod.JSON_PROPERTY_LAST_NAME,
  PaymentMethod.JSON_PROPERTY_FULL_NAME,
  PaymentMethod.JSON_PROPERTY_EMAIL,
  PaymentMethod.JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID,
  PaymentMethod.JSON_PROPERTY_PAYMENT_METHOD_ID,
  PaymentMethod.JSON_PROPERTY_ISSUER_IDENTIFICATION_NUMBER,
  PaymentMethod.JSON_PROPERTY_BILLING_ADDRESS,
  PaymentMethod.JSON_PROPERTY_SHIPPING_ADDRESS,
  PaymentMethod.JSON_PROPERTY_CREDIT_CARD,
  PaymentMethod.JSON_PROPERTY_GATEWAY_PAYMENT_METHOD,
  PaymentMethod.JSON_PROPERTY_VAULT_PAYMENT_METHOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class PaymentMethod {
  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private JsonNullable<String> firstName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private JsonNullable<String> lastName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  private JsonNullable<String> fullName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EMAIL = "email";
  private JsonNullable<String> email = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID = "merchantAccountReferenceId";
  private JsonNullable<String> merchantAccountReferenceId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PAYMENT_METHOD_ID = "paymentMethodId";
  private JsonNullable<String> paymentMethodId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ISSUER_IDENTIFICATION_NUMBER = "issuerIdentificationNumber";
  private JsonNullable<String> issuerIdentificationNumber = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BILLING_ADDRESS = "billingAddress";
  @javax.annotation.Nullable
  private Address billingAddress;

  public static final String JSON_PROPERTY_SHIPPING_ADDRESS = "shippingAddress";
  @javax.annotation.Nullable
  private Address shippingAddress;

  public static final String JSON_PROPERTY_CREDIT_CARD = "creditCard";
  @javax.annotation.Nullable
  private CreditCard creditCard;

  public static final String JSON_PROPERTY_GATEWAY_PAYMENT_METHOD = "gatewayPaymentMethod";
  @javax.annotation.Nullable
  private GatewayPaymentMethod gatewayPaymentMethod;

  public static final String JSON_PROPERTY_VAULT_PAYMENT_METHOD = "vaultPaymentMethod";
  @javax.annotation.Nullable
  private VaultPaymentMethod vaultPaymentMethod;

  public PaymentMethod() { 
  }

  public PaymentMethod firstName(@javax.annotation.Nullable String firstName) {
    this.firstName = JsonNullable.<String>of(firstName);
    return this;
  }

  /**
   * Customer&#39;s first name
   * @return firstName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getFirstName() {
        return firstName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFirstName_JsonNullable() {
    return firstName;
  }
  
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  public void setFirstName_JsonNullable(JsonNullable<String> firstName) {
    this.firstName = firstName;
  }

  public void setFirstName(@javax.annotation.Nullable String firstName) {
    this.firstName = JsonNullable.<String>of(firstName);
  }


  public PaymentMethod lastName(@javax.annotation.Nullable String lastName) {
    this.lastName = JsonNullable.<String>of(lastName);
    return this;
  }

  /**
   * Customer&#39;s last name
   * @return lastName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getLastName() {
        return lastName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastName_JsonNullable() {
    return lastName;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  public void setLastName_JsonNullable(JsonNullable<String> lastName) {
    this.lastName = lastName;
  }

  public void setLastName(@javax.annotation.Nullable String lastName) {
    this.lastName = JsonNullable.<String>of(lastName);
  }


  public PaymentMethod fullName(@javax.annotation.Nullable String fullName) {
    this.fullName = JsonNullable.<String>of(fullName);
    return this;
  }

  /**
   * Customer&#39;s full name
   * @return fullName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getFullName() {
        return fullName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFullName_JsonNullable() {
    return fullName;
  }
  
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  public void setFullName_JsonNullable(JsonNullable<String> fullName) {
    this.fullName = fullName;
  }

  public void setFullName(@javax.annotation.Nullable String fullName) {
    this.fullName = JsonNullable.<String>of(fullName);
  }


  public PaymentMethod email(@javax.annotation.Nullable String email) {
    this.email = JsonNullable.<String>of(email);
    return this;
  }

  /**
   * Customer&#39;s email address
   * @return email
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getEmail() {
        return email.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getEmail_JsonNullable() {
    return email;
  }
  
  @JsonProperty(JSON_PROPERTY_EMAIL)
  public void setEmail_JsonNullable(JsonNullable<String> email) {
    this.email = email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = JsonNullable.<String>of(email);
  }


  public PaymentMethod merchantAccountReferenceId(@javax.annotation.Nullable String merchantAccountReferenceId) {
    this.merchantAccountReferenceId = JsonNullable.<String>of(merchantAccountReferenceId);
    return this;
  }

  /**
   * Merchant account identifier at the gateway
   * @return merchantAccountReferenceId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getMerchantAccountReferenceId() {
        return merchantAccountReferenceId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMerchantAccountReferenceId_JsonNullable() {
    return merchantAccountReferenceId;
  }
  
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID)
  public void setMerchantAccountReferenceId_JsonNullable(JsonNullable<String> merchantAccountReferenceId) {
    this.merchantAccountReferenceId = merchantAccountReferenceId;
  }

  public void setMerchantAccountReferenceId(@javax.annotation.Nullable String merchantAccountReferenceId) {
    this.merchantAccountReferenceId = JsonNullable.<String>of(merchantAccountReferenceId);
  }


  public PaymentMethod paymentMethodId(@javax.annotation.Nullable String paymentMethodId) {
    this.paymentMethodId = JsonNullable.<String>of(paymentMethodId);
    return this;
  }

  /**
   * Existing payment method identifier (for updates)
   * @return paymentMethodId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPaymentMethodId() {
        return paymentMethodId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPaymentMethodId_JsonNullable() {
    return paymentMethodId;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_ID)
  public void setPaymentMethodId_JsonNullable(JsonNullable<String> paymentMethodId) {
    this.paymentMethodId = paymentMethodId;
  }

  public void setPaymentMethodId(@javax.annotation.Nullable String paymentMethodId) {
    this.paymentMethodId = JsonNullable.<String>of(paymentMethodId);
  }


  public PaymentMethod issuerIdentificationNumber(@javax.annotation.Nullable String issuerIdentificationNumber) {
    this.issuerIdentificationNumber = JsonNullable.<String>of(issuerIdentificationNumber);
    return this;
  }

  /**
   * Bank Identification Number (BIN). Must contain exactly 6 or 8 digits.
   * @return issuerIdentificationNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getIssuerIdentificationNumber() {
        return issuerIdentificationNumber.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ISSUER_IDENTIFICATION_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getIssuerIdentificationNumber_JsonNullable() {
    return issuerIdentificationNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_ISSUER_IDENTIFICATION_NUMBER)
  public void setIssuerIdentificationNumber_JsonNullable(JsonNullable<String> issuerIdentificationNumber) {
    this.issuerIdentificationNumber = issuerIdentificationNumber;
  }

  public void setIssuerIdentificationNumber(@javax.annotation.Nullable String issuerIdentificationNumber) {
    this.issuerIdentificationNumber = JsonNullable.<String>of(issuerIdentificationNumber);
  }


  public PaymentMethod billingAddress(@javax.annotation.Nullable Address billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

  /**
   * Get billingAddress
   * @return billingAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BILLING_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Address getBillingAddress() {
    return billingAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_BILLING_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingAddress(@javax.annotation.Nullable Address billingAddress) {
    this.billingAddress = billingAddress;
  }


  public PaymentMethod shippingAddress(@javax.annotation.Nullable Address shippingAddress) {
    this.shippingAddress = shippingAddress;
    return this;
  }

  /**
   * Get shippingAddress
   * @return shippingAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHIPPING_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Address getShippingAddress() {
    return shippingAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_SHIPPING_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingAddress(@javax.annotation.Nullable Address shippingAddress) {
    this.shippingAddress = shippingAddress;
  }


  public PaymentMethod creditCard(@javax.annotation.Nullable CreditCard creditCard) {
    this.creditCard = creditCard;
    return this;
  }

  /**
   * Get creditCard
   * @return creditCard
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREDIT_CARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreditCard getCreditCard() {
    return creditCard;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDIT_CARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreditCard(@javax.annotation.Nullable CreditCard creditCard) {
    this.creditCard = creditCard;
  }


  public PaymentMethod gatewayPaymentMethod(@javax.annotation.Nullable GatewayPaymentMethod gatewayPaymentMethod) {
    this.gatewayPaymentMethod = gatewayPaymentMethod;
    return this;
  }

  /**
   * Get gatewayPaymentMethod
   * @return gatewayPaymentMethod
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GATEWAY_PAYMENT_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GatewayPaymentMethod getGatewayPaymentMethod() {
    return gatewayPaymentMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_GATEWAY_PAYMENT_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGatewayPaymentMethod(@javax.annotation.Nullable GatewayPaymentMethod gatewayPaymentMethod) {
    this.gatewayPaymentMethod = gatewayPaymentMethod;
  }


  public PaymentMethod vaultPaymentMethod(@javax.annotation.Nullable VaultPaymentMethod vaultPaymentMethod) {
    this.vaultPaymentMethod = vaultPaymentMethod;
    return this;
  }

  /**
   * Get vaultPaymentMethod
   * @return vaultPaymentMethod
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VAULT_PAYMENT_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VaultPaymentMethod getVaultPaymentMethod() {
    return vaultPaymentMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_VAULT_PAYMENT_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVaultPaymentMethod(@javax.annotation.Nullable VaultPaymentMethod vaultPaymentMethod) {
    this.vaultPaymentMethod = vaultPaymentMethod;
  }


  /**
   * Return true if this PaymentMethod object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethod paymentMethod = (PaymentMethod) o;
    return equalsNullable(this.firstName, paymentMethod.firstName) &&
        equalsNullable(this.lastName, paymentMethod.lastName) &&
        equalsNullable(this.fullName, paymentMethod.fullName) &&
        equalsNullable(this.email, paymentMethod.email) &&
        equalsNullable(this.merchantAccountReferenceId, paymentMethod.merchantAccountReferenceId) &&
        equalsNullable(this.paymentMethodId, paymentMethod.paymentMethodId) &&
        equalsNullable(this.issuerIdentificationNumber, paymentMethod.issuerIdentificationNumber) &&
        Objects.equals(this.billingAddress, paymentMethod.billingAddress) &&
        Objects.equals(this.shippingAddress, paymentMethod.shippingAddress) &&
        Objects.equals(this.creditCard, paymentMethod.creditCard) &&
        Objects.equals(this.gatewayPaymentMethod, paymentMethod.gatewayPaymentMethod) &&
        Objects.equals(this.vaultPaymentMethod, paymentMethod.vaultPaymentMethod);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(firstName), hashCodeNullable(lastName), hashCodeNullable(fullName), hashCodeNullable(email), hashCodeNullable(merchantAccountReferenceId), hashCodeNullable(paymentMethodId), hashCodeNullable(issuerIdentificationNumber), billingAddress, shippingAddress, creditCard, gatewayPaymentMethod, vaultPaymentMethod);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethod {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    merchantAccountReferenceId: ").append(toIndentedString(merchantAccountReferenceId)).append("\n");
    sb.append("    paymentMethodId: ").append(toIndentedString(paymentMethodId)).append("\n");
    sb.append("    issuerIdentificationNumber: ").append(toIndentedString(issuerIdentificationNumber)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    sb.append("    creditCard: ").append(toIndentedString(creditCard)).append("\n");
    sb.append("    gatewayPaymentMethod: ").append(toIndentedString(gatewayPaymentMethod)).append("\n");
    sb.append("    vaultPaymentMethod: ").append(toIndentedString(vaultPaymentMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfirstName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstName()))));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastName()))));
    }

    // add `fullName` to the URL query string
    if (getFullName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfullName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFullName()))));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `merchantAccountReferenceId` to the URL query string
    if (getMerchantAccountReferenceId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchantAccountReferenceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantAccountReferenceId()))));
    }

    // add `paymentMethodId` to the URL query string
    if (getPaymentMethodId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentMethodId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentMethodId()))));
    }

    // add `issuerIdentificationNumber` to the URL query string
    if (getIssuerIdentificationNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sissuerIdentificationNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIssuerIdentificationNumber()))));
    }

    // add `billingAddress` to the URL query string
    if (getBillingAddress() != null) {
      joiner.add(getBillingAddress().toUrlQueryString(prefix + "billingAddress" + suffix));
    }

    // add `shippingAddress` to the URL query string
    if (getShippingAddress() != null) {
      joiner.add(getShippingAddress().toUrlQueryString(prefix + "shippingAddress" + suffix));
    }

    // add `creditCard` to the URL query string
    if (getCreditCard() != null) {
      joiner.add(getCreditCard().toUrlQueryString(prefix + "creditCard" + suffix));
    }

    // add `gatewayPaymentMethod` to the URL query string
    if (getGatewayPaymentMethod() != null) {
      joiner.add(getGatewayPaymentMethod().toUrlQueryString(prefix + "gatewayPaymentMethod" + suffix));
    }

    // add `vaultPaymentMethod` to the URL query string
    if (getVaultPaymentMethod() != null) {
      joiner.add(getVaultPaymentMethod().toUrlQueryString(prefix + "vaultPaymentMethod" + suffix));
    }

    return joiner.toString();
  }
}

