/*
 * Revaly
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 
 *
 * The version of the OpenAPI document: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */


package co.revaly.sdk.core.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import co.revaly.sdk.core.ApiClient;
/**
 * Merchant identification and account signals. acquirerMerchantId is hard-required by RTN downstream but optional in this API.
 */
@JsonPropertyOrder({
  RtnDataMerchantData.JSON_PROPERTY_ACQUIRER_MERCHANT_ID,
  RtnDataMerchantData.JSON_PROPERTY_ISSUER_MERCHANT_ID,
  RtnDataMerchantData.JSON_PROPERTY_ACQUIRER_BIN,
  RtnDataMerchantData.JSON_PROPERTY_ACQUIRER_REFERENCE_NUMBER,
  RtnDataMerchantData.JSON_PROPERTY_MERCHANT_NAME,
  RtnDataMerchantData.JSON_PROPERTY_MERCHANT_ACCOUNT_AGE_INDICATOR,
  RtnDataMerchantData.JSON_PROPERTY_MERCHANT_ACCOUNT_OPENED_DATE,
  RtnDataMerchantData.JSON_PROPERTY_IS_TENURED_MERCHANT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class RtnDataMerchantData {
  public static final String JSON_PROPERTY_ACQUIRER_MERCHANT_ID = "acquirerMerchantId";
  @javax.annotation.Nullable
  private String acquirerMerchantId;

  public static final String JSON_PROPERTY_ISSUER_MERCHANT_ID = "issuerMerchantId";
  @javax.annotation.Nullable
  private String issuerMerchantId;

  public static final String JSON_PROPERTY_ACQUIRER_BIN = "acquirerBin";
  @javax.annotation.Nullable
  private String acquirerBin;

  public static final String JSON_PROPERTY_ACQUIRER_REFERENCE_NUMBER = "acquirerReferenceNumber";
  @javax.annotation.Nullable
  private String acquirerReferenceNumber;

  public static final String JSON_PROPERTY_MERCHANT_NAME = "merchantName";
  @javax.annotation.Nullable
  private String merchantName;

  /**
   * Merchant account age token.
   */
  public enum MerchantAccountAgeIndicatorEnum {
    _01(String.valueOf("01")),
    
    _03(String.valueOf("03")),
    
    _05(String.valueOf("05")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    MerchantAccountAgeIndicatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MerchantAccountAgeIndicatorEnum fromValue(String value) {
      for (MerchantAccountAgeIndicatorEnum b : MerchantAccountAgeIndicatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT_AGE_INDICATOR = "merchantAccountAgeIndicator";
  @javax.annotation.Nullable
  private MerchantAccountAgeIndicatorEnum merchantAccountAgeIndicator;

  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT_OPENED_DATE = "merchantAccountOpenedDate";
  @javax.annotation.Nullable
  private String merchantAccountOpenedDate;

  public static final String JSON_PROPERTY_IS_TENURED_MERCHANT = "isTenuredMerchant";
  @javax.annotation.Nullable
  private Boolean isTenuredMerchant;

  public RtnDataMerchantData() { 
  }

  public RtnDataMerchantData acquirerMerchantId(@javax.annotation.Nullable String acquirerMerchantId) {
    this.acquirerMerchantId = acquirerMerchantId;
    return this;
  }

  /**
   * Acquirer-assigned merchant identifier. Hard-required by RTN; optional in this API.
   * @return acquirerMerchantId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACQUIRER_MERCHANT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAcquirerMerchantId() {
    return acquirerMerchantId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACQUIRER_MERCHANT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcquirerMerchantId(@javax.annotation.Nullable String acquirerMerchantId) {
    this.acquirerMerchantId = acquirerMerchantId;
  }


  public RtnDataMerchantData issuerMerchantId(@javax.annotation.Nullable String issuerMerchantId) {
    this.issuerMerchantId = issuerMerchantId;
    return this;
  }

  /**
   * Issuer-side merchant identifier, if known.
   * @return issuerMerchantId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUER_MERCHANT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIssuerMerchantId() {
    return issuerMerchantId;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUER_MERCHANT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerMerchantId(@javax.annotation.Nullable String issuerMerchantId) {
    this.issuerMerchantId = issuerMerchantId;
  }


  public RtnDataMerchantData acquirerBin(@javax.annotation.Nullable String acquirerBin) {
    this.acquirerBin = acquirerBin;
    return this;
  }

  /**
   * BIN of the acquiring institution.
   * @return acquirerBin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACQUIRER_BIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAcquirerBin() {
    return acquirerBin;
  }


  @JsonProperty(value = JSON_PROPERTY_ACQUIRER_BIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcquirerBin(@javax.annotation.Nullable String acquirerBin) {
    this.acquirerBin = acquirerBin;
  }


  public RtnDataMerchantData acquirerReferenceNumber(@javax.annotation.Nullable String acquirerReferenceNumber) {
    this.acquirerReferenceNumber = acquirerReferenceNumber;
    return this;
  }

  /**
   * Acquirer reference number (ARN) for network clearing.
   * @return acquirerReferenceNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACQUIRER_REFERENCE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAcquirerReferenceNumber() {
    return acquirerReferenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_ACQUIRER_REFERENCE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcquirerReferenceNumber(@javax.annotation.Nullable String acquirerReferenceNumber) {
    this.acquirerReferenceNumber = acquirerReferenceNumber;
  }


  public RtnDataMerchantData merchantName(@javax.annotation.Nullable String merchantName) {
    this.merchantName = merchantName;
    return this;
  }

  /**
   * Merchant display name as it appears to the customer.
   * @return merchantName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MERCHANT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMerchantName() {
    return merchantName;
  }


  @JsonProperty(value = JSON_PROPERTY_MERCHANT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantName(@javax.annotation.Nullable String merchantName) {
    this.merchantName = merchantName;
  }


  public RtnDataMerchantData merchantAccountAgeIndicator(@javax.annotation.Nullable MerchantAccountAgeIndicatorEnum merchantAccountAgeIndicator) {
    this.merchantAccountAgeIndicator = merchantAccountAgeIndicator;
    return this;
  }

  /**
   * Merchant account age token.
   * @return merchantAccountAgeIndicator
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MERCHANT_ACCOUNT_AGE_INDICATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MerchantAccountAgeIndicatorEnum getMerchantAccountAgeIndicator() {
    return merchantAccountAgeIndicator;
  }


  @JsonProperty(value = JSON_PROPERTY_MERCHANT_ACCOUNT_AGE_INDICATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantAccountAgeIndicator(@javax.annotation.Nullable MerchantAccountAgeIndicatorEnum merchantAccountAgeIndicator) {
    this.merchantAccountAgeIndicator = merchantAccountAgeIndicator;
  }


  public RtnDataMerchantData merchantAccountOpenedDate(@javax.annotation.Nullable String merchantAccountOpenedDate) {
    this.merchantAccountOpenedDate = merchantAccountOpenedDate;
    return this;
  }

  /**
   * Date the merchant account was created. Format YYYYMMDD.
   * @return merchantAccountOpenedDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MERCHANT_ACCOUNT_OPENED_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMerchantAccountOpenedDate() {
    return merchantAccountOpenedDate;
  }


  @JsonProperty(value = JSON_PROPERTY_MERCHANT_ACCOUNT_OPENED_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantAccountOpenedDate(@javax.annotation.Nullable String merchantAccountOpenedDate) {
    this.merchantAccountOpenedDate = merchantAccountOpenedDate;
  }


  public RtnDataMerchantData isTenuredMerchant(@javax.annotation.Nullable Boolean isTenuredMerchant) {
    this.isTenuredMerchant = isTenuredMerchant;
    return this;
  }

  /**
   * True if the merchant has a long-standing, established account relationship.
   * @return isTenuredMerchant
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_TENURED_MERCHANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsTenuredMerchant() {
    return isTenuredMerchant;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_TENURED_MERCHANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsTenuredMerchant(@javax.annotation.Nullable Boolean isTenuredMerchant) {
    this.isTenuredMerchant = isTenuredMerchant;
  }


  /**
   * Return true if this RtnData_merchantData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RtnDataMerchantData rtnDataMerchantData = (RtnDataMerchantData) o;
    return Objects.equals(this.acquirerMerchantId, rtnDataMerchantData.acquirerMerchantId) &&
        Objects.equals(this.issuerMerchantId, rtnDataMerchantData.issuerMerchantId) &&
        Objects.equals(this.acquirerBin, rtnDataMerchantData.acquirerBin) &&
        Objects.equals(this.acquirerReferenceNumber, rtnDataMerchantData.acquirerReferenceNumber) &&
        Objects.equals(this.merchantName, rtnDataMerchantData.merchantName) &&
        Objects.equals(this.merchantAccountAgeIndicator, rtnDataMerchantData.merchantAccountAgeIndicator) &&
        Objects.equals(this.merchantAccountOpenedDate, rtnDataMerchantData.merchantAccountOpenedDate) &&
        Objects.equals(this.isTenuredMerchant, rtnDataMerchantData.isTenuredMerchant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acquirerMerchantId, issuerMerchantId, acquirerBin, acquirerReferenceNumber, merchantName, merchantAccountAgeIndicator, merchantAccountOpenedDate, isTenuredMerchant);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RtnDataMerchantData {\n");
    sb.append("    acquirerMerchantId: ").append(toIndentedString(acquirerMerchantId)).append("\n");
    sb.append("    issuerMerchantId: ").append(toIndentedString(issuerMerchantId)).append("\n");
    sb.append("    acquirerBin: ").append(toIndentedString(acquirerBin)).append("\n");
    sb.append("    acquirerReferenceNumber: ").append(toIndentedString(acquirerReferenceNumber)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    merchantAccountAgeIndicator: ").append(toIndentedString(merchantAccountAgeIndicator)).append("\n");
    sb.append("    merchantAccountOpenedDate: ").append(toIndentedString(merchantAccountOpenedDate)).append("\n");
    sb.append("    isTenuredMerchant: ").append(toIndentedString(isTenuredMerchant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `acquirerMerchantId` to the URL query string
    if (getAcquirerMerchantId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sacquirerMerchantId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcquirerMerchantId()))));
    }

    // add `issuerMerchantId` to the URL query string
    if (getIssuerMerchantId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sissuerMerchantId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIssuerMerchantId()))));
    }

    // add `acquirerBin` to the URL query string
    if (getAcquirerBin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sacquirerBin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcquirerBin()))));
    }

    // add `acquirerReferenceNumber` to the URL query string
    if (getAcquirerReferenceNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sacquirerReferenceNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcquirerReferenceNumber()))));
    }

    // add `merchantName` to the URL query string
    if (getMerchantName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchantName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantName()))));
    }

    // add `merchantAccountAgeIndicator` to the URL query string
    if (getMerchantAccountAgeIndicator() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchantAccountAgeIndicator%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantAccountAgeIndicator()))));
    }

    // add `merchantAccountOpenedDate` to the URL query string
    if (getMerchantAccountOpenedDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchantAccountOpenedDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantAccountOpenedDate()))));
    }

    // add `isTenuredMerchant` to the URL query string
    if (getIsTenuredMerchant() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisTenuredMerchant%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsTenuredMerchant()))));
    }

    return joiner.toString();
  }
}

