/*
 * Revaly
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */


package co.revaly.sdk.core.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import co.revaly.sdk.core.model.PaymentMethodResponse;
import co.revaly.sdk.core.model.TransactionGateway;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import co.revaly.sdk.core.ApiClient;
/**
 * Transaction item returned from the list transactions endpoint. In simplified mode, only a subset of fields is returned (transactionId, transactionDate, transactionStatus, responseCode, message, transactionType, retryDate, amount, initialMerchantTransactionId, paymentMethodStorageState, completionStatus). In detailed mode, additional fields are returned (excludes customVariable1-5 and initialTransactionId). 
 */
@JsonPropertyOrder({
  TransactionListItem.JSON_PROPERTY_TRANSACTION_ID,
  TransactionListItem.JSON_PROPERTY_TRANSACTION_DATE,
  TransactionListItem.JSON_PROPERTY_TRANSACTION_STATUS,
  TransactionListItem.JSON_PROPERTY_RESPONSE_CODE,
  TransactionListItem.JSON_PROPERTY_MESSAGE,
  TransactionListItem.JSON_PROPERTY_TRANSACTION_TYPE,
  TransactionListItem.JSON_PROPERTY_RETRY_DATE,
  TransactionListItem.JSON_PROPERTY_AMOUNT,
  TransactionListItem.JSON_PROPERTY_INITIAL_MERCHANT_TRANSACTION_ID,
  TransactionListItem.JSON_PROPERTY_STORAGE_STATE,
  TransactionListItem.JSON_PROPERTY_COMPLETION_STATUS,
  TransactionListItem.JSON_PROPERTY_GATEWAY_SPECIFIC_RESPONSE_FIELDS,
  TransactionListItem.JSON_PROPERTY_GATEWAY_SPECIFIC_FIELDS,
  TransactionListItem.JSON_PROPERTY_ACQUIRER_AUTH_CODE,
  TransactionListItem.JSON_PROPERTY_GATEWAY_TRANSACTION_ID,
  TransactionListItem.JSON_PROPERTY_GATEWAY_PAYMENT_METHOD_ID,
  TransactionListItem.JSON_PROPERTY_ENGAGED_RECOVERY_STATE,
  TransactionListItem.JSON_PROPERTY_CURRENCY_CODE,
  TransactionListItem.JSON_PROPERTY_MERCHANT_TRANSACTION_ID,
  TransactionListItem.JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID,
  TransactionListItem.JSON_PROPERTY_CUSTOMER_ID,
  TransactionListItem.JSON_PROPERTY_ORDER_ID,
  TransactionListItem.JSON_PROPERTY_STATEMENT_DESCRIPTOR,
  TransactionListItem.JSON_PROPERTY_PAYMENT_METHOD_ID,
  TransactionListItem.JSON_PROPERTY_PAYMENT_METHOD_STORAGE_STATE,
  TransactionListItem.JSON_PROPERTY_PAYMENT_METHOD_TYPE,
  TransactionListItem.JSON_PROPERTY_PAYMENT_METHOD_MERCHANT_ACCOUNT_REFERENCE_ID,
  TransactionListItem.JSON_PROPERTY_ERROR_CODE,
  TransactionListItem.JSON_PROPERTY_ERROR_DETAIL,
  TransactionListItem.JSON_PROPERTY_AVS_CODE,
  TransactionListItem.JSON_PROPERTY_GATEWAY,
  TransactionListItem.JSON_PROPERTY_PAYMENT_METHOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TransactionListItem {
  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  private JsonNullable<String> transactionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TRANSACTION_DATE = "transactionDate";
  @javax.annotation.Nullable
  private OffsetDateTime transactionDate;

  public static final String JSON_PROPERTY_TRANSACTION_STATUS = "transactionStatus";
  @javax.annotation.Nullable
  private Integer transactionStatus;

  public static final String JSON_PROPERTY_RESPONSE_CODE = "responseCode";
  private JsonNullable<String> responseCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private JsonNullable<String> message = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transactionType";
  private JsonNullable<String> transactionType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RETRY_DATE = "retryDate";
  private JsonNullable<OffsetDateTime> retryDate = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private JsonNullable<Long> amount = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_INITIAL_MERCHANT_TRANSACTION_ID = "initialMerchantTransactionId";
  private JsonNullable<String> initialMerchantTransactionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STORAGE_STATE = "storageState";
  private JsonNullable<String> storageState = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COMPLETION_STATUS = "completionStatus";
  private JsonNullable<String> completionStatus = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GATEWAY_SPECIFIC_RESPONSE_FIELDS = "gatewaySpecificResponseFields";
  private JsonNullable<Map<String, Object>> gatewaySpecificResponseFields = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_GATEWAY_SPECIFIC_FIELDS = "gatewaySpecificFields";
  private JsonNullable<Map<String, Object>> gatewaySpecificFields = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_ACQUIRER_AUTH_CODE = "acquirerAuthCode";
  private JsonNullable<String> acquirerAuthCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GATEWAY_TRANSACTION_ID = "gatewayTransactionId";
  private JsonNullable<String> gatewayTransactionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GATEWAY_PAYMENT_METHOD_ID = "gatewayPaymentMethodId";
  private JsonNullable<String> gatewayPaymentMethodId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ENGAGED_RECOVERY_STATE = "engagedRecoveryState";
  private JsonNullable<Integer> engagedRecoveryState = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currencyCode";
  private JsonNullable<String> currencyCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MERCHANT_TRANSACTION_ID = "merchantTransactionId";
  private JsonNullable<String> merchantTransactionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID = "merchantAccountReferenceId";
  private JsonNullable<String> merchantAccountReferenceId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private JsonNullable<String> customerId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  private JsonNullable<String> orderId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STATEMENT_DESCRIPTOR = "statementDescriptor";
  private JsonNullable<String> statementDescriptor = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PAYMENT_METHOD_ID = "paymentMethodId";
  private JsonNullable<String> paymentMethodId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PAYMENT_METHOD_STORAGE_STATE = "paymentMethodStorageState";
  private JsonNullable<String> paymentMethodStorageState = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PAYMENT_METHOD_TYPE = "paymentMethodType";
  private JsonNullable<String> paymentMethodType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PAYMENT_METHOD_MERCHANT_ACCOUNT_REFERENCE_ID = "paymentMethodMerchantAccountReferenceId";
  private JsonNullable<String> paymentMethodMerchantAccountReferenceId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  private JsonNullable<String> errorCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ERROR_DETAIL = "errorDetail";
  private JsonNullable<String> errorDetail = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVS_CODE = "avsCode";
  private JsonNullable<String> avsCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GATEWAY = "gateway";
  private JsonNullable<TransactionGateway> gateway = JsonNullable.<TransactionGateway>undefined();

  public static final String JSON_PROPERTY_PAYMENT_METHOD = "paymentMethod";
  private JsonNullable<PaymentMethodResponse> paymentMethod = JsonNullable.<PaymentMethodResponse>undefined();

  public TransactionListItem() { 
  }

  public TransactionListItem transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = JsonNullable.<String>of(transactionId);
    return this;
  }

  /**
   * Unique transaction identifier
   * @return transactionId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTransactionId() {
        return transactionId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTransactionId_JsonNullable() {
    return transactionId;
  }
  
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  public void setTransactionId_JsonNullable(JsonNullable<String> transactionId) {
    this.transactionId = transactionId;
  }

  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = JsonNullable.<String>of(transactionId);
  }


  public TransactionListItem transactionDate(@javax.annotation.Nullable OffsetDateTime transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

  /**
   * Date and time when the transaction was processed (ISO 8601)
   * @return transactionDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTransactionDate() {
    return transactionDate;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionDate(@javax.annotation.Nullable OffsetDateTime transactionDate) {
    this.transactionDate = transactionDate;
  }


  public TransactionListItem transactionStatus(@javax.annotation.Nullable Integer transactionStatus) {
    this.transactionStatus = transactionStatus;
    return this;
  }

  /**
   * Current status of the transaction (1 &#x3D; Approved, 2 &#x3D; Declined, 3 &#x3D; Error)
   * @return transactionStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTransactionStatus() {
    return transactionStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionStatus(@javax.annotation.Nullable Integer transactionStatus) {
    this.transactionStatus = transactionStatus;
  }


  public TransactionListItem responseCode(@javax.annotation.Nullable String responseCode) {
    this.responseCode = JsonNullable.<String>of(responseCode);
    return this;
  }

  /**
   * Response code from the processing result
   * @return responseCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getResponseCode() {
        return responseCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RESPONSE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getResponseCode_JsonNullable() {
    return responseCode;
  }
  
  @JsonProperty(JSON_PROPERTY_RESPONSE_CODE)
  public void setResponseCode_JsonNullable(JsonNullable<String> responseCode) {
    this.responseCode = responseCode;
  }

  public void setResponseCode(@javax.annotation.Nullable String responseCode) {
    this.responseCode = JsonNullable.<String>of(responseCode);
  }


  public TransactionListItem message(@javax.annotation.Nullable String message) {
    this.message = JsonNullable.<String>of(message);
    return this;
  }

  /**
   * Human-readable message about the transaction result
   * @return message
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getMessage() {
        return message.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMessage_JsonNullable() {
    return message;
  }
  
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  public void setMessage_JsonNullable(JsonNullable<String> message) {
    this.message = message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = JsonNullable.<String>of(message);
  }


  public TransactionListItem transactionType(@javax.annotation.Nullable String transactionType) {
    this.transactionType = JsonNullable.<String>of(transactionType);
    return this;
  }

  /**
   * Type of transaction performed
   * @return transactionType
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTransactionType() {
        return transactionType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTransactionType_JsonNullable() {
    return transactionType;
  }
  
  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  public void setTransactionType_JsonNullable(JsonNullable<String> transactionType) {
    this.transactionType = transactionType;
  }

  public void setTransactionType(@javax.annotation.Nullable String transactionType) {
    this.transactionType = JsonNullable.<String>of(transactionType);
  }


  public TransactionListItem retryDate(@javax.annotation.Nullable OffsetDateTime retryDate) {
    this.retryDate = JsonNullable.<OffsetDateTime>of(retryDate);
    return this;
  }

  /**
   * Scheduled retry date, if applicable
   * @return retryDate
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getRetryDate() {
        return retryDate.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_RETRY_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getRetryDate_JsonNullable() {
    return retryDate;
  }
  
  @JsonProperty(JSON_PROPERTY_RETRY_DATE)
  public void setRetryDate_JsonNullable(JsonNullable<OffsetDateTime> retryDate) {
    this.retryDate = retryDate;
  }

  public void setRetryDate(@javax.annotation.Nullable OffsetDateTime retryDate) {
    this.retryDate = JsonNullable.<OffsetDateTime>of(retryDate);
  }


  public TransactionListItem amount(@javax.annotation.Nullable Long amount) {
    this.amount = JsonNullable.<Long>of(amount);
    return this;
  }

  /**
   * Transaction amount in smallest currency unit (e.g., cents for USD)
   * @return amount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Long getAmount() {
        return amount.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getAmount_JsonNullable() {
    return amount;
  }
  
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  public void setAmount_JsonNullable(JsonNullable<Long> amount) {
    this.amount = amount;
  }

  public void setAmount(@javax.annotation.Nullable Long amount) {
    this.amount = JsonNullable.<Long>of(amount);
  }


  public TransactionListItem initialMerchantTransactionId(@javax.annotation.Nullable String initialMerchantTransactionId) {
    this.initialMerchantTransactionId = JsonNullable.<String>of(initialMerchantTransactionId);
    return this;
  }

  /**
   * The merchant transaction ID of the initial transaction in the recovery chain
   * @return initialMerchantTransactionId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getInitialMerchantTransactionId() {
        return initialMerchantTransactionId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_INITIAL_MERCHANT_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getInitialMerchantTransactionId_JsonNullable() {
    return initialMerchantTransactionId;
  }
  
  @JsonProperty(JSON_PROPERTY_INITIAL_MERCHANT_TRANSACTION_ID)
  public void setInitialMerchantTransactionId_JsonNullable(JsonNullable<String> initialMerchantTransactionId) {
    this.initialMerchantTransactionId = initialMerchantTransactionId;
  }

  public void setInitialMerchantTransactionId(@javax.annotation.Nullable String initialMerchantTransactionId) {
    this.initialMerchantTransactionId = JsonNullable.<String>of(initialMerchantTransactionId);
  }


  public TransactionListItem storageState(@javax.annotation.Nullable String storageState) {
    this.storageState = JsonNullable.<String>of(storageState);
    return this;
  }

  /**
   * Payment method storage state at the time of transaction
   * @return storageState
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getStorageState() {
        return storageState.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STORAGE_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getStorageState_JsonNullable() {
    return storageState;
  }
  
  @JsonProperty(JSON_PROPERTY_STORAGE_STATE)
  public void setStorageState_JsonNullable(JsonNullable<String> storageState) {
    this.storageState = storageState;
  }

  public void setStorageState(@javax.annotation.Nullable String storageState) {
    this.storageState = JsonNullable.<String>of(storageState);
  }


  public TransactionListItem completionStatus(@javax.annotation.Nullable String completionStatus) {
    this.completionStatus = JsonNullable.<String>of(completionStatus);
    return this;
  }

  /**
   * Recovery completion status of the transaction (e.g., RecoverySuccessful, RecoveryDeclined)
   * @return completionStatus
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCompletionStatus() {
        return completionStatus.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_COMPLETION_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCompletionStatus_JsonNullable() {
    return completionStatus;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPLETION_STATUS)
  public void setCompletionStatus_JsonNullable(JsonNullable<String> completionStatus) {
    this.completionStatus = completionStatus;
  }

  public void setCompletionStatus(@javax.annotation.Nullable String completionStatus) {
    this.completionStatus = JsonNullable.<String>of(completionStatus);
  }


  public TransactionListItem gatewaySpecificResponseFields(@javax.annotation.Nullable Map<String, Object> gatewaySpecificResponseFields) {
    this.gatewaySpecificResponseFields = JsonNullable.<Map<String, Object>>of(gatewaySpecificResponseFields);
    return this;
  }

  public TransactionListItem putGatewaySpecificResponseFieldsItem(String key, Object gatewaySpecificResponseFieldsItem) {
    if (this.gatewaySpecificResponseFields == null || !this.gatewaySpecificResponseFields.isPresent()) {
      this.gatewaySpecificResponseFields = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.gatewaySpecificResponseFields.get().put(key, gatewaySpecificResponseFieldsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Gateway-specific response fields returned directly by the payment processor. Keyed by gateway type (e.g., chase_payment_tech, stripe_payment_intents, worldpay_litle). 
   * @return gatewaySpecificResponseFields
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getGatewaySpecificResponseFields() {
        return gatewaySpecificResponseFields.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GATEWAY_SPECIFIC_RESPONSE_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getGatewaySpecificResponseFields_JsonNullable() {
    return gatewaySpecificResponseFields;
  }
  
  @JsonProperty(JSON_PROPERTY_GATEWAY_SPECIFIC_RESPONSE_FIELDS)
  public void setGatewaySpecificResponseFields_JsonNullable(JsonNullable<Map<String, Object>> gatewaySpecificResponseFields) {
    this.gatewaySpecificResponseFields = gatewaySpecificResponseFields;
  }

  public void setGatewaySpecificResponseFields(@javax.annotation.Nullable Map<String, Object> gatewaySpecificResponseFields) {
    this.gatewaySpecificResponseFields = JsonNullable.<Map<String, Object>>of(gatewaySpecificResponseFields);
  }


  public TransactionListItem gatewaySpecificFields(@javax.annotation.Nullable Map<String, Object> gatewaySpecificFields) {
    this.gatewaySpecificFields = JsonNullable.<Map<String, Object>>of(gatewaySpecificFields);
    return this;
  }

  public TransactionListItem putGatewaySpecificFieldsItem(String key, Object gatewaySpecificFieldsItem) {
    if (this.gatewaySpecificFields == null || !this.gatewaySpecificFields.isPresent()) {
      this.gatewaySpecificFields = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.gatewaySpecificFields.get().put(key, gatewaySpecificFieldsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Gateway-specific request fields sent to the payment processor. Keyed by gateway type (e.g., chase_payment_tech, stripe_payment_intents, worldpay_litle). 
   * @return gatewaySpecificFields
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getGatewaySpecificFields() {
        return gatewaySpecificFields.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GATEWAY_SPECIFIC_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getGatewaySpecificFields_JsonNullable() {
    return gatewaySpecificFields;
  }
  
  @JsonProperty(JSON_PROPERTY_GATEWAY_SPECIFIC_FIELDS)
  public void setGatewaySpecificFields_JsonNullable(JsonNullable<Map<String, Object>> gatewaySpecificFields) {
    this.gatewaySpecificFields = gatewaySpecificFields;
  }

  public void setGatewaySpecificFields(@javax.annotation.Nullable Map<String, Object> gatewaySpecificFields) {
    this.gatewaySpecificFields = JsonNullable.<Map<String, Object>>of(gatewaySpecificFields);
  }


  public TransactionListItem acquirerAuthCode(@javax.annotation.Nullable String acquirerAuthCode) {
    this.acquirerAuthCode = JsonNullable.<String>of(acquirerAuthCode);
    return this;
  }

  /**
   * Authorization code returned by the acquiring bank
   * @return acquirerAuthCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getAcquirerAuthCode() {
        return acquirerAuthCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ACQUIRER_AUTH_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAcquirerAuthCode_JsonNullable() {
    return acquirerAuthCode;
  }
  
  @JsonProperty(JSON_PROPERTY_ACQUIRER_AUTH_CODE)
  public void setAcquirerAuthCode_JsonNullable(JsonNullable<String> acquirerAuthCode) {
    this.acquirerAuthCode = acquirerAuthCode;
  }

  public void setAcquirerAuthCode(@javax.annotation.Nullable String acquirerAuthCode) {
    this.acquirerAuthCode = JsonNullable.<String>of(acquirerAuthCode);
  }


  public TransactionListItem gatewayTransactionId(@javax.annotation.Nullable String gatewayTransactionId) {
    this.gatewayTransactionId = JsonNullable.<String>of(gatewayTransactionId);
    return this;
  }

  /**
   * Gateway-specific transaction identifier
   * @return gatewayTransactionId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGatewayTransactionId() {
        return gatewayTransactionId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GATEWAY_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGatewayTransactionId_JsonNullable() {
    return gatewayTransactionId;
  }
  
  @JsonProperty(JSON_PROPERTY_GATEWAY_TRANSACTION_ID)
  public void setGatewayTransactionId_JsonNullable(JsonNullable<String> gatewayTransactionId) {
    this.gatewayTransactionId = gatewayTransactionId;
  }

  public void setGatewayTransactionId(@javax.annotation.Nullable String gatewayTransactionId) {
    this.gatewayTransactionId = JsonNullable.<String>of(gatewayTransactionId);
  }


  public TransactionListItem gatewayPaymentMethodId(@javax.annotation.Nullable String gatewayPaymentMethodId) {
    this.gatewayPaymentMethodId = JsonNullable.<String>of(gatewayPaymentMethodId);
    return this;
  }

  /**
   * Gateway-specific payment method identifier
   * @return gatewayPaymentMethodId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGatewayPaymentMethodId() {
        return gatewayPaymentMethodId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GATEWAY_PAYMENT_METHOD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGatewayPaymentMethodId_JsonNullable() {
    return gatewayPaymentMethodId;
  }
  
  @JsonProperty(JSON_PROPERTY_GATEWAY_PAYMENT_METHOD_ID)
  public void setGatewayPaymentMethodId_JsonNullable(JsonNullable<String> gatewayPaymentMethodId) {
    this.gatewayPaymentMethodId = gatewayPaymentMethodId;
  }

  public void setGatewayPaymentMethodId(@javax.annotation.Nullable String gatewayPaymentMethodId) {
    this.gatewayPaymentMethodId = JsonNullable.<String>of(gatewayPaymentMethodId);
  }


  public TransactionListItem engagedRecoveryState(@javax.annotation.Nullable Integer engagedRecoveryState) {
    this.engagedRecoveryState = JsonNullable.<Integer>of(engagedRecoveryState);
    return this;
  }

  /**
   * Recovery state indicator (null/0 &#x3D; not engaged, 1+ &#x3D; recovery level)
   * @return engagedRecoveryState
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getEngagedRecoveryState() {
        return engagedRecoveryState.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ENGAGED_RECOVERY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getEngagedRecoveryState_JsonNullable() {
    return engagedRecoveryState;
  }
  
  @JsonProperty(JSON_PROPERTY_ENGAGED_RECOVERY_STATE)
  public void setEngagedRecoveryState_JsonNullable(JsonNullable<Integer> engagedRecoveryState) {
    this.engagedRecoveryState = engagedRecoveryState;
  }

  public void setEngagedRecoveryState(@javax.annotation.Nullable Integer engagedRecoveryState) {
    this.engagedRecoveryState = JsonNullable.<Integer>of(engagedRecoveryState);
  }


  public TransactionListItem currencyCode(@javax.annotation.Nullable String currencyCode) {
    this.currencyCode = JsonNullable.<String>of(currencyCode);
    return this;
  }

  /**
   * Transaction currency code (ISO 4217)
   * @return currencyCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCurrencyCode() {
        return currencyCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CURRENCY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCurrencyCode_JsonNullable() {
    return currencyCode;
  }
  
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  public void setCurrencyCode_JsonNullable(JsonNullable<String> currencyCode) {
    this.currencyCode = currencyCode;
  }

  public void setCurrencyCode(@javax.annotation.Nullable String currencyCode) {
    this.currencyCode = JsonNullable.<String>of(currencyCode);
  }


  public TransactionListItem merchantTransactionId(@javax.annotation.Nullable String merchantTransactionId) {
    this.merchantTransactionId = JsonNullable.<String>of(merchantTransactionId);
    return this;
  }

  /**
   * Merchant-provided transaction identifier
   * @return merchantTransactionId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getMerchantTransactionId() {
        return merchantTransactionId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MERCHANT_TRANSACTION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMerchantTransactionId_JsonNullable() {
    return merchantTransactionId;
  }
  
  @JsonProperty(JSON_PROPERTY_MERCHANT_TRANSACTION_ID)
  public void setMerchantTransactionId_JsonNullable(JsonNullable<String> merchantTransactionId) {
    this.merchantTransactionId = merchantTransactionId;
  }

  public void setMerchantTransactionId(@javax.annotation.Nullable String merchantTransactionId) {
    this.merchantTransactionId = JsonNullable.<String>of(merchantTransactionId);
  }


  public TransactionListItem merchantAccountReferenceId(@javax.annotation.Nullable String merchantAccountReferenceId) {
    this.merchantAccountReferenceId = JsonNullable.<String>of(merchantAccountReferenceId);
    return this;
  }

  /**
   * Merchant account reference identifier
   * @return merchantAccountReferenceId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getMerchantAccountReferenceId() {
        return merchantAccountReferenceId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMerchantAccountReferenceId_JsonNullable() {
    return merchantAccountReferenceId;
  }
  
  @JsonProperty(JSON_PROPERTY_MERCHANT_ACCOUNT_REFERENCE_ID)
  public void setMerchantAccountReferenceId_JsonNullable(JsonNullable<String> merchantAccountReferenceId) {
    this.merchantAccountReferenceId = merchantAccountReferenceId;
  }

  public void setMerchantAccountReferenceId(@javax.annotation.Nullable String merchantAccountReferenceId) {
    this.merchantAccountReferenceId = JsonNullable.<String>of(merchantAccountReferenceId);
  }


  public TransactionListItem customerId(@javax.annotation.Nullable String customerId) {
    this.customerId = JsonNullable.<String>of(customerId);
    return this;
  }

  /**
   * Customer identifier associated with the transaction
   * @return customerId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCustomerId() {
        return customerId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCustomerId_JsonNullable() {
    return customerId;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  public void setCustomerId_JsonNullable(JsonNullable<String> customerId) {
    this.customerId = customerId;
  }

  public void setCustomerId(@javax.annotation.Nullable String customerId) {
    this.customerId = JsonNullable.<String>of(customerId);
  }


  public TransactionListItem orderId(@javax.annotation.Nullable String orderId) {
    this.orderId = JsonNullable.<String>of(orderId);
    return this;
  }

  /**
   * Order identifier from the merchant system
   * @return orderId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getOrderId() {
        return orderId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ORDER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOrderId_JsonNullable() {
    return orderId;
  }
  
  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  public void setOrderId_JsonNullable(JsonNullable<String> orderId) {
    this.orderId = orderId;
  }

  public void setOrderId(@javax.annotation.Nullable String orderId) {
    this.orderId = JsonNullable.<String>of(orderId);
  }


  public TransactionListItem statementDescriptor(@javax.annotation.Nullable String statementDescriptor) {
    this.statementDescriptor = JsonNullable.<String>of(statementDescriptor);
    return this;
  }

  /**
   * Merchant-supplied text intended for the customer&#39;s card or bank statement, echoed back bounded to 255 characters. Adapted per gateway (length/charset) at submission and never blocks the charge.
   * @return statementDescriptor
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getStatementDescriptor() {
        return statementDescriptor.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STATEMENT_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getStatementDescriptor_JsonNullable() {
    return statementDescriptor;
  }
  
  @JsonProperty(JSON_PROPERTY_STATEMENT_DESCRIPTOR)
  public void setStatementDescriptor_JsonNullable(JsonNullable<String> statementDescriptor) {
    this.statementDescriptor = statementDescriptor;
  }

  public void setStatementDescriptor(@javax.annotation.Nullable String statementDescriptor) {
    this.statementDescriptor = JsonNullable.<String>of(statementDescriptor);
  }


  public TransactionListItem paymentMethodId(@javax.annotation.Nullable String paymentMethodId) {
    this.paymentMethodId = JsonNullable.<String>of(paymentMethodId);
    return this;
  }

  /**
   * Payment method identifier used for the transaction
   * @return paymentMethodId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPaymentMethodId() {
        return paymentMethodId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPaymentMethodId_JsonNullable() {
    return paymentMethodId;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_ID)
  public void setPaymentMethodId_JsonNullable(JsonNullable<String> paymentMethodId) {
    this.paymentMethodId = paymentMethodId;
  }

  public void setPaymentMethodId(@javax.annotation.Nullable String paymentMethodId) {
    this.paymentMethodId = JsonNullable.<String>of(paymentMethodId);
  }


  public TransactionListItem paymentMethodStorageState(@javax.annotation.Nullable String paymentMethodStorageState) {
    this.paymentMethodStorageState = JsonNullable.<String>of(paymentMethodStorageState);
    return this;
  }

  /**
   * Storage state of the payment method
   * @return paymentMethodStorageState
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPaymentMethodStorageState() {
        return paymentMethodStorageState.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD_STORAGE_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPaymentMethodStorageState_JsonNullable() {
    return paymentMethodStorageState;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_STORAGE_STATE)
  public void setPaymentMethodStorageState_JsonNullable(JsonNullable<String> paymentMethodStorageState) {
    this.paymentMethodStorageState = paymentMethodStorageState;
  }

  public void setPaymentMethodStorageState(@javax.annotation.Nullable String paymentMethodStorageState) {
    this.paymentMethodStorageState = JsonNullable.<String>of(paymentMethodStorageState);
  }


  public TransactionListItem paymentMethodType(@javax.annotation.Nullable String paymentMethodType) {
    this.paymentMethodType = JsonNullable.<String>of(paymentMethodType);
    return this;
  }

  /**
   * Type of payment method used
   * @return paymentMethodType
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPaymentMethodType() {
        return paymentMethodType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPaymentMethodType_JsonNullable() {
    return paymentMethodType;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_TYPE)
  public void setPaymentMethodType_JsonNullable(JsonNullable<String> paymentMethodType) {
    this.paymentMethodType = paymentMethodType;
  }

  public void setPaymentMethodType(@javax.annotation.Nullable String paymentMethodType) {
    this.paymentMethodType = JsonNullable.<String>of(paymentMethodType);
  }


  public TransactionListItem paymentMethodMerchantAccountReferenceId(@javax.annotation.Nullable String paymentMethodMerchantAccountReferenceId) {
    this.paymentMethodMerchantAccountReferenceId = JsonNullable.<String>of(paymentMethodMerchantAccountReferenceId);
    return this;
  }

  /**
   * Merchant account reference ID associated with the payment method
   * @return paymentMethodMerchantAccountReferenceId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPaymentMethodMerchantAccountReferenceId() {
        return paymentMethodMerchantAccountReferenceId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD_MERCHANT_ACCOUNT_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPaymentMethodMerchantAccountReferenceId_JsonNullable() {
    return paymentMethodMerchantAccountReferenceId;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_MERCHANT_ACCOUNT_REFERENCE_ID)
  public void setPaymentMethodMerchantAccountReferenceId_JsonNullable(JsonNullable<String> paymentMethodMerchantAccountReferenceId) {
    this.paymentMethodMerchantAccountReferenceId = paymentMethodMerchantAccountReferenceId;
  }

  public void setPaymentMethodMerchantAccountReferenceId(@javax.annotation.Nullable String paymentMethodMerchantAccountReferenceId) {
    this.paymentMethodMerchantAccountReferenceId = JsonNullable.<String>of(paymentMethodMerchantAccountReferenceId);
  }


  public TransactionListItem errorCode(@javax.annotation.Nullable String errorCode) {
    this.errorCode = JsonNullable.<String>of(errorCode);
    return this;
  }

  /**
   * Error code from the gateway response
   * @return errorCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getErrorCode() {
        return errorCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ERROR_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getErrorCode_JsonNullable() {
    return errorCode;
  }
  
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  public void setErrorCode_JsonNullable(JsonNullable<String> errorCode) {
    this.errorCode = errorCode;
  }

  public void setErrorCode(@javax.annotation.Nullable String errorCode) {
    this.errorCode = JsonNullable.<String>of(errorCode);
  }


  public TransactionListItem errorDetail(@javax.annotation.Nullable String errorDetail) {
    this.errorDetail = JsonNullable.<String>of(errorDetail);
    return this;
  }

  /**
   * Detailed error message from the gateway response
   * @return errorDetail
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getErrorDetail() {
        return errorDetail.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ERROR_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getErrorDetail_JsonNullable() {
    return errorDetail;
  }
  
  @JsonProperty(JSON_PROPERTY_ERROR_DETAIL)
  public void setErrorDetail_JsonNullable(JsonNullable<String> errorDetail) {
    this.errorDetail = errorDetail;
  }

  public void setErrorDetail(@javax.annotation.Nullable String errorDetail) {
    this.errorDetail = JsonNullable.<String>of(errorDetail);
  }


  public TransactionListItem avsCode(@javax.annotation.Nullable String avsCode) {
    this.avsCode = JsonNullable.<String>of(avsCode);
    return this;
  }

  /**
   * Address Verification System result code from the gateway
   * @return avsCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getAvsCode() {
        return avsCode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AVS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvsCode_JsonNullable() {
    return avsCode;
  }
  
  @JsonProperty(JSON_PROPERTY_AVS_CODE)
  public void setAvsCode_JsonNullable(JsonNullable<String> avsCode) {
    this.avsCode = avsCode;
  }

  public void setAvsCode(@javax.annotation.Nullable String avsCode) {
    this.avsCode = JsonNullable.<String>of(avsCode);
  }


  public TransactionListItem gateway(@javax.annotation.Nullable TransactionGateway gateway) {
    this.gateway = JsonNullable.<TransactionGateway>of(gateway);
    return this;
  }

  /**
   * Get gateway
   * @return gateway
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public TransactionGateway getGateway() {
        return gateway.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GATEWAY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<TransactionGateway> getGateway_JsonNullable() {
    return gateway;
  }
  
  @JsonProperty(JSON_PROPERTY_GATEWAY)
  public void setGateway_JsonNullable(JsonNullable<TransactionGateway> gateway) {
    this.gateway = gateway;
  }

  public void setGateway(@javax.annotation.Nullable TransactionGateway gateway) {
    this.gateway = JsonNullable.<TransactionGateway>of(gateway);
  }


  public TransactionListItem paymentMethod(@javax.annotation.Nullable PaymentMethodResponse paymentMethod) {
    this.paymentMethod = JsonNullable.<PaymentMethodResponse>of(paymentMethod);
    return this;
  }

  /**
   * Get paymentMethod
   * @return paymentMethod
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public PaymentMethodResponse getPaymentMethod() {
        return paymentMethod.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<PaymentMethodResponse> getPaymentMethod_JsonNullable() {
    return paymentMethod;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD)
  public void setPaymentMethod_JsonNullable(JsonNullable<PaymentMethodResponse> paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public void setPaymentMethod(@javax.annotation.Nullable PaymentMethodResponse paymentMethod) {
    this.paymentMethod = JsonNullable.<PaymentMethodResponse>of(paymentMethod);
  }


  /**
   * Return true if this TransactionListItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionListItem transactionListItem = (TransactionListItem) o;
    return equalsNullable(this.transactionId, transactionListItem.transactionId) &&
        Objects.equals(this.transactionDate, transactionListItem.transactionDate) &&
        Objects.equals(this.transactionStatus, transactionListItem.transactionStatus) &&
        equalsNullable(this.responseCode, transactionListItem.responseCode) &&
        equalsNullable(this.message, transactionListItem.message) &&
        equalsNullable(this.transactionType, transactionListItem.transactionType) &&
        equalsNullable(this.retryDate, transactionListItem.retryDate) &&
        equalsNullable(this.amount, transactionListItem.amount) &&
        equalsNullable(this.initialMerchantTransactionId, transactionListItem.initialMerchantTransactionId) &&
        equalsNullable(this.storageState, transactionListItem.storageState) &&
        equalsNullable(this.completionStatus, transactionListItem.completionStatus) &&
        equalsNullable(this.gatewaySpecificResponseFields, transactionListItem.gatewaySpecificResponseFields) &&
        equalsNullable(this.gatewaySpecificFields, transactionListItem.gatewaySpecificFields) &&
        equalsNullable(this.acquirerAuthCode, transactionListItem.acquirerAuthCode) &&
        equalsNullable(this.gatewayTransactionId, transactionListItem.gatewayTransactionId) &&
        equalsNullable(this.gatewayPaymentMethodId, transactionListItem.gatewayPaymentMethodId) &&
        equalsNullable(this.engagedRecoveryState, transactionListItem.engagedRecoveryState) &&
        equalsNullable(this.currencyCode, transactionListItem.currencyCode) &&
        equalsNullable(this.merchantTransactionId, transactionListItem.merchantTransactionId) &&
        equalsNullable(this.merchantAccountReferenceId, transactionListItem.merchantAccountReferenceId) &&
        equalsNullable(this.customerId, transactionListItem.customerId) &&
        equalsNullable(this.orderId, transactionListItem.orderId) &&
        equalsNullable(this.statementDescriptor, transactionListItem.statementDescriptor) &&
        equalsNullable(this.paymentMethodId, transactionListItem.paymentMethodId) &&
        equalsNullable(this.paymentMethodStorageState, transactionListItem.paymentMethodStorageState) &&
        equalsNullable(this.paymentMethodType, transactionListItem.paymentMethodType) &&
        equalsNullable(this.paymentMethodMerchantAccountReferenceId, transactionListItem.paymentMethodMerchantAccountReferenceId) &&
        equalsNullable(this.errorCode, transactionListItem.errorCode) &&
        equalsNullable(this.errorDetail, transactionListItem.errorDetail) &&
        equalsNullable(this.avsCode, transactionListItem.avsCode) &&
        equalsNullable(this.gateway, transactionListItem.gateway) &&
        equalsNullable(this.paymentMethod, transactionListItem.paymentMethod);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(transactionId), transactionDate, transactionStatus, hashCodeNullable(responseCode), hashCodeNullable(message), hashCodeNullable(transactionType), hashCodeNullable(retryDate), hashCodeNullable(amount), hashCodeNullable(initialMerchantTransactionId), hashCodeNullable(storageState), hashCodeNullable(completionStatus), hashCodeNullable(gatewaySpecificResponseFields), hashCodeNullable(gatewaySpecificFields), hashCodeNullable(acquirerAuthCode), hashCodeNullable(gatewayTransactionId), hashCodeNullable(gatewayPaymentMethodId), hashCodeNullable(engagedRecoveryState), hashCodeNullable(currencyCode), hashCodeNullable(merchantTransactionId), hashCodeNullable(merchantAccountReferenceId), hashCodeNullable(customerId), hashCodeNullable(orderId), hashCodeNullable(statementDescriptor), hashCodeNullable(paymentMethodId), hashCodeNullable(paymentMethodStorageState), hashCodeNullable(paymentMethodType), hashCodeNullable(paymentMethodMerchantAccountReferenceId), hashCodeNullable(errorCode), hashCodeNullable(errorDetail), hashCodeNullable(avsCode), hashCodeNullable(gateway), hashCodeNullable(paymentMethod));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionListItem {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    retryDate: ").append(toIndentedString(retryDate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    initialMerchantTransactionId: ").append(toIndentedString(initialMerchantTransactionId)).append("\n");
    sb.append("    storageState: ").append(toIndentedString(storageState)).append("\n");
    sb.append("    completionStatus: ").append(toIndentedString(completionStatus)).append("\n");
    sb.append("    gatewaySpecificResponseFields: ").append(toIndentedString(gatewaySpecificResponseFields)).append("\n");
    sb.append("    gatewaySpecificFields: ").append(toIndentedString(gatewaySpecificFields)).append("\n");
    sb.append("    acquirerAuthCode: ").append(toIndentedString(acquirerAuthCode)).append("\n");
    sb.append("    gatewayTransactionId: ").append(toIndentedString(gatewayTransactionId)).append("\n");
    sb.append("    gatewayPaymentMethodId: ").append(toIndentedString(gatewayPaymentMethodId)).append("\n");
    sb.append("    engagedRecoveryState: ").append(toIndentedString(engagedRecoveryState)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    merchantTransactionId: ").append(toIndentedString(merchantTransactionId)).append("\n");
    sb.append("    merchantAccountReferenceId: ").append(toIndentedString(merchantAccountReferenceId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    statementDescriptor: ").append(toIndentedString(statementDescriptor)).append("\n");
    sb.append("    paymentMethodId: ").append(toIndentedString(paymentMethodId)).append("\n");
    sb.append("    paymentMethodStorageState: ").append(toIndentedString(paymentMethodStorageState)).append("\n");
    sb.append("    paymentMethodType: ").append(toIndentedString(paymentMethodType)).append("\n");
    sb.append("    paymentMethodMerchantAccountReferenceId: ").append(toIndentedString(paymentMethodMerchantAccountReferenceId)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDetail: ").append(toIndentedString(errorDetail)).append("\n");
    sb.append("    avsCode: ").append(toIndentedString(avsCode)).append("\n");
    sb.append("    gateway: ").append(toIndentedString(gateway)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transactionId` to the URL query string
    if (getTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionId()))));
    }

    // add `transactionDate` to the URL query string
    if (getTransactionDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactionDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionDate()))));
    }

    // add `transactionStatus` to the URL query string
    if (getTransactionStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactionStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionStatus()))));
    }

    // add `responseCode` to the URL query string
    if (getResponseCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresponseCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseCode()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `transactionType` to the URL query string
    if (getTransactionType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactionType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionType()))));
    }

    // add `retryDate` to the URL query string
    if (getRetryDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretryDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetryDate()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `initialMerchantTransactionId` to the URL query string
    if (getInitialMerchantTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinitialMerchantTransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInitialMerchantTransactionId()))));
    }

    // add `storageState` to the URL query string
    if (getStorageState() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstorageState%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStorageState()))));
    }

    // add `completionStatus` to the URL query string
    if (getCompletionStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scompletionStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompletionStatus()))));
    }

    // add `gatewaySpecificResponseFields` to the URL query string
    if (getGatewaySpecificResponseFields() != null) {
      for (String _key : getGatewaySpecificResponseFields().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sgatewaySpecificResponseFields%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getGatewaySpecificResponseFields().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getGatewaySpecificResponseFields().get(_key)))));
      }
    }

    // add `gatewaySpecificFields` to the URL query string
    if (getGatewaySpecificFields() != null) {
      for (String _key : getGatewaySpecificFields().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sgatewaySpecificFields%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getGatewaySpecificFields().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getGatewaySpecificFields().get(_key)))));
      }
    }

    // add `acquirerAuthCode` to the URL query string
    if (getAcquirerAuthCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sacquirerAuthCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcquirerAuthCode()))));
    }

    // add `gatewayTransactionId` to the URL query string
    if (getGatewayTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgatewayTransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGatewayTransactionId()))));
    }

    // add `gatewayPaymentMethodId` to the URL query string
    if (getGatewayPaymentMethodId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgatewayPaymentMethodId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGatewayPaymentMethodId()))));
    }

    // add `engagedRecoveryState` to the URL query string
    if (getEngagedRecoveryState() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sengagedRecoveryState%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEngagedRecoveryState()))));
    }

    // add `currencyCode` to the URL query string
    if (getCurrencyCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrencyCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrencyCode()))));
    }

    // add `merchantTransactionId` to the URL query string
    if (getMerchantTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchantTransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantTransactionId()))));
    }

    // add `merchantAccountReferenceId` to the URL query string
    if (getMerchantAccountReferenceId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchantAccountReferenceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantAccountReferenceId()))));
    }

    // add `customerId` to the URL query string
    if (getCustomerId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomerId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomerId()))));
    }

    // add `orderId` to the URL query string
    if (getOrderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sorderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrderId()))));
    }

    // add `statementDescriptor` to the URL query string
    if (getStatementDescriptor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatementDescriptor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatementDescriptor()))));
    }

    // add `paymentMethodId` to the URL query string
    if (getPaymentMethodId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentMethodId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentMethodId()))));
    }

    // add `paymentMethodStorageState` to the URL query string
    if (getPaymentMethodStorageState() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentMethodStorageState%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentMethodStorageState()))));
    }

    // add `paymentMethodType` to the URL query string
    if (getPaymentMethodType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentMethodType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentMethodType()))));
    }

    // add `paymentMethodMerchantAccountReferenceId` to the URL query string
    if (getPaymentMethodMerchantAccountReferenceId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentMethodMerchantAccountReferenceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentMethodMerchantAccountReferenceId()))));
    }

    // add `errorCode` to the URL query string
    if (getErrorCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorCode()))));
    }

    // add `errorDetail` to the URL query string
    if (getErrorDetail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorDetail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorDetail()))));
    }

    // add `avsCode` to the URL query string
    if (getAvsCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%savsCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAvsCode()))));
    }

    // add `gateway` to the URL query string
    if (getGateway() != null) {
      joiner.add(getGateway().toUrlQueryString(prefix + "gateway" + suffix));
    }

    // add `paymentMethod` to the URL query string
    if (getPaymentMethod() != null) {
      joiner.add(getPaymentMethod().toUrlQueryString(prefix + "paymentMethod" + suffix));
    }

    return joiner.toString();
  }
}

