/*
 * Revaly
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */


package co.revaly.sdk.core.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import co.revaly.sdk.core.ApiClient;
/**
 * Gateway information associated with a transaction
 */
@JsonPropertyOrder({
  TransactionGateway.JSON_PROPERTY_TOKEN,
  TransactionGateway.JSON_PROPERTY_GATEWAY_TYPE,
  TransactionGateway.JSON_PROPERTY_NAME,
  TransactionGateway.JSON_PROPERTY_REFERENCE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TransactionGateway {
  public static final String JSON_PROPERTY_TOKEN = "token";
  private JsonNullable<String> token = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GATEWAY_TYPE = "gatewayType";
  private JsonNullable<String> gatewayType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_REFERENCE_ID = "referenceId";
  private JsonNullable<String> referenceId = JsonNullable.<String>undefined();

  public TransactionGateway() { 
  }

  public TransactionGateway token(@javax.annotation.Nullable String token) {
    this.token = JsonNullable.<String>of(token);
    return this;
  }

  /**
   * Gateway routing token identifier
   * @return token
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getToken() {
        return token.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getToken_JsonNullable() {
    return token;
  }
  
  @JsonProperty(JSON_PROPERTY_TOKEN)
  public void setToken_JsonNullable(JsonNullable<String> token) {
    this.token = token;
  }

  public void setToken(@javax.annotation.Nullable String token) {
    this.token = JsonNullable.<String>of(token);
  }


  public TransactionGateway gatewayType(@javax.annotation.Nullable String gatewayType) {
    this.gatewayType = JsonNullable.<String>of(gatewayType);
    return this;
  }

  /**
   * The type of payment gateway used
   * @return gatewayType
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGatewayType() {
        return gatewayType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GATEWAY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGatewayType_JsonNullable() {
    return gatewayType;
  }
  
  @JsonProperty(JSON_PROPERTY_GATEWAY_TYPE)
  public void setGatewayType_JsonNullable(JsonNullable<String> gatewayType) {
    this.gatewayType = gatewayType;
  }

  public void setGatewayType(@javax.annotation.Nullable String gatewayType) {
    this.gatewayType = JsonNullable.<String>of(gatewayType);
  }


  public TransactionGateway name(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Human-readable gateway name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public TransactionGateway referenceId(@javax.annotation.Nullable String referenceId) {
    this.referenceId = JsonNullable.<String>of(referenceId);
    return this;
  }

  /**
   * Merchant account reference identifier at the gateway
   * @return referenceId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getReferenceId() {
        return referenceId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REFERENCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReferenceId_JsonNullable() {
    return referenceId;
  }
  
  @JsonProperty(JSON_PROPERTY_REFERENCE_ID)
  public void setReferenceId_JsonNullable(JsonNullable<String> referenceId) {
    this.referenceId = referenceId;
  }

  public void setReferenceId(@javax.annotation.Nullable String referenceId) {
    this.referenceId = JsonNullable.<String>of(referenceId);
  }


  /**
   * Return true if this TransactionGateway object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionGateway transactionGateway = (TransactionGateway) o;
    return equalsNullable(this.token, transactionGateway.token) &&
        equalsNullable(this.gatewayType, transactionGateway.gatewayType) &&
        equalsNullable(this.name, transactionGateway.name) &&
        equalsNullable(this.referenceId, transactionGateway.referenceId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(token), hashCodeNullable(gatewayType), hashCodeNullable(name), hashCodeNullable(referenceId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionGateway {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    gatewayType: ").append(toIndentedString(gatewayType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `token` to the URL query string
    if (getToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToken()))));
    }

    // add `gatewayType` to the URL query string
    if (getGatewayType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgatewayType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGatewayType()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `referenceId` to the URL query string
    if (getReferenceId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreferenceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReferenceId()))));
    }

    return joiner.toString();
  }
}

