/*
Revaly

Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 

API version: 2.2.1

RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
(ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotifyRequest{}

// NotifyRequest Notification request to inform Revaly of specific business events
type NotifyRequest struct {
	// Type of business event being reported. The event type determines how Revaly processes the notification.  - **recordPayment**: Record a payment transaction - **recordRefund**: Record a refund transaction - **recordChargeback**: Record a chargeback on a transaction - **endOutreach**: End an outreach campaign for a customer - **updateCustomerData**: Update customer information and contact details 
	EventType string `json:"eventType"`
	Data *NotifyData `json:"data,omitempty"`
}

type _NotifyRequest NotifyRequest

// NewNotifyRequest instantiates a new NotifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotifyRequest(eventType string) *NotifyRequest {
	this := NotifyRequest{}
	this.EventType = eventType
	return &this
}

// NewNotifyRequestWithDefaults instantiates a new NotifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotifyRequestWithDefaults() *NotifyRequest {
	this := NotifyRequest{}
	return &this
}

// GetEventType returns the EventType field value
func (o *NotifyRequest) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *NotifyRequest) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *NotifyRequest) SetEventType(v string) {
	o.EventType = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NotifyRequest) GetData() NotifyData {
	if o == nil || IsNil(o.Data) {
		var ret NotifyData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotifyRequest) GetDataOk() (*NotifyData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NotifyRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given NotifyData and assigns it to the Data field.
func (o *NotifyRequest) SetData(v NotifyData) {
	o.Data = &v
}

func (o NotifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["eventType"] = o.EventType
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *NotifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotifyRequest := _NotifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotifyRequest)

	if err != nil {
		return err
	}

	*o = NotifyRequest(varNotifyRequest)

	return err
}

type NullableNotifyRequest struct {
	value *NotifyRequest
	isSet bool
}

func (v NullableNotifyRequest) Get() *NotifyRequest {
	return v.value
}

func (v *NullableNotifyRequest) Set(val *NotifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNotifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNotifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotifyRequest(val *NotifyRequest) *NullableNotifyRequest {
	return &NullableNotifyRequest{value: val, isSet: true}
}

func (v NullableNotifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


