/*
Revaly

Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 

API version: 2.6.0

RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
(ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// RAP fork imports (fork note in UnmarshalJSON below; record: pipeline/go/config.yaml).
import (
	"reflect"
	"strings"
)

// GetTransactionById200Response - struct for GetTransactionById200Response
type GetTransactionById200Response struct {
	TransactionGroupResponse *TransactionGroupResponse
	TransactionResponse *TransactionResponse
}

// TransactionGroupResponseAsGetTransactionById200Response is a convenience function that returns TransactionGroupResponse wrapped in GetTransactionById200Response
func TransactionGroupResponseAsGetTransactionById200Response(v *TransactionGroupResponse) GetTransactionById200Response {
	return GetTransactionById200Response{
		TransactionGroupResponse: v,
	}
}

// TransactionResponseAsGetTransactionById200Response is a convenience function that returns TransactionResponse wrapped in GetTransactionById200Response
func TransactionResponseAsGetTransactionById200Response(v *TransactionResponse) GetTransactionById200Response {
	return GetTransactionById200Response{
		TransactionResponse: v,
	}
}


// Unmarshal JSON data into any of the pointers in the struct
//
// RAP fork (ADR-SDK-023; recorded in pipeline/go/config.yaml) — anyOf variant
// of the model_oneof fork (2026-08-27, spec v2.4.0 re-pin). The stock anyOf leg
// lenient-decodes branches first-match-wins, which is names-correct only until
// the server evolves: branch models with required members strict-reject unknown
// fields (their generated UnmarshalJSON uses DisallowUnknownFields), so one
// additive platform field re-binds a pending body as a terminal transaction and
// hard-fails a group envelope. Discrimination here is by field NAMES only,
// never values (failover-contract §2 prohibits value/content heuristics):
//
//   Pass 1 (strict): DisallowUnknownFields decode per branch in declaration
//   order (the spec orders anyOf branches most-specific first); empty or
//   absent binds discarded; the FIRST strict match wins (anyOf semantics).
//
//   Pass 2 (lenient, only when pass 1 matched nothing — additive platform
//   fields from minor releases land here): per branch, all required top-level
//   keys (json tags without omitempty) must be present, then the branch with
//   the uniquely highest count of recognized top-level keys wins and is bound
//   through a methodless alias of the branch type, so plain field-based
//   decoding ignores additive fields at every nesting level. No unique winner
//   keeps the stock error.
func (dst *GetTransactionById200Response) UnmarshalJSON(data []byte) error {
	var err error
	// Pass 1 — strict: unknown top-level fields disqualify a branch; the models'
	// own UnmarshalJSON methods additionally enforce their required properties.
	// Branches are tried in declaration order; the first strict match binds.
	// try to unmarshal data into TransactionGroupResponse
	err = newStrictDecoder(data).Decode(&dst.TransactionGroupResponse)
	if err == nil {
		jsonTransactionGroupResponse, _ := json.Marshal(dst.TransactionGroupResponse)
		if string(jsonTransactionGroupResponse) == "{}" || string(jsonTransactionGroupResponse) == "null" { // empty or absent struct
			dst.TransactionGroupResponse = nil
		} else {
			return nil // data stored in dst.TransactionGroupResponse, first strict match wins
		}
	} else {
		dst.TransactionGroupResponse = nil
	}

	// try to unmarshal data into TransactionResponse
	err = newStrictDecoder(data).Decode(&dst.TransactionResponse)
	if err == nil {
		jsonTransactionResponse, _ := json.Marshal(dst.TransactionResponse)
		if string(jsonTransactionResponse) == "{}" || string(jsonTransactionResponse) == "null" { // empty or absent struct
			dst.TransactionResponse = nil
		} else {
			return nil // data stored in dst.TransactionResponse, first strict match wins
		}
	} else {
		dst.TransactionResponse = nil
	}

	// Pass 2 — lenient, names-only coverage (zero strict matches).
	var payload map[string]json.RawMessage
	if err = json.Unmarshal(data, &payload); err != nil || payload == nil {
		return fmt.Errorf("data failed to match schemas in anyOf(GetTransactionById200Response)")
	}
	// knownAndRequiredKeys reflects a branch struct's exported top-level json tags;
	// required mirrors the generated required-property sets (tags without omitempty).
	knownAndRequiredKeys := func(t reflect.Type) (map[string]bool, []string) {
		known := make(map[string]bool, t.NumField())
		var required []string
		for i := 0; i < t.NumField(); i++ {
			tag := t.Field(i).Tag.Get("json")
			if tag == "" || tag == "-" {
				continue
			}
			parts := strings.Split(tag, ",")
			if parts[0] == "" {
				continue
			}
			known[parts[0]] = true
			optional := false
			for _, p := range parts[1:] {
				if p == "omitempty" {
					optional = true
				}
			}
			if !optional {
				required = append(required, parts[0])
			}
		}
		return known, required
	}
	// coverageOf: a branch is a candidate only if every required key is present;
	// its coverage is the number of recognized top-level payload keys (≥ 1).
	coverageOf := func(t reflect.Type) (int, bool) {
		known, required := knownAndRequiredKeys(t)
		for _, r := range required {
			if _, present := payload[r]; !present {
				return 0, false
			}
		}
		cov := 0
		for k := range payload {
			if known[k] {
				cov++
			}
		}
		return cov, cov > 0
	}
	branchTypes := []reflect.Type{
		reflect.TypeOf(TransactionGroupResponse{}),
		reflect.TypeOf(TransactionResponse{}),
	}
	// bind decodes the FULL payload through a methodless alias of the branch
	// type: plain field-based decoding ignores unknown keys at every nesting
	// level, so additive fields — top-level or nested — cannot disqualify the
	// branch the coverage pass chose. Required-member presence was already
	// enforced above, by name.
	type plainTransactionGroupResponse TransactionGroupResponse
	type plainTransactionResponse TransactionResponse
	branchBinders := []func([]byte) error{
		func(raw []byte) error {
			var v plainTransactionGroupResponse
			if bindErr := json.Unmarshal(raw, &v); bindErr != nil {
				return bindErr
			}
			dst.TransactionGroupResponse = (*TransactionGroupResponse)(&v)
			return nil
		},
		func(raw []byte) error {
			var v plainTransactionResponse
			if bindErr := json.Unmarshal(raw, &v); bindErr != nil {
				return bindErr
			}
			dst.TransactionResponse = (*TransactionResponse)(&v)
			return nil
		},
	}
	bestIdx, bestCov, bestCount := -1, 0, 0
	for i, t := range branchTypes {
		cov, candidate := coverageOf(t)
		if !candidate {
			continue
		}
		if cov > bestCov {
			bestIdx, bestCov, bestCount = i, cov, 1
		} else if cov == bestCov {
			bestCount++
		}
	}
	if bestIdx >= 0 && bestCount == 1 {
		if branchBinders[bestIdx](data) == nil {
			return nil
		}
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTransactionById200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTransactionById200Response) MarshalJSON() ([]byte, error) {
	if src.TransactionGroupResponse != nil {
		return json.Marshal(&src.TransactionGroupResponse)
	}

	if src.TransactionResponse != nil {
		return json.Marshal(&src.TransactionResponse)
	}

	return nil, nil // no data in anyOf schemas
}

// Get the actual instance
func (obj *GetTransactionById200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TransactionGroupResponse != nil {
		return obj.TransactionGroupResponse
	}

	if obj.TransactionResponse != nil {
		return obj.TransactionResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetTransactionById200Response) GetActualInstanceValue() (interface{}) {
	if obj.TransactionGroupResponse != nil {
		return *obj.TransactionGroupResponse
	}

	if obj.TransactionResponse != nil {
		return *obj.TransactionResponse
	}

	// all schemas are nil
	return nil
}

type NullableGetTransactionById200Response struct {
	value *GetTransactionById200Response
	isSet bool
}

func (v NullableGetTransactionById200Response) Get() *GetTransactionById200Response {
	return v.value
}

func (v *NullableGetTransactionById200Response) Set(val *GetTransactionById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTransactionById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTransactionById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTransactionById200Response(val *GetTransactionById200Response) *NullableGetTransactionById200Response {
	return &NullableGetTransactionById200Response{value: val, isSet: true}
}

func (v NullableGetTransactionById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTransactionById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


