/*
Revaly

Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 

API version: 2.3.0

RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
(ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PendingTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PendingTransactionResponse{}

// PendingTransactionResponse Pending payment intent. Returned by the merchant-transaction lookup when the platform has accepted a payment with this merchantTransactionId (the intent was durably recorded before gateway dispatch) but no transaction record is visible yet. Poll the same lookup again: it resolves to the full TransactionResponse once the transaction becomes visible. This shape is deliberately distinct from TransactionResponse — use the required `state` field as the discriminator.
type PendingTransactionResponse struct {
	// Always `pending` — discriminates this shape from a completed transaction.
	State string `json:"state"`
	// Merchant-provided transaction identifier the intent was recorded under
	MerchantTransactionId string `json:"merchantTransactionId"`
	// Operation the intent was recorded for — \"Charge\" or \"Authorize\" (same vocabulary as TransactionResponse.transactionType).
	TransactionType NullableString `json:"transactionType,omitempty"`
	// When the platform recorded the payment intent (ISO 8601)
	ReceivedAt NullableTime `json:"receivedAt,omitempty"`
}

type _PendingTransactionResponse PendingTransactionResponse

// NewPendingTransactionResponse instantiates a new PendingTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPendingTransactionResponse(state string, merchantTransactionId string) *PendingTransactionResponse {
	this := PendingTransactionResponse{}
	this.State = state
	this.MerchantTransactionId = merchantTransactionId
	return &this
}

// NewPendingTransactionResponseWithDefaults instantiates a new PendingTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPendingTransactionResponseWithDefaults() *PendingTransactionResponse {
	this := PendingTransactionResponse{}
	return &this
}

// GetState returns the State field value
func (o *PendingTransactionResponse) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *PendingTransactionResponse) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *PendingTransactionResponse) SetState(v string) {
	o.State = v
}

// GetMerchantTransactionId returns the MerchantTransactionId field value
func (o *PendingTransactionResponse) GetMerchantTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantTransactionId
}

// GetMerchantTransactionIdOk returns a tuple with the MerchantTransactionId field value
// and a boolean to check if the value has been set.
func (o *PendingTransactionResponse) GetMerchantTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantTransactionId, true
}

// SetMerchantTransactionId sets field value
func (o *PendingTransactionResponse) SetMerchantTransactionId(v string) {
	o.MerchantTransactionId = v
}

// GetTransactionType returns the TransactionType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PendingTransactionResponse) GetTransactionType() string {
	if o == nil || IsNil(o.TransactionType.Get()) {
		var ret string
		return ret
	}
	return *o.TransactionType.Get()
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PendingTransactionResponse) GetTransactionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TransactionType.Get(), o.TransactionType.IsSet()
}

// HasTransactionType returns a boolean if a field has been set.
func (o *PendingTransactionResponse) HasTransactionType() bool {
	if o != nil && o.TransactionType.IsSet() {
		return true
	}

	return false
}

// SetTransactionType gets a reference to the given NullableString and assigns it to the TransactionType field.
func (o *PendingTransactionResponse) SetTransactionType(v string) {
	o.TransactionType.Set(&v)
}
// SetTransactionTypeNil sets the value for TransactionType to be an explicit nil
func (o *PendingTransactionResponse) SetTransactionTypeNil() {
	o.TransactionType.Set(nil)
}

// UnsetTransactionType ensures that no value is present for TransactionType, not even an explicit nil
func (o *PendingTransactionResponse) UnsetTransactionType() {
	o.TransactionType.Unset()
}

// GetReceivedAt returns the ReceivedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PendingTransactionResponse) GetReceivedAt() time.Time {
	if o == nil || IsNil(o.ReceivedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ReceivedAt.Get()
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PendingTransactionResponse) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceivedAt.Get(), o.ReceivedAt.IsSet()
}

// HasReceivedAt returns a boolean if a field has been set.
func (o *PendingTransactionResponse) HasReceivedAt() bool {
	if o != nil && o.ReceivedAt.IsSet() {
		return true
	}

	return false
}

// SetReceivedAt gets a reference to the given NullableTime and assigns it to the ReceivedAt field.
func (o *PendingTransactionResponse) SetReceivedAt(v time.Time) {
	o.ReceivedAt.Set(&v)
}
// SetReceivedAtNil sets the value for ReceivedAt to be an explicit nil
func (o *PendingTransactionResponse) SetReceivedAtNil() {
	o.ReceivedAt.Set(nil)
}

// UnsetReceivedAt ensures that no value is present for ReceivedAt, not even an explicit nil
func (o *PendingTransactionResponse) UnsetReceivedAt() {
	o.ReceivedAt.Unset()
}

func (o PendingTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PendingTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["merchantTransactionId"] = o.MerchantTransactionId
	if o.TransactionType.IsSet() {
		toSerialize["transactionType"] = o.TransactionType.Get()
	}
	if o.ReceivedAt.IsSet() {
		toSerialize["receivedAt"] = o.ReceivedAt.Get()
	}
	return toSerialize, nil
}

func (o *PendingTransactionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"merchantTransactionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPendingTransactionResponse := _PendingTransactionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPendingTransactionResponse)

	if err != nil {
		return err
	}

	*o = PendingTransactionResponse(varPendingTransactionResponse)

	return err
}

type NullablePendingTransactionResponse struct {
	value *PendingTransactionResponse
	isSet bool
}

func (v NullablePendingTransactionResponse) Get() *PendingTransactionResponse {
	return v.value
}

func (v *NullablePendingTransactionResponse) Set(val *PendingTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePendingTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePendingTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePendingTransactionResponse(val *PendingTransactionResponse) *NullablePendingTransactionResponse {
	return &NullablePendingTransactionResponse{value: val, isSet: true}
}

func (v NullablePendingTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePendingTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


