/*
 * Revaly
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header. 
 *
 * The version of the OpenAPI document: 2.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

package co.revaly.sdk.core.api;

import co.revaly.sdk.core.ApiClient;
import co.revaly.sdk.core.ApiException;
import co.revaly.sdk.core.ApiResponse;
import co.revaly.sdk.core.Configuration;
import co.revaly.sdk.core.Pair;

import co.revaly.sdk.core.model.CreatePaymentMethodRequest;
import co.revaly.sdk.core.model.ErrorResponse;
import co.revaly.sdk.core.model.PaymentMethodRecacheRequest;
import co.revaly.sdk.core.model.PaymentMethodResponse;
import co.revaly.sdk.core.model.PaymentMethodWriteResponse;
import co.revaly.sdk.core.model.UpdatePaymentMethodRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class PaymentMethodsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PaymentMethodsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PaymentMethodsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a payment method
   * Create and store a payment method in the vault. Supports both credit card details  and gatewayPaymentMethodIds from supported payment processors.  **Payment Method Types:** - **creditCard**: Credit card details that will be tokenized and stored - **gatewayPaymentMethodId**: Pre-existing gatewayPaymentMethodId from a supported payment gateway 
   * @param createPaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse createPaymentMethod(@javax.annotation.Nonnull CreatePaymentMethodRequest createPaymentMethodRequest, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return createPaymentMethod(createPaymentMethodRequest, xApiVersion, null);
  }

  /**
   * Create a payment method
   * Create and store a payment method in the vault. Supports both credit card details  and gatewayPaymentMethodIds from supported payment processors.  **Payment Method Types:** - **creditCard**: Credit card details that will be tokenized and stored - **gatewayPaymentMethodId**: Pre-existing gatewayPaymentMethodId from a supported payment gateway 
   * @param createPaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse createPaymentMethod(@javax.annotation.Nonnull CreatePaymentMethodRequest createPaymentMethodRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    ApiResponse<PaymentMethodWriteResponse> localVarResponse = createPaymentMethodWithHttpInfo(createPaymentMethodRequest, xApiVersion, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a payment method
   * Create and store a payment method in the vault. Supports both credit card details  and gatewayPaymentMethodIds from supported payment processors.  **Payment Method Types:** - **creditCard**: Credit card details that will be tokenized and stored - **gatewayPaymentMethodId**: Pre-existing gatewayPaymentMethodId from a supported payment gateway 
   * @param createPaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> createPaymentMethodWithHttpInfo(@javax.annotation.Nonnull CreatePaymentMethodRequest createPaymentMethodRequest, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return createPaymentMethodWithHttpInfo(createPaymentMethodRequest, xApiVersion, null);
  }

  /**
   * Create a payment method
   * Create and store a payment method in the vault. Supports both credit card details  and gatewayPaymentMethodIds from supported payment processors.  **Payment Method Types:** - **creditCard**: Credit card details that will be tokenized and stored - **gatewayPaymentMethodId**: Pre-existing gatewayPaymentMethodId from a supported payment gateway 
   * @param createPaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> createPaymentMethodWithHttpInfo(@javax.annotation.Nonnull CreatePaymentMethodRequest createPaymentMethodRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createPaymentMethodRequestBuilder(createPaymentMethodRequest, xApiVersion, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createPaymentMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PaymentMethodWriteResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PaymentMethodWriteResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PaymentMethodWriteResponse>() {});
        

        return new ApiResponse<PaymentMethodWriteResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createPaymentMethodRequestBuilder(@javax.annotation.Nonnull CreatePaymentMethodRequest createPaymentMethodRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createPaymentMethodRequest' is set
    if (createPaymentMethodRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createPaymentMethodRequest' when calling createPaymentMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payment-methods/create";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiVersion != null) {
      localVarRequestBuilder.header("X-Api-Version", xApiVersion.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createPaymentMethodRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get payment method details
   * Retrieve detailed information about a specific payment method.  Returns payment method data with sensitive information masked for security. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return PaymentMethodResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodResponse getPaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return getPaymentMethod(paymentMethodId, xApiVersion, null);
  }

  /**
   * Get payment method details
   * Retrieve detailed information about a specific payment method.  Returns payment method data with sensitive information masked for security. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return PaymentMethodResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodResponse getPaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    ApiResponse<PaymentMethodResponse> localVarResponse = getPaymentMethodWithHttpInfo(paymentMethodId, xApiVersion, headers);
    return localVarResponse.getData();
  }

  /**
   * Get payment method details
   * Retrieve detailed information about a specific payment method.  Returns payment method data with sensitive information masked for security. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return ApiResponse&lt;PaymentMethodResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodResponse> getPaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return getPaymentMethodWithHttpInfo(paymentMethodId, xApiVersion, null);
  }

  /**
   * Get payment method details
   * Retrieve detailed information about a specific payment method.  Returns payment method data with sensitive information masked for security. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PaymentMethodResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodResponse> getPaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPaymentMethodRequestBuilder(paymentMethodId, xApiVersion, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPaymentMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PaymentMethodResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PaymentMethodResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PaymentMethodResponse>() {});
        

        return new ApiResponse<PaymentMethodResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPaymentMethodRequestBuilder(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'paymentMethodId' is set
    if (paymentMethodId == null) {
      throw new ApiException(400, "Missing the required parameter 'paymentMethodId' when calling getPaymentMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payment-methods/show/{paymentMethodId}"
        .replace("{paymentMethodId}", ApiClient.urlEncode(paymentMethodId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiVersion != null) {
      localVarRequestBuilder.header("X-Api-Version", xApiVersion.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List payment methods
   * Retrieve a paginated list of stored payment methods.  Returns payment methods with sensitive information masked for security. Use pagination parameters to navigate through large result sets. 
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param count Number of payment methods to return (optional, default to 20)
   * @param order Sort order for results (optional, default to asc)
   * @param sincePaymentMethodId Return payment methods after this ID (for pagination) (optional)
   * @return List&lt;PaymentMethodResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PaymentMethodResponse> listPaymentMethods(@javax.annotation.Nullable String xApiVersion, @javax.annotation.Nullable Integer count, @javax.annotation.Nullable String order, @javax.annotation.Nullable String sincePaymentMethodId) throws ApiException {
    return listPaymentMethods(xApiVersion, count, order, sincePaymentMethodId, null);
  }

  /**
   * List payment methods
   * Retrieve a paginated list of stored payment methods.  Returns payment methods with sensitive information masked for security. Use pagination parameters to navigate through large result sets. 
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param count Number of payment methods to return (optional, default to 20)
   * @param order Sort order for results (optional, default to asc)
   * @param sincePaymentMethodId Return payment methods after this ID (for pagination) (optional)
   * @param headers Optional headers to include in the request
   * @return List&lt;PaymentMethodResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PaymentMethodResponse> listPaymentMethods(@javax.annotation.Nullable String xApiVersion, @javax.annotation.Nullable Integer count, @javax.annotation.Nullable String order, @javax.annotation.Nullable String sincePaymentMethodId, Map<String, String> headers) throws ApiException {
    ApiResponse<List<PaymentMethodResponse>> localVarResponse = listPaymentMethodsWithHttpInfo(xApiVersion, count, order, sincePaymentMethodId, headers);
    return localVarResponse.getData();
  }

  /**
   * List payment methods
   * Retrieve a paginated list of stored payment methods.  Returns payment methods with sensitive information masked for security. Use pagination parameters to navigate through large result sets. 
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param count Number of payment methods to return (optional, default to 20)
   * @param order Sort order for results (optional, default to asc)
   * @param sincePaymentMethodId Return payment methods after this ID (for pagination) (optional)
   * @return ApiResponse&lt;List&lt;PaymentMethodResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PaymentMethodResponse>> listPaymentMethodsWithHttpInfo(@javax.annotation.Nullable String xApiVersion, @javax.annotation.Nullable Integer count, @javax.annotation.Nullable String order, @javax.annotation.Nullable String sincePaymentMethodId) throws ApiException {
    return listPaymentMethodsWithHttpInfo(xApiVersion, count, order, sincePaymentMethodId, null);
  }

  /**
   * List payment methods
   * Retrieve a paginated list of stored payment methods.  Returns payment methods with sensitive information masked for security. Use pagination parameters to navigate through large result sets. 
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param count Number of payment methods to return (optional, default to 20)
   * @param order Sort order for results (optional, default to asc)
   * @param sincePaymentMethodId Return payment methods after this ID (for pagination) (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;PaymentMethodResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PaymentMethodResponse>> listPaymentMethodsWithHttpInfo(@javax.annotation.Nullable String xApiVersion, @javax.annotation.Nullable Integer count, @javax.annotation.Nullable String order, @javax.annotation.Nullable String sincePaymentMethodId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listPaymentMethodsRequestBuilder(xApiVersion, count, order, sincePaymentMethodId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listPaymentMethods", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<PaymentMethodResponse>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<PaymentMethodResponse> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<PaymentMethodResponse>>() {});
        

        return new ApiResponse<List<PaymentMethodResponse>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listPaymentMethodsRequestBuilder(@javax.annotation.Nullable String xApiVersion, @javax.annotation.Nullable Integer count, @javax.annotation.Nullable String order, @javax.annotation.Nullable String sincePaymentMethodId, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payment-methods/list";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "count";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("count", count));
    localVarQueryParameterBaseName = "order";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("order", order));
    localVarQueryParameterBaseName = "sincePaymentMethodId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sincePaymentMethodId", sincePaymentMethodId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (xApiVersion != null) {
      localVarRequestBuilder.header("X-Api-Version", xApiVersion.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Recache payment method
   * Update a credit card verification value (CVV) so the card can be transacted against     
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param paymentMethodRecacheRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse recachePaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull PaymentMethodRecacheRequest paymentMethodRecacheRequest, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return recachePaymentMethod(paymentMethodId, paymentMethodRecacheRequest, xApiVersion, null);
  }

  /**
   * Recache payment method
   * Update a credit card verification value (CVV) so the card can be transacted against     
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param paymentMethodRecacheRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse recachePaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull PaymentMethodRecacheRequest paymentMethodRecacheRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    ApiResponse<PaymentMethodWriteResponse> localVarResponse = recachePaymentMethodWithHttpInfo(paymentMethodId, paymentMethodRecacheRequest, xApiVersion, headers);
    return localVarResponse.getData();
  }

  /**
   * Recache payment method
   * Update a credit card verification value (CVV) so the card can be transacted against     
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param paymentMethodRecacheRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> recachePaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull PaymentMethodRecacheRequest paymentMethodRecacheRequest, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return recachePaymentMethodWithHttpInfo(paymentMethodId, paymentMethodRecacheRequest, xApiVersion, null);
  }

  /**
   * Recache payment method
   * Update a credit card verification value (CVV) so the card can be transacted against     
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param paymentMethodRecacheRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> recachePaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull PaymentMethodRecacheRequest paymentMethodRecacheRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = recachePaymentMethodRequestBuilder(paymentMethodId, paymentMethodRecacheRequest, xApiVersion, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("recachePaymentMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PaymentMethodWriteResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PaymentMethodWriteResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PaymentMethodWriteResponse>() {});
        

        return new ApiResponse<PaymentMethodWriteResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder recachePaymentMethodRequestBuilder(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull PaymentMethodRecacheRequest paymentMethodRecacheRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'paymentMethodId' is set
    if (paymentMethodId == null) {
      throw new ApiException(400, "Missing the required parameter 'paymentMethodId' when calling recachePaymentMethod");
    }
    // verify the required parameter 'paymentMethodRecacheRequest' is set
    if (paymentMethodRecacheRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'paymentMethodRecacheRequest' when calling recachePaymentMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payment-methods/recache/{paymentMethodId}"
        .replace("{paymentMethodId}", ApiClient.urlEncode(paymentMethodId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiVersion != null) {
      localVarRequestBuilder.header("X-Api-Version", xApiVersion.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(paymentMethodRecacheRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Redact payment method
   * Redact sensitive payment method information for compliance purposes.  This operation permanently removes sensitive data while keeping the payment method record for historical and reporting purposes. This action cannot be undone. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse redactPaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return redactPaymentMethod(paymentMethodId, xApiVersion, null);
  }

  /**
   * Redact payment method
   * Redact sensitive payment method information for compliance purposes.  This operation permanently removes sensitive data while keeping the payment method record for historical and reporting purposes. This action cannot be undone. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse redactPaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    ApiResponse<PaymentMethodWriteResponse> localVarResponse = redactPaymentMethodWithHttpInfo(paymentMethodId, xApiVersion, headers);
    return localVarResponse.getData();
  }

  /**
   * Redact payment method
   * Redact sensitive payment method information for compliance purposes.  This operation permanently removes sensitive data while keeping the payment method record for historical and reporting purposes. This action cannot be undone. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> redactPaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return redactPaymentMethodWithHttpInfo(paymentMethodId, xApiVersion, null);
  }

  /**
   * Redact payment method
   * Redact sensitive payment method information for compliance purposes.  This operation permanently removes sensitive data while keeping the payment method record for historical and reporting purposes. This action cannot be undone. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> redactPaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = redactPaymentMethodRequestBuilder(paymentMethodId, xApiVersion, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("redactPaymentMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PaymentMethodWriteResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PaymentMethodWriteResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PaymentMethodWriteResponse>() {});
        

        return new ApiResponse<PaymentMethodWriteResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder redactPaymentMethodRequestBuilder(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'paymentMethodId' is set
    if (paymentMethodId == null) {
      throw new ApiException(400, "Missing the required parameter 'paymentMethodId' when calling redactPaymentMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payment-methods/redact/{paymentMethodId}"
        .replace("{paymentMethodId}", ApiClient.urlEncode(paymentMethodId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiVersion != null) {
      localVarRequestBuilder.header("X-Api-Version", xApiVersion.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update payment method
   * Update an existing payment method&#39;s information.  Allows updating billing information, expiration dates, and other non-sensitive data. Sensitive card data cannot be updated directly. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param updatePaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse updatePaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull UpdatePaymentMethodRequest updatePaymentMethodRequest, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return updatePaymentMethod(paymentMethodId, updatePaymentMethodRequest, xApiVersion, null);
  }

  /**
   * Update payment method
   * Update an existing payment method&#39;s information.  Allows updating billing information, expiration dates, and other non-sensitive data. Sensitive card data cannot be updated directly. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param updatePaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return PaymentMethodWriteResponse
   * @throws ApiException if fails to make API call
   */
  public PaymentMethodWriteResponse updatePaymentMethod(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull UpdatePaymentMethodRequest updatePaymentMethodRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    ApiResponse<PaymentMethodWriteResponse> localVarResponse = updatePaymentMethodWithHttpInfo(paymentMethodId, updatePaymentMethodRequest, xApiVersion, headers);
    return localVarResponse.getData();
  }

  /**
   * Update payment method
   * Update an existing payment method&#39;s information.  Allows updating billing information, expiration dates, and other non-sensitive data. Sensitive card data cannot be updated directly. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param updatePaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> updatePaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull UpdatePaymentMethodRequest updatePaymentMethodRequest, @javax.annotation.Nullable String xApiVersion) throws ApiException {
    return updatePaymentMethodWithHttpInfo(paymentMethodId, updatePaymentMethodRequest, xApiVersion, null);
  }

  /**
   * Update payment method
   * Update an existing payment method&#39;s information.  Allows updating billing information, expiration dates, and other non-sensitive data. Sensitive card data cannot be updated directly. 
   * @param paymentMethodId Unique identifier for the payment method (required)
   * @param updatePaymentMethodRequest  (required)
   * @param xApiVersion Selects the RAP API version for this request. New integrations should pin &#x60;2.1&#x60; (identical to &#x60;2.0&#x60; today; future refinements land there). Omit to use the base version (&#x60;2.0&#x60;). A value naming an unsupported version — including an empty value — returns HTTP 400; if the header is sent, it must name a supported version. See the API description for the full version policy. (optional, default to 2.0)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PaymentMethodWriteResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaymentMethodWriteResponse> updatePaymentMethodWithHttpInfo(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull UpdatePaymentMethodRequest updatePaymentMethodRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updatePaymentMethodRequestBuilder(paymentMethodId, updatePaymentMethodRequest, xApiVersion, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updatePaymentMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PaymentMethodWriteResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PaymentMethodWriteResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PaymentMethodWriteResponse>() {});
        

        return new ApiResponse<PaymentMethodWriteResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updatePaymentMethodRequestBuilder(@javax.annotation.Nonnull String paymentMethodId, @javax.annotation.Nonnull UpdatePaymentMethodRequest updatePaymentMethodRequest, @javax.annotation.Nullable String xApiVersion, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'paymentMethodId' is set
    if (paymentMethodId == null) {
      throw new ApiException(400, "Missing the required parameter 'paymentMethodId' when calling updatePaymentMethod");
    }
    // verify the required parameter 'updatePaymentMethodRequest' is set
    if (updatePaymentMethodRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updatePaymentMethodRequest' when calling updatePaymentMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/payment-methods/update/{paymentMethodId}"
        .replace("{paymentMethodId}", ApiClient.urlEncode(paymentMethodId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (xApiVersion != null) {
      localVarRequestBuilder.header("X-Api-Version", xApiVersion.toString());
    }
    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updatePaymentMethodRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
