<?php
/**
 * PreviousTransaction
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Revaly\Sdk\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Revaly
 *
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string.
 *
 * The version of the OpenAPI document: 2.2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Revaly\Sdk\Core\Model;

use \ArrayAccess;
use \Revaly\Sdk\Core\ObjectSerializer;

/**
 * PreviousTransaction Class Doc Comment
 *
 * @category Class
 * @description Information about a previous transaction for reference
 * @package  Revaly\Sdk\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PreviousTransaction implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PreviousTransaction';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'transaction_date' => '\DateTime',
        'merchant_account_reference_id' => 'string',
        'gateway_code' => 'string',
        'gateway_message' => 'string',
        'gateway_message_key' => 'string',
        'transaction_status' => 'int',
        'avs_code' => 'string',
        'avs_message' => 'string',
        'cvv_code' => 'string',
        'cvv_message' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'transaction_date' => 'date-time',
        'merchant_account_reference_id' => null,
        'gateway_code' => null,
        'gateway_message' => null,
        'gateway_message_key' => null,
        'transaction_status' => null,
        'avs_code' => null,
        'avs_message' => null,
        'cvv_code' => null,
        'cvv_message' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'transaction_date' => true,
        'merchant_account_reference_id' => true,
        'gateway_code' => true,
        'gateway_message' => true,
        'gateway_message_key' => true,
        'transaction_status' => true,
        'avs_code' => true,
        'avs_message' => true,
        'cvv_code' => true,
        'cvv_message' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transaction_date' => 'transactionDate',
        'merchant_account_reference_id' => 'merchantAccountReferenceId',
        'gateway_code' => 'gatewayCode',
        'gateway_message' => 'gatewayMessage',
        'gateway_message_key' => 'gatewayMessageKey',
        'transaction_status' => 'transactionStatus',
        'avs_code' => 'avsCode',
        'avs_message' => 'avsMessage',
        'cvv_code' => 'cvvCode',
        'cvv_message' => 'cvvMessage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transaction_date' => 'setTransactionDate',
        'merchant_account_reference_id' => 'setMerchantAccountReferenceId',
        'gateway_code' => 'setGatewayCode',
        'gateway_message' => 'setGatewayMessage',
        'gateway_message_key' => 'setGatewayMessageKey',
        'transaction_status' => 'setTransactionStatus',
        'avs_code' => 'setAvsCode',
        'avs_message' => 'setAvsMessage',
        'cvv_code' => 'setCvvCode',
        'cvv_message' => 'setCvvMessage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transaction_date' => 'getTransactionDate',
        'merchant_account_reference_id' => 'getMerchantAccountReferenceId',
        'gateway_code' => 'getGatewayCode',
        'gateway_message' => 'getGatewayMessage',
        'gateway_message_key' => 'getGatewayMessageKey',
        'transaction_status' => 'getTransactionStatus',
        'avs_code' => 'getAvsCode',
        'avs_message' => 'getAvsMessage',
        'cvv_code' => 'getCvvCode',
        'cvv_message' => 'getCvvMessage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('transaction_date', $data ?? [], null);
        $this->setIfExists('merchant_account_reference_id', $data ?? [], null);
        $this->setIfExists('gateway_code', $data ?? [], null);
        $this->setIfExists('gateway_message', $data ?? [], null);
        $this->setIfExists('gateway_message_key', $data ?? [], null);
        $this->setIfExists('transaction_status', $data ?? [], null);
        $this->setIfExists('avs_code', $data ?? [], null);
        $this->setIfExists('avs_message', $data ?? [], null);
        $this->setIfExists('cvv_code', $data ?? [], null);
        $this->setIfExists('cvv_message', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['merchant_account_reference_id']) && (mb_strlen($this->container['merchant_account_reference_id']) > 100)) {
            $invalidProperties[] = "invalid value for 'merchant_account_reference_id', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['gateway_code']) && (mb_strlen($this->container['gateway_code']) > 50)) {
            $invalidProperties[] = "invalid value for 'gateway_code', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['gateway_message']) && (mb_strlen($this->container['gateway_message']) > 255)) {
            $invalidProperties[] = "invalid value for 'gateway_message', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['gateway_message_key']) && (mb_strlen($this->container['gateway_message_key']) > 100)) {
            $invalidProperties[] = "invalid value for 'gateway_message_key', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['avs_code']) && (mb_strlen($this->container['avs_code']) > 10)) {
            $invalidProperties[] = "invalid value for 'avs_code', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['avs_message']) && (mb_strlen($this->container['avs_message']) > 255)) {
            $invalidProperties[] = "invalid value for 'avs_message', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['cvv_code']) && (mb_strlen($this->container['cvv_code']) > 10)) {
            $invalidProperties[] = "invalid value for 'cvv_code', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['cvv_message']) && (mb_strlen($this->container['cvv_message']) > 255)) {
            $invalidProperties[] = "invalid value for 'cvv_message', the character length must be smaller than or equal to 255.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transaction_date
     *
     * @return \DateTime|null
     */
    public function getTransactionDate()
    {
        return $this->container['transaction_date'];
    }

    /**
     * Sets transaction_date
     *
     * @param \DateTime|null $transaction_date Date of the previous transaction
     *
     * @return self
     */
    public function setTransactionDate($transaction_date)
    {
        if (is_null($transaction_date)) {
            array_push($this->openAPINullablesSetToNull, 'transaction_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transaction_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['transaction_date'] = $transaction_date;

        return $this;
    }

    /**
     * Gets merchant_account_reference_id
     *
     * @return string|null
     */
    public function getMerchantAccountReferenceId()
    {
        return $this->container['merchant_account_reference_id'];
    }

    /**
     * Sets merchant_account_reference_id
     *
     * @param string|null $merchant_account_reference_id Merchant account reference ID from the previous transaction
     *
     * @return self
     */
    public function setMerchantAccountReferenceId($merchant_account_reference_id)
    {
        if (is_null($merchant_account_reference_id)) {
            array_push($this->openAPINullablesSetToNull, 'merchant_account_reference_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('merchant_account_reference_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($merchant_account_reference_id) && (mb_strlen($merchant_account_reference_id) > 100)) {
            throw new \InvalidArgumentException('invalid length for $merchant_account_reference_id when calling PreviousTransaction., must be smaller than or equal to 100.');
        }

        $this->container['merchant_account_reference_id'] = $merchant_account_reference_id;

        return $this;
    }

    /**
     * Gets gateway_code
     *
     * @return string|null
     */
    public function getGatewayCode()
    {
        return $this->container['gateway_code'];
    }

    /**
     * Sets gateway_code
     *
     * @param string|null $gateway_code Gateway response code from the previous transaction
     *
     * @return self
     */
    public function setGatewayCode($gateway_code)
    {
        if (is_null($gateway_code)) {
            array_push($this->openAPINullablesSetToNull, 'gateway_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gateway_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($gateway_code) && (mb_strlen($gateway_code) > 50)) {
            throw new \InvalidArgumentException('invalid length for $gateway_code when calling PreviousTransaction., must be smaller than or equal to 50.');
        }

        $this->container['gateway_code'] = $gateway_code;

        return $this;
    }

    /**
     * Gets gateway_message
     *
     * @return string|null
     */
    public function getGatewayMessage()
    {
        return $this->container['gateway_message'];
    }

    /**
     * Sets gateway_message
     *
     * @param string|null $gateway_message Gateway response message from the previous transaction
     *
     * @return self
     */
    public function setGatewayMessage($gateway_message)
    {
        if (is_null($gateway_message)) {
            array_push($this->openAPINullablesSetToNull, 'gateway_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gateway_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($gateway_message) && (mb_strlen($gateway_message) > 255)) {
            throw new \InvalidArgumentException('invalid length for $gateway_message when calling PreviousTransaction., must be smaller than or equal to 255.');
        }

        $this->container['gateway_message'] = $gateway_message;

        return $this;
    }

    /**
     * Gets gateway_message_key
     *
     * @return string|null
     */
    public function getGatewayMessageKey()
    {
        return $this->container['gateway_message_key'];
    }

    /**
     * Sets gateway_message_key
     *
     * @param string|null $gateway_message_key Gateway message key from the previous transaction
     *
     * @return self
     */
    public function setGatewayMessageKey($gateway_message_key)
    {
        if (is_null($gateway_message_key)) {
            array_push($this->openAPINullablesSetToNull, 'gateway_message_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gateway_message_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($gateway_message_key) && (mb_strlen($gateway_message_key) > 100)) {
            throw new \InvalidArgumentException('invalid length for $gateway_message_key when calling PreviousTransaction., must be smaller than or equal to 100.');
        }

        $this->container['gateway_message_key'] = $gateway_message_key;

        return $this;
    }

    /**
     * Gets transaction_status
     *
     * @return int|null
     */
    public function getTransactionStatus()
    {
        return $this->container['transaction_status'];
    }

    /**
     * Sets transaction_status
     *
     * @param int|null $transaction_status Previous status of the transaction (1 = Approved, 2 = Declined, 3 = Error)
     *
     * @return self
     */
    public function setTransactionStatus($transaction_status)
    {
        if (is_null($transaction_status)) {
            array_push($this->openAPINullablesSetToNull, 'transaction_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transaction_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['transaction_status'] = $transaction_status;

        return $this;
    }

    /**
     * Gets avs_code
     *
     * @return string|null
     */
    public function getAvsCode()
    {
        return $this->container['avs_code'];
    }

    /**
     * Sets avs_code
     *
     * @param string|null $avs_code AVS code from the previous transaction
     *
     * @return self
     */
    public function setAvsCode($avs_code)
    {
        if (is_null($avs_code)) {
            array_push($this->openAPINullablesSetToNull, 'avs_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avs_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($avs_code) && (mb_strlen($avs_code) > 10)) {
            throw new \InvalidArgumentException('invalid length for $avs_code when calling PreviousTransaction., must be smaller than or equal to 10.');
        }

        $this->container['avs_code'] = $avs_code;

        return $this;
    }

    /**
     * Gets avs_message
     *
     * @return string|null
     */
    public function getAvsMessage()
    {
        return $this->container['avs_message'];
    }

    /**
     * Sets avs_message
     *
     * @param string|null $avs_message AVS message from the previous transaction
     *
     * @return self
     */
    public function setAvsMessage($avs_message)
    {
        if (is_null($avs_message)) {
            array_push($this->openAPINullablesSetToNull, 'avs_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avs_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($avs_message) && (mb_strlen($avs_message) > 255)) {
            throw new \InvalidArgumentException('invalid length for $avs_message when calling PreviousTransaction., must be smaller than or equal to 255.');
        }

        $this->container['avs_message'] = $avs_message;

        return $this;
    }

    /**
     * Gets cvv_code
     *
     * @return string|null
     */
    public function getCvvCode()
    {
        return $this->container['cvv_code'];
    }

    /**
     * Sets cvv_code
     *
     * @param string|null $cvv_code CVV code from the previous transaction
     *
     * @return self
     */
    public function setCvvCode($cvv_code)
    {
        if (is_null($cvv_code)) {
            array_push($this->openAPINullablesSetToNull, 'cvv_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cvv_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($cvv_code) && (mb_strlen($cvv_code) > 10)) {
            throw new \InvalidArgumentException('invalid length for $cvv_code when calling PreviousTransaction., must be smaller than or equal to 10.');
        }

        $this->container['cvv_code'] = $cvv_code;

        return $this;
    }

    /**
     * Gets cvv_message
     *
     * @return string|null
     */
    public function getCvvMessage()
    {
        return $this->container['cvv_message'];
    }

    /**
     * Sets cvv_message
     *
     * @param string|null $cvv_message CVV message from the previous transaction
     *
     * @return self
     */
    public function setCvvMessage($cvv_message)
    {
        if (is_null($cvv_message)) {
            array_push($this->openAPINullablesSetToNull, 'cvv_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cvv_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($cvv_message) && (mb_strlen($cvv_message) > 255)) {
            throw new \InvalidArgumentException('invalid length for $cvv_message when calling PreviousTransaction., must be smaller than or equal to 255.');
        }

        $this->container['cvv_message'] = $cvv_message;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


