<?php
/**
 * RtnDataOrderData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Revaly\Sdk\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Revaly
 *
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string.
 *
 * The version of the OpenAPI document: 2.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Revaly\Sdk\Core\Model;

use \ArrayAccess;
use \Revaly\Sdk\Core\ObjectSerializer;

/**
 * RtnDataOrderData Class Doc Comment
 *
 * @category Class
 * @description Order and purchase details. All fields optional.
 * @package  Revaly\Sdk\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RtnDataOrderData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RtnData_orderData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'purchase_date' => '\DateTime',
        'item_count' => 'int',
        'highest_price_item_price' => 'int',
        'highest_price_item_brand' => 'string',
        'highest_price_item_category' => 'string',
        'is_pre_order_purchase' => 'bool',
        'pre_order_date' => 'string',
        'is_reorder' => 'bool',
        'installment_payment_count' => 'int',
        'is_recurring_purchase' => 'bool',
        'recurring_interval_days' => 'int',
        'recurring_end_date' => 'string',
        'alternate_payment_indicator' => 'string',
        'gift_card_count' => 'int',
        'gift_card_amount' => 'int',
        'gift_card_currency' => 'string',
        'installment_payment_data' => 'string',
        'top_item_categories' => 'string',
        'highest_price_item_sku' => 'string',
        'is_coupon_used' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'purchase_date' => 'date-time',
        'item_count' => null,
        'highest_price_item_price' => null,
        'highest_price_item_brand' => null,
        'highest_price_item_category' => null,
        'is_pre_order_purchase' => null,
        'pre_order_date' => null,
        'is_reorder' => null,
        'installment_payment_count' => null,
        'is_recurring_purchase' => null,
        'recurring_interval_days' => null,
        'recurring_end_date' => null,
        'alternate_payment_indicator' => null,
        'gift_card_count' => null,
        'gift_card_amount' => 'int32',
        'gift_card_currency' => null,
        'installment_payment_data' => null,
        'top_item_categories' => null,
        'highest_price_item_sku' => null,
        'is_coupon_used' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'purchase_date' => false,
        'item_count' => false,
        'highest_price_item_price' => false,
        'highest_price_item_brand' => false,
        'highest_price_item_category' => false,
        'is_pre_order_purchase' => false,
        'pre_order_date' => false,
        'is_reorder' => false,
        'installment_payment_count' => false,
        'is_recurring_purchase' => false,
        'recurring_interval_days' => false,
        'recurring_end_date' => false,
        'alternate_payment_indicator' => false,
        'gift_card_count' => false,
        'gift_card_amount' => false,
        'gift_card_currency' => false,
        'installment_payment_data' => false,
        'top_item_categories' => false,
        'highest_price_item_sku' => false,
        'is_coupon_used' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'purchase_date' => 'purchaseDate',
        'item_count' => 'itemCount',
        'highest_price_item_price' => 'highestPriceItemPrice',
        'highest_price_item_brand' => 'highestPriceItemBrand',
        'highest_price_item_category' => 'highestPriceItemCategory',
        'is_pre_order_purchase' => 'isPreOrderPurchase',
        'pre_order_date' => 'preOrderDate',
        'is_reorder' => 'isReorder',
        'installment_payment_count' => 'installmentPaymentCount',
        'is_recurring_purchase' => 'isRecurringPurchase',
        'recurring_interval_days' => 'recurringIntervalDays',
        'recurring_end_date' => 'recurringEndDate',
        'alternate_payment_indicator' => 'alternatePaymentIndicator',
        'gift_card_count' => 'giftCardCount',
        'gift_card_amount' => 'giftCardAmount',
        'gift_card_currency' => 'giftCardCurrency',
        'installment_payment_data' => 'installmentPaymentData',
        'top_item_categories' => 'topItemCategories',
        'highest_price_item_sku' => 'highestPriceItemSku',
        'is_coupon_used' => 'isCouponUsed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'purchase_date' => 'setPurchaseDate',
        'item_count' => 'setItemCount',
        'highest_price_item_price' => 'setHighestPriceItemPrice',
        'highest_price_item_brand' => 'setHighestPriceItemBrand',
        'highest_price_item_category' => 'setHighestPriceItemCategory',
        'is_pre_order_purchase' => 'setIsPreOrderPurchase',
        'pre_order_date' => 'setPreOrderDate',
        'is_reorder' => 'setIsReorder',
        'installment_payment_count' => 'setInstallmentPaymentCount',
        'is_recurring_purchase' => 'setIsRecurringPurchase',
        'recurring_interval_days' => 'setRecurringIntervalDays',
        'recurring_end_date' => 'setRecurringEndDate',
        'alternate_payment_indicator' => 'setAlternatePaymentIndicator',
        'gift_card_count' => 'setGiftCardCount',
        'gift_card_amount' => 'setGiftCardAmount',
        'gift_card_currency' => 'setGiftCardCurrency',
        'installment_payment_data' => 'setInstallmentPaymentData',
        'top_item_categories' => 'setTopItemCategories',
        'highest_price_item_sku' => 'setHighestPriceItemSku',
        'is_coupon_used' => 'setIsCouponUsed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'purchase_date' => 'getPurchaseDate',
        'item_count' => 'getItemCount',
        'highest_price_item_price' => 'getHighestPriceItemPrice',
        'highest_price_item_brand' => 'getHighestPriceItemBrand',
        'highest_price_item_category' => 'getHighestPriceItemCategory',
        'is_pre_order_purchase' => 'getIsPreOrderPurchase',
        'pre_order_date' => 'getPreOrderDate',
        'is_reorder' => 'getIsReorder',
        'installment_payment_count' => 'getInstallmentPaymentCount',
        'is_recurring_purchase' => 'getIsRecurringPurchase',
        'recurring_interval_days' => 'getRecurringIntervalDays',
        'recurring_end_date' => 'getRecurringEndDate',
        'alternate_payment_indicator' => 'getAlternatePaymentIndicator',
        'gift_card_count' => 'getGiftCardCount',
        'gift_card_amount' => 'getGiftCardAmount',
        'gift_card_currency' => 'getGiftCardCurrency',
        'installment_payment_data' => 'getInstallmentPaymentData',
        'top_item_categories' => 'getTopItemCategories',
        'highest_price_item_sku' => 'getHighestPriceItemSku',
        'is_coupon_used' => 'getIsCouponUsed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ALTERNATE_PAYMENT_INDICATOR__01 = '01';
    public const ALTERNATE_PAYMENT_INDICATOR__02 = '02';
    public const ALTERNATE_PAYMENT_INDICATOR__03 = '03';
    public const ALTERNATE_PAYMENT_INDICATOR__04 = '04';
    public const ALTERNATE_PAYMENT_INDICATOR_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
    public const IS_COUPON_USED_Y = 'Y';
    public const IS_COUPON_USED_N = 'N';
    public const IS_COUPON_USED_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAlternatePaymentIndicatorAllowableValues()
    {
        return [
            self::ALTERNATE_PAYMENT_INDICATOR__01,
            self::ALTERNATE_PAYMENT_INDICATOR__02,
            self::ALTERNATE_PAYMENT_INDICATOR__03,
            self::ALTERNATE_PAYMENT_INDICATOR__04,
            self::ALTERNATE_PAYMENT_INDICATOR_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIsCouponUsedAllowableValues()
    {
        return [
            self::IS_COUPON_USED_Y,
            self::IS_COUPON_USED_N,
            self::IS_COUPON_USED_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('purchase_date', $data ?? [], null);
        $this->setIfExists('item_count', $data ?? [], null);
        $this->setIfExists('highest_price_item_price', $data ?? [], null);
        $this->setIfExists('highest_price_item_brand', $data ?? [], null);
        $this->setIfExists('highest_price_item_category', $data ?? [], null);
        $this->setIfExists('is_pre_order_purchase', $data ?? [], null);
        $this->setIfExists('pre_order_date', $data ?? [], null);
        $this->setIfExists('is_reorder', $data ?? [], null);
        $this->setIfExists('installment_payment_count', $data ?? [], null);
        $this->setIfExists('is_recurring_purchase', $data ?? [], null);
        $this->setIfExists('recurring_interval_days', $data ?? [], null);
        $this->setIfExists('recurring_end_date', $data ?? [], null);
        $this->setIfExists('alternate_payment_indicator', $data ?? [], null);
        $this->setIfExists('gift_card_count', $data ?? [], null);
        $this->setIfExists('gift_card_amount', $data ?? [], null);
        $this->setIfExists('gift_card_currency', $data ?? [], null);
        $this->setIfExists('installment_payment_data', $data ?? [], null);
        $this->setIfExists('top_item_categories', $data ?? [], null);
        $this->setIfExists('highest_price_item_sku', $data ?? [], null);
        $this->setIfExists('is_coupon_used', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['item_count']) && ($this->container['item_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'item_count', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['highest_price_item_price']) && ($this->container['highest_price_item_price'] < 0)) {
            $invalidProperties[] = "invalid value for 'highest_price_item_price', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['pre_order_date']) && !preg_match("/^\\d{8}$/", $this->container['pre_order_date'])) {
            $invalidProperties[] = "invalid value for 'pre_order_date', must be conform to the pattern /^\\d{8}$/.";
        }

        if (!is_null($this->container['installment_payment_count']) && ($this->container['installment_payment_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'installment_payment_count', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['recurring_interval_days']) && ($this->container['recurring_interval_days'] < 1)) {
            $invalidProperties[] = "invalid value for 'recurring_interval_days', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['recurring_end_date']) && !preg_match("/^\\d{8}$/", $this->container['recurring_end_date'])) {
            $invalidProperties[] = "invalid value for 'recurring_end_date', must be conform to the pattern /^\\d{8}$/.";
        }

        $allowedValues = $this->getAlternatePaymentIndicatorAllowableValues();
        if (!is_null($this->container['alternate_payment_indicator']) && !in_array($this->container['alternate_payment_indicator'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'alternate_payment_indicator', must be one of '%s'",
                $this->container['alternate_payment_indicator'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['gift_card_count']) && ($this->container['gift_card_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'gift_card_count', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['gift_card_amount']) && ($this->container['gift_card_amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'gift_card_amount', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['top_item_categories']) && (mb_strlen($this->container['top_item_categories']) > 20)) {
            $invalidProperties[] = "invalid value for 'top_item_categories', the character length must be smaller than or equal to 20.";
        }

        if (!is_null($this->container['highest_price_item_sku']) && (mb_strlen($this->container['highest_price_item_sku']) > 16)) {
            $invalidProperties[] = "invalid value for 'highest_price_item_sku', the character length must be smaller than or equal to 16.";
        }

        $allowedValues = $this->getIsCouponUsedAllowableValues();
        if (!is_null($this->container['is_coupon_used']) && !in_array($this->container['is_coupon_used'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'is_coupon_used', must be one of '%s'",
                $this->container['is_coupon_used'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets purchase_date
     *
     * @return \DateTime|null
     */
    public function getPurchaseDate()
    {
        return $this->container['purchase_date'];
    }

    /**
     * Sets purchase_date
     *
     * @param \DateTime|null $purchase_date ISO 8601 UTC timestamp of the purchase.
     *
     * @return self
     */
    public function setPurchaseDate($purchase_date)
    {
        if (is_null($purchase_date)) {
            throw new \InvalidArgumentException('non-nullable purchase_date cannot be null');
        }
        $this->container['purchase_date'] = $purchase_date;

        return $this;
    }

    /**
     * Gets item_count
     *
     * @return int|null
     */
    public function getItemCount()
    {
        return $this->container['item_count'];
    }

    /**
     * Sets item_count
     *
     * @param int|null $item_count Total number of items in the order.
     *
     * @return self
     */
    public function setItemCount($item_count)
    {
        if (is_null($item_count)) {
            throw new \InvalidArgumentException('non-nullable item_count cannot be null');
        }

        if (($item_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $item_count when calling RtnDataOrderData., must be bigger than or equal to 0.');
        }

        $this->container['item_count'] = $item_count;

        return $this;
    }

    /**
     * Gets highest_price_item_price
     *
     * @return int|null
     */
    public function getHighestPriceItemPrice()
    {
        return $this->container['highest_price_item_price'];
    }

    /**
     * Sets highest_price_item_price
     *
     * @param int|null $highest_price_item_price Price of the most expensive item in minor currency units.
     *
     * @return self
     */
    public function setHighestPriceItemPrice($highest_price_item_price)
    {
        if (is_null($highest_price_item_price)) {
            throw new \InvalidArgumentException('non-nullable highest_price_item_price cannot be null');
        }

        if (($highest_price_item_price < 0)) {
            throw new \InvalidArgumentException('invalid value for $highest_price_item_price when calling RtnDataOrderData., must be bigger than or equal to 0.');
        }

        $this->container['highest_price_item_price'] = $highest_price_item_price;

        return $this;
    }

    /**
     * Gets highest_price_item_brand
     *
     * @return string|null
     */
    public function getHighestPriceItemBrand()
    {
        return $this->container['highest_price_item_brand'];
    }

    /**
     * Sets highest_price_item_brand
     *
     * @param string|null $highest_price_item_brand Brand of the most expensive item.
     *
     * @return self
     */
    public function setHighestPriceItemBrand($highest_price_item_brand)
    {
        if (is_null($highest_price_item_brand)) {
            throw new \InvalidArgumentException('non-nullable highest_price_item_brand cannot be null');
        }
        $this->container['highest_price_item_brand'] = $highest_price_item_brand;

        return $this;
    }

    /**
     * Gets highest_price_item_category
     *
     * @return string|null
     */
    public function getHighestPriceItemCategory()
    {
        return $this->container['highest_price_item_category'];
    }

    /**
     * Sets highest_price_item_category
     *
     * @param string|null $highest_price_item_category Category of the most expensive item.
     *
     * @return self
     */
    public function setHighestPriceItemCategory($highest_price_item_category)
    {
        if (is_null($highest_price_item_category)) {
            throw new \InvalidArgumentException('non-nullable highest_price_item_category cannot be null');
        }
        $this->container['highest_price_item_category'] = $highest_price_item_category;

        return $this;
    }

    /**
     * Gets is_pre_order_purchase
     *
     * @return bool|null
     */
    public function getIsPreOrderPurchase()
    {
        return $this->container['is_pre_order_purchase'];
    }

    /**
     * Sets is_pre_order_purchase
     *
     * @param bool|null $is_pre_order_purchase True if the order contains pre-order items.
     *
     * @return self
     */
    public function setIsPreOrderPurchase($is_pre_order_purchase)
    {
        if (is_null($is_pre_order_purchase)) {
            throw new \InvalidArgumentException('non-nullable is_pre_order_purchase cannot be null');
        }
        $this->container['is_pre_order_purchase'] = $is_pre_order_purchase;

        return $this;
    }

    /**
     * Gets pre_order_date
     *
     * @return string|null
     */
    public function getPreOrderDate()
    {
        return $this->container['pre_order_date'];
    }

    /**
     * Sets pre_order_date
     *
     * @param string|null $pre_order_date Expected availability date for pre-order items. Format YYYYMMDD.
     *
     * @return self
     */
    public function setPreOrderDate($pre_order_date)
    {
        if (is_null($pre_order_date)) {
            throw new \InvalidArgumentException('non-nullable pre_order_date cannot be null');
        }

        if ((!preg_match("/^\\d{8}$/", ObjectSerializer::toString($pre_order_date)))) {
            throw new \InvalidArgumentException("invalid value for \$pre_order_date when calling RtnDataOrderData., must conform to the pattern /^\\d{8}$/.");
        }

        $this->container['pre_order_date'] = $pre_order_date;

        return $this;
    }

    /**
     * Gets is_reorder
     *
     * @return bool|null
     */
    public function getIsReorder()
    {
        return $this->container['is_reorder'];
    }

    /**
     * Sets is_reorder
     *
     * @param bool|null $is_reorder True if the customer has previously purchased this item.
     *
     * @return self
     */
    public function setIsReorder($is_reorder)
    {
        if (is_null($is_reorder)) {
            throw new \InvalidArgumentException('non-nullable is_reorder cannot be null');
        }
        $this->container['is_reorder'] = $is_reorder;

        return $this;
    }

    /**
     * Gets installment_payment_count
     *
     * @return int|null
     */
    public function getInstallmentPaymentCount()
    {
        return $this->container['installment_payment_count'];
    }

    /**
     * Sets installment_payment_count
     *
     * @param int|null $installment_payment_count Number of installment payments for this transaction.
     *
     * @return self
     */
    public function setInstallmentPaymentCount($installment_payment_count)
    {
        if (is_null($installment_payment_count)) {
            throw new \InvalidArgumentException('non-nullable installment_payment_count cannot be null');
        }

        if (($installment_payment_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $installment_payment_count when calling RtnDataOrderData., must be bigger than or equal to 0.');
        }

        $this->container['installment_payment_count'] = $installment_payment_count;

        return $this;
    }

    /**
     * Gets is_recurring_purchase
     *
     * @return bool|null
     */
    public function getIsRecurringPurchase()
    {
        return $this->container['is_recurring_purchase'];
    }

    /**
     * Sets is_recurring_purchase
     *
     * @param bool|null $is_recurring_purchase True if this purchase is part of a recurring series.
     *
     * @return self
     */
    public function setIsRecurringPurchase($is_recurring_purchase)
    {
        if (is_null($is_recurring_purchase)) {
            throw new \InvalidArgumentException('non-nullable is_recurring_purchase cannot be null');
        }
        $this->container['is_recurring_purchase'] = $is_recurring_purchase;

        return $this;
    }

    /**
     * Gets recurring_interval_days
     *
     * @return int|null
     */
    public function getRecurringIntervalDays()
    {
        return $this->container['recurring_interval_days'];
    }

    /**
     * Sets recurring_interval_days
     *
     * @param int|null $recurring_interval_days Days between recurring charges.
     *
     * @return self
     */
    public function setRecurringIntervalDays($recurring_interval_days)
    {
        if (is_null($recurring_interval_days)) {
            throw new \InvalidArgumentException('non-nullable recurring_interval_days cannot be null');
        }

        if (($recurring_interval_days < 1)) {
            throw new \InvalidArgumentException('invalid value for $recurring_interval_days when calling RtnDataOrderData., must be bigger than or equal to 1.');
        }

        $this->container['recurring_interval_days'] = $recurring_interval_days;

        return $this;
    }

    /**
     * Gets recurring_end_date
     *
     * @return string|null
     */
    public function getRecurringEndDate()
    {
        return $this->container['recurring_end_date'];
    }

    /**
     * Sets recurring_end_date
     *
     * @param string|null $recurring_end_date End date for recurring charges. Format YYYYMMDD.
     *
     * @return self
     */
    public function setRecurringEndDate($recurring_end_date)
    {
        if (is_null($recurring_end_date)) {
            throw new \InvalidArgumentException('non-nullable recurring_end_date cannot be null');
        }

        if ((!preg_match("/^\\d{8}$/", ObjectSerializer::toString($recurring_end_date)))) {
            throw new \InvalidArgumentException("invalid value for \$recurring_end_date when calling RtnDataOrderData., must conform to the pattern /^\\d{8}$/.");
        }

        $this->container['recurring_end_date'] = $recurring_end_date;

        return $this;
    }

    /**
     * Gets alternate_payment_indicator
     *
     * @return string|null
     */
    public function getAlternatePaymentIndicator()
    {
        return $this->container['alternate_payment_indicator'];
    }

    /**
     * Sets alternate_payment_indicator
     *
     * @param string|null $alternate_payment_indicator Alternative payment method: 01 = none, 02 = coupon, 03 = gift card, 04 = store credit.
     *
     * @return self
     */
    public function setAlternatePaymentIndicator($alternate_payment_indicator)
    {
        if (is_null($alternate_payment_indicator)) {
            throw new \InvalidArgumentException('non-nullable alternate_payment_indicator cannot be null');
        }
        $allowedValues = $this->getAlternatePaymentIndicatorAllowableValues();
        if (!in_array($alternate_payment_indicator, $allowedValues, true)) {
            $alternate_payment_indicator = self::ALTERNATE_PAYMENT_INDICATOR_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['alternate_payment_indicator'] = $alternate_payment_indicator;

        return $this;
    }

    /**
     * Gets gift_card_count
     *
     * @return int|null
     */
    public function getGiftCardCount()
    {
        return $this->container['gift_card_count'];
    }

    /**
     * Sets gift_card_count
     *
     * @param int|null $gift_card_count Number of gift cards applied to this order.
     *
     * @return self
     */
    public function setGiftCardCount($gift_card_count)
    {
        if (is_null($gift_card_count)) {
            throw new \InvalidArgumentException('non-nullable gift_card_count cannot be null');
        }

        if (($gift_card_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $gift_card_count when calling RtnDataOrderData., must be bigger than or equal to 0.');
        }

        $this->container['gift_card_count'] = $gift_card_count;

        return $this;
    }

    /**
     * Gets gift_card_amount
     *
     * @return int|null
     */
    public function getGiftCardAmount()
    {
        return $this->container['gift_card_amount'];
    }

    /**
     * Sets gift_card_amount
     *
     * @param int|null $gift_card_amount Total gift card amount in minor currency units.
     *
     * @return self
     */
    public function setGiftCardAmount($gift_card_amount)
    {
        if (is_null($gift_card_amount)) {
            throw new \InvalidArgumentException('non-nullable gift_card_amount cannot be null');
        }

        if (($gift_card_amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $gift_card_amount when calling RtnDataOrderData., must be bigger than or equal to 0.');
        }

        $this->container['gift_card_amount'] = $gift_card_amount;

        return $this;
    }

    /**
     * Gets gift_card_currency
     *
     * @return string|null
     */
    public function getGiftCardCurrency()
    {
        return $this->container['gift_card_currency'];
    }

    /**
     * Sets gift_card_currency
     *
     * @param string|null $gift_card_currency ISO 4217 numeric currency code for gift card amount.
     *
     * @return self
     */
    public function setGiftCardCurrency($gift_card_currency)
    {
        if (is_null($gift_card_currency)) {
            throw new \InvalidArgumentException('non-nullable gift_card_currency cannot be null');
        }
        $this->container['gift_card_currency'] = $gift_card_currency;

        return $this;
    }

    /**
     * Gets installment_payment_data
     *
     * @return string|null
     */
    public function getInstallmentPaymentData()
    {
        return $this->container['installment_payment_data'];
    }

    /**
     * Sets installment_payment_data
     *
     * @param string|null $installment_payment_data Number of installment payments as a string. String companion to installmentPaymentCount for FIs that expect a string.
     *
     * @return self
     */
    public function setInstallmentPaymentData($installment_payment_data)
    {
        if (is_null($installment_payment_data)) {
            throw new \InvalidArgumentException('non-nullable installment_payment_data cannot be null');
        }
        $this->container['installment_payment_data'] = $installment_payment_data;

        return $this;
    }

    /**
     * Gets top_item_categories
     *
     * @return string|null
     */
    public function getTopItemCategories()
    {
        return $this->container['top_item_categories'];
    }

    /**
     * Sets top_item_categories
     *
     * @param string|null $top_item_categories Up to five item-category codes concatenated as four-digit codes.
     *
     * @return self
     */
    public function setTopItemCategories($top_item_categories)
    {
        if (is_null($top_item_categories)) {
            throw new \InvalidArgumentException('non-nullable top_item_categories cannot be null');
        }
        if ((mb_strlen($top_item_categories) > 20)) {
            throw new \InvalidArgumentException('invalid length for $top_item_categories when calling RtnDataOrderData., must be smaller than or equal to 20.');
        }

        $this->container['top_item_categories'] = $top_item_categories;

        return $this;
    }

    /**
     * Gets highest_price_item_sku
     *
     * @return string|null
     */
    public function getHighestPriceItemSku()
    {
        return $this->container['highest_price_item_sku'];
    }

    /**
     * Sets highest_price_item_sku
     *
     * @param string|null $highest_price_item_sku SKU of the most expensive item in the order.
     *
     * @return self
     */
    public function setHighestPriceItemSku($highest_price_item_sku)
    {
        if (is_null($highest_price_item_sku)) {
            throw new \InvalidArgumentException('non-nullable highest_price_item_sku cannot be null');
        }
        if ((mb_strlen($highest_price_item_sku) > 16)) {
            throw new \InvalidArgumentException('invalid length for $highest_price_item_sku when calling RtnDataOrderData., must be smaller than or equal to 16.');
        }

        $this->container['highest_price_item_sku'] = $highest_price_item_sku;

        return $this;
    }

    /**
     * Gets is_coupon_used
     *
     * @return string|null
     */
    public function getIsCouponUsed()
    {
        return $this->container['is_coupon_used'];
    }

    /**
     * Sets is_coupon_used
     *
     * @param string|null $is_coupon_used Whether a coupon was used (Amex is_coupon_used). Narrower than alternatePaymentIndicator.
     *
     * @return self
     */
    public function setIsCouponUsed($is_coupon_used)
    {
        if (is_null($is_coupon_used)) {
            throw new \InvalidArgumentException('non-nullable is_coupon_used cannot be null');
        }
        $allowedValues = $this->getIsCouponUsedAllowableValues();
        if (!in_array($is_coupon_used, $allowedValues, true)) {
            $is_coupon_used = self::IS_COUPON_USED_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['is_coupon_used'] = $is_coupon_used;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


