// <auto-generated>
/*
 * Revaly
 *
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 
 *
 * The version of the OpenAPI document: 2.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Revaly.Sdk.Core.Client;

namespace Revaly.Sdk.Core.Model
{
    /// <summary>
    /// Associated transaction information
    /// </summary>
    public partial class PaymentMethodWriteResponseTransaction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodWriteResponseTransaction" /> class.
        /// </summary>
        /// <param name="transactionId">Unique identifier for the transaction</param>
        /// <param name="transactionDate">Date and time when the transaction was processed</param>
        /// <param name="transactionStatus">Current status of the transaction (1 &#x3D; Approved, 2 &#x3D; Declined, 3 &#x3D; Error)</param>
        /// <param name="message">Human-readable message about the transaction</param>
        /// <param name="responseCode">Gateway response code</param>
        /// <param name="transactionType">Type of transaction</param>
        [JsonConstructor]
        public PaymentMethodWriteResponseTransaction(Option<string?> transactionId = default, Option<DateTime?> transactionDate = default, Option<int?> transactionStatus = default, Option<string?> message = default, Option<string?> responseCode = default, Option<string?> transactionType = default)
        {
            TransactionIdOption = transactionId;
            TransactionDateOption = transactionDate;
            TransactionStatusOption = transactionStatus;
            MessageOption = message;
            ResponseCodeOption = responseCode;
            TransactionTypeOption = transactionType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TransactionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionIdOption { get; private set; }

        /// <summary>
        /// Unique identifier for the transaction
        /// </summary>
        /// <value>Unique identifier for the transaction</value>
        /* <example>06CQR5TMB800000G0011NCFRVY37A</example> */
        [JsonPropertyName("transactionId")]
        public string? TransactionId { get { return this.TransactionIdOption.Value; } set { this.TransactionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> TransactionDateOption { get; private set; }

        /// <summary>
        /// Date and time when the transaction was processed
        /// </summary>
        /// <value>Date and time when the transaction was processed</value>
        /* <example>2024-01-15T10:30Z</example> */
        [JsonPropertyName("transactionDate")]
        public DateTime? TransactionDate { get { return this.TransactionDateOption.Value; } set { this.TransactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TransactionStatusOption { get; private set; }

        /// <summary>
        /// Current status of the transaction (1 &#x3D; Approved, 2 &#x3D; Declined, 3 &#x3D; Error)
        /// </summary>
        /// <value>Current status of the transaction (1 &#x3D; Approved, 2 &#x3D; Declined, 3 &#x3D; Error)</value>
        /* <example>1</example> */
        [JsonPropertyName("transactionStatus")]
        public int? TransactionStatus { get { return this.TransactionStatusOption.Value; } set { this.TransactionStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Human-readable message about the transaction
        /// </summary>
        /// <value>Human-readable message about the transaction</value>
        /* <example>Payment method created successfully</example> */
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ResponseCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResponseCodeOption { get; private set; }

        /// <summary>
        /// Gateway response code
        /// </summary>
        /// <value>Gateway response code</value>
        /* <example>00</example> */
        [JsonPropertyName("responseCode")]
        public string? ResponseCode { get { return this.ResponseCodeOption.Value; } set { this.ResponseCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionTypeOption { get; private set; }

        /// <summary>
        /// Type of transaction
        /// </summary>
        /// <value>Type of transaction</value>
        /* <example>create_payment_method</example> */
        [JsonPropertyName("transactionType")]
        public string? TransactionType { get { return this.TransactionTypeOption.Value; } set { this.TransactionTypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentMethodWriteResponseTransaction {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  TransactionStatus: ").Append(TransactionStatus).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  ResponseCode: ").Append(ResponseCode).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TransactionId (string) maxLength
            if (this.TransactionId != null && this.TransactionId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for TransactionId, length must be less than 50.", new [] { "TransactionId" });
            }

            // TransactionId (string) minLength
            if (this.TransactionId != null && this.TransactionId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for TransactionId, length must be greater than 1.", new [] { "TransactionId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaymentMethodWriteResponseTransaction" />
    /// </summary>
    public class PaymentMethodWriteResponseTransactionJsonConverter : JsonConverter<PaymentMethodWriteResponseTransaction>
    {
        /// <summary>
        /// The format to use to serialize TransactionDate
        /// </summary>
        public static string TransactionDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="PaymentMethodWriteResponseTransaction" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaymentMethodWriteResponseTransaction Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> transactionId = default;
            Option<DateTime?> transactionDate = default;
            Option<int?> transactionStatus = default;
            Option<string?> message = default;
            Option<string?> responseCode = default;
            Option<string?> transactionType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "transactionId":
                            transactionId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionDate":
                            transactionDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "transactionStatus":
                            transactionStatus = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "responseCode":
                            responseCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionType":
                            transactionType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new PaymentMethodWriteResponseTransaction(transactionId, transactionDate, transactionStatus, message, responseCode, transactionType);
        }

        /// <summary>
        /// Serializes a <see cref="PaymentMethodWriteResponseTransaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentMethodWriteResponseTransaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaymentMethodWriteResponseTransaction paymentMethodWriteResponseTransaction, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paymentMethodWriteResponseTransaction, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaymentMethodWriteResponseTransaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentMethodWriteResponseTransaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaymentMethodWriteResponseTransaction paymentMethodWriteResponseTransaction, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paymentMethodWriteResponseTransaction.TransactionIdOption.IsSet)
                if (paymentMethodWriteResponseTransaction.TransactionIdOption.Value != null)
                    writer.WriteString("transactionId", paymentMethodWriteResponseTransaction.TransactionId);
                else
                    writer.WriteNull("transactionId");

            if (paymentMethodWriteResponseTransaction.TransactionDateOption.IsSet)
                if (paymentMethodWriteResponseTransaction.TransactionDateOption.Value != null)
                    writer.WriteString("transactionDate", paymentMethodWriteResponseTransaction.TransactionDateOption.Value!.Value.ToString(TransactionDateFormat));
                else
                    writer.WriteNull("transactionDate");

            if (paymentMethodWriteResponseTransaction.TransactionStatusOption.IsSet)
                if (paymentMethodWriteResponseTransaction.TransactionStatusOption.Value != null)
                    writer.WriteNumber("transactionStatus", paymentMethodWriteResponseTransaction.TransactionStatusOption.Value!.Value);
                else
                    writer.WriteNull("transactionStatus");

            if (paymentMethodWriteResponseTransaction.MessageOption.IsSet)
                if (paymentMethodWriteResponseTransaction.MessageOption.Value != null)
                    writer.WriteString("message", paymentMethodWriteResponseTransaction.Message);
                else
                    writer.WriteNull("message");

            if (paymentMethodWriteResponseTransaction.ResponseCodeOption.IsSet)
                if (paymentMethodWriteResponseTransaction.ResponseCodeOption.Value != null)
                    writer.WriteString("responseCode", paymentMethodWriteResponseTransaction.ResponseCode);
                else
                    writer.WriteNull("responseCode");

            if (paymentMethodWriteResponseTransaction.TransactionTypeOption.IsSet)
                if (paymentMethodWriteResponseTransaction.TransactionTypeOption.Value != null)
                    writer.WriteString("transactionType", paymentMethodWriteResponseTransaction.TransactionType);
                else
                    writer.WriteNull("transactionType");
        }
    }
}
