// <auto-generated>
/*
 * Revaly
 *
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header. 
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Revaly.Sdk.Core.Client;

namespace Revaly.Sdk.Core.Model
{
    /// <summary>
    /// 3D Secure authentication data for payment processing
    /// </summary>
    public partial class ThreeDS : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDS" /> class.
        /// </summary>
        /// <param name="varVersion">3DS protocol version used for the auth result.</param>
        /// <param name="exemptionType">Requested/declared SCA exemption routed to the gateway (e.g., &#39;moto&#39;, &#39;low_value&#39;).</param>
        /// <param name="eci">Electronic Commerce Indicator (scheme-specific). Visa: 05/06/07, MC: 02/01/00.</param>
        /// <param name="cryptogram">Cardholder Authentication Verification Value (CAVV/AVV/UCAF cryptogram). Base64 of a 20-byte value (28 chars).</param>
        /// <param name="dsTransactionId">Directory Server transaction ID (UUID, 36 chars).</param>
        /// <param name="acsTransactionId">ACS (issuer) transaction ID (UUID, 36 chars).</param>
        /// <param name="xid">Authentication transaction ID (legacy 3DS1, Base64 of 20 bytes, 28 chars).</param>
        /// <param name="cavvAlgorithm">Algorithm used to generate the cryptogram. Often &#39;1&#39;.</param>
        /// <param name="directoryStatus">Directory Server response status (TransStatus). Typical: Y, N, U, A, R.</param>
        /// <param name="authenticationStatus">Final cardholder authentication status from ACS/3DS Server (TransStatus). Typical: Y, N, U, A, R.</param>
        /// <param name="enrolledStatus">Enrollment status (legacy 3DS1, Verify Enrollment Response). Typical: Y, N, U.</param>
        /// <param name="serverTransId">3DS Server transaction ID (UUID, 36 chars).</param>
        [JsonConstructor]
        public ThreeDS(Option<string?> varVersion = default, Option<string?> exemptionType = default, Option<string?> eci = default, Option<string?> cryptogram = default, Option<Guid?> dsTransactionId = default, Option<Guid?> acsTransactionId = default, Option<string?> xid = default, Option<string?> cavvAlgorithm = default, Option<DirectoryStatusEnum?> directoryStatus = default, Option<AuthenticationStatusEnum?> authenticationStatus = default, Option<EnrolledStatusEnum?> enrolledStatus = default, Option<Guid?> serverTransId = default)
        {
            VarVersionOption = varVersion;
            ExemptionTypeOption = exemptionType;
            EciOption = eci;
            CryptogramOption = cryptogram;
            DsTransactionIdOption = dsTransactionId;
            AcsTransactionIdOption = acsTransactionId;
            XidOption = xid;
            CavvAlgorithmOption = cavvAlgorithm;
            DirectoryStatusOption = directoryStatus;
            AuthenticationStatusOption = authenticationStatus;
            EnrolledStatusOption = enrolledStatus;
            ServerTransIdOption = serverTransId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Directory Server response status (TransStatus). Typical: Y, N, U, A, R.
        /// </summary>
        /// <value>Directory Server response status (TransStatus). Typical: Y, N, U, A, R.</value>
        public enum DirectoryStatusEnum
        {
            /// <summary>
            /// Enum Y for value: Y
            /// </summary>
            Y = 1,

            /// <summary>
            /// Enum N for value: N
            /// </summary>
            N = 2,

            /// <summary>
            /// Enum U for value: U
            /// </summary>
            U = 3,

            /// <summary>
            /// Enum A for value: A
            /// </summary>
            A = 4,

            /// <summary>
            /// Enum R for value: R
            /// </summary>
            R = 5,

            /// <summary>
            /// Enum UnknownDefaultOpenApi for value: unknown_default_open_api
            /// </summary>
            UnknownDefaultOpenApi = 6
        }

        /// <summary>
        /// Returns a <see cref="DirectoryStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static DirectoryStatusEnum DirectoryStatusEnumFromString(string value)
        {
            if (value.Equals("Y"))
                return DirectoryStatusEnum.Y;

            if (value.Equals("N"))
                return DirectoryStatusEnum.N;

            if (value.Equals("U"))
                return DirectoryStatusEnum.U;

            if (value.Equals("A"))
                return DirectoryStatusEnum.A;

            if (value.Equals("R"))
                return DirectoryStatusEnum.R;

            if (value.Equals("unknown_default_open_api"))
                return DirectoryStatusEnum.UnknownDefaultOpenApi;

            throw new NotImplementedException($"Could not convert value to type DirectoryStatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="DirectoryStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DirectoryStatusEnum? DirectoryStatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Y"))
                return DirectoryStatusEnum.Y;

            if (value.Equals("N"))
                return DirectoryStatusEnum.N;

            if (value.Equals("U"))
                return DirectoryStatusEnum.U;

            if (value.Equals("A"))
                return DirectoryStatusEnum.A;

            if (value.Equals("R"))
                return DirectoryStatusEnum.R;

            if (value.Equals("unknown_default_open_api"))
                return DirectoryStatusEnum.UnknownDefaultOpenApi;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="DirectoryStatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string? DirectoryStatusEnumToJsonValue(DirectoryStatusEnum? value)
        {
            if (value == null)
                return null;

            if (value == DirectoryStatusEnum.Y)
                return "Y";

            if (value == DirectoryStatusEnum.N)
                return "N";

            if (value == DirectoryStatusEnum.U)
                return "U";

            if (value == DirectoryStatusEnum.A)
                return "A";

            if (value == DirectoryStatusEnum.R)
                return "R";

            if (value == DirectoryStatusEnum.UnknownDefaultOpenApi)
                return "unknown_default_open_api";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of DirectoryStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DirectoryStatusEnum?> DirectoryStatusOption { get; private set; }

        /// <summary>
        /// Directory Server response status (TransStatus). Typical: Y, N, U, A, R.
        /// </summary>
        /// <value>Directory Server response status (TransStatus). Typical: Y, N, U, A, R.</value>
        /* <example>Y</example> */
        [JsonPropertyName("directoryStatus")]
        public DirectoryStatusEnum? DirectoryStatus { get { return this.DirectoryStatusOption.Value; } set { this.DirectoryStatusOption = new(value); } }

        /// <summary>
        /// Final cardholder authentication status from ACS/3DS Server (TransStatus). Typical: Y, N, U, A, R.
        /// </summary>
        /// <value>Final cardholder authentication status from ACS/3DS Server (TransStatus). Typical: Y, N, U, A, R.</value>
        public enum AuthenticationStatusEnum
        {
            /// <summary>
            /// Enum Y for value: Y
            /// </summary>
            Y = 1,

            /// <summary>
            /// Enum N for value: N
            /// </summary>
            N = 2,

            /// <summary>
            /// Enum U for value: U
            /// </summary>
            U = 3,

            /// <summary>
            /// Enum A for value: A
            /// </summary>
            A = 4,

            /// <summary>
            /// Enum R for value: R
            /// </summary>
            R = 5,

            /// <summary>
            /// Enum UnknownDefaultOpenApi for value: unknown_default_open_api
            /// </summary>
            UnknownDefaultOpenApi = 6
        }

        /// <summary>
        /// Returns a <see cref="AuthenticationStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static AuthenticationStatusEnum AuthenticationStatusEnumFromString(string value)
        {
            if (value.Equals("Y"))
                return AuthenticationStatusEnum.Y;

            if (value.Equals("N"))
                return AuthenticationStatusEnum.N;

            if (value.Equals("U"))
                return AuthenticationStatusEnum.U;

            if (value.Equals("A"))
                return AuthenticationStatusEnum.A;

            if (value.Equals("R"))
                return AuthenticationStatusEnum.R;

            if (value.Equals("unknown_default_open_api"))
                return AuthenticationStatusEnum.UnknownDefaultOpenApi;

            throw new NotImplementedException($"Could not convert value to type AuthenticationStatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="AuthenticationStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AuthenticationStatusEnum? AuthenticationStatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Y"))
                return AuthenticationStatusEnum.Y;

            if (value.Equals("N"))
                return AuthenticationStatusEnum.N;

            if (value.Equals("U"))
                return AuthenticationStatusEnum.U;

            if (value.Equals("A"))
                return AuthenticationStatusEnum.A;

            if (value.Equals("R"))
                return AuthenticationStatusEnum.R;

            if (value.Equals("unknown_default_open_api"))
                return AuthenticationStatusEnum.UnknownDefaultOpenApi;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="AuthenticationStatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string? AuthenticationStatusEnumToJsonValue(AuthenticationStatusEnum? value)
        {
            if (value == null)
                return null;

            if (value == AuthenticationStatusEnum.Y)
                return "Y";

            if (value == AuthenticationStatusEnum.N)
                return "N";

            if (value == AuthenticationStatusEnum.U)
                return "U";

            if (value == AuthenticationStatusEnum.A)
                return "A";

            if (value == AuthenticationStatusEnum.R)
                return "R";

            if (value == AuthenticationStatusEnum.UnknownDefaultOpenApi)
                return "unknown_default_open_api";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of AuthenticationStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AuthenticationStatusEnum?> AuthenticationStatusOption { get; private set; }

        /// <summary>
        /// Final cardholder authentication status from ACS/3DS Server (TransStatus). Typical: Y, N, U, A, R.
        /// </summary>
        /// <value>Final cardholder authentication status from ACS/3DS Server (TransStatus). Typical: Y, N, U, A, R.</value>
        /* <example>Y</example> */
        [JsonPropertyName("authenticationStatus")]
        public AuthenticationStatusEnum? AuthenticationStatus { get { return this.AuthenticationStatusOption.Value; } set { this.AuthenticationStatusOption = new(value); } }

        /// <summary>
        /// Enrollment status (legacy 3DS1, Verify Enrollment Response). Typical: Y, N, U.
        /// </summary>
        /// <value>Enrollment status (legacy 3DS1, Verify Enrollment Response). Typical: Y, N, U.</value>
        public enum EnrolledStatusEnum
        {
            /// <summary>
            /// Enum Y for value: Y
            /// </summary>
            Y = 1,

            /// <summary>
            /// Enum N for value: N
            /// </summary>
            N = 2,

            /// <summary>
            /// Enum U for value: U
            /// </summary>
            U = 3,

            /// <summary>
            /// Enum UnknownDefaultOpenApi for value: unknown_default_open_api
            /// </summary>
            UnknownDefaultOpenApi = 4
        }

        /// <summary>
        /// Returns a <see cref="EnrolledStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EnrolledStatusEnum EnrolledStatusEnumFromString(string value)
        {
            if (value.Equals("Y"))
                return EnrolledStatusEnum.Y;

            if (value.Equals("N"))
                return EnrolledStatusEnum.N;

            if (value.Equals("U"))
                return EnrolledStatusEnum.U;

            if (value.Equals("unknown_default_open_api"))
                return EnrolledStatusEnum.UnknownDefaultOpenApi;

            throw new NotImplementedException($"Could not convert value to type EnrolledStatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EnrolledStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EnrolledStatusEnum? EnrolledStatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Y"))
                return EnrolledStatusEnum.Y;

            if (value.Equals("N"))
                return EnrolledStatusEnum.N;

            if (value.Equals("U"))
                return EnrolledStatusEnum.U;

            if (value.Equals("unknown_default_open_api"))
                return EnrolledStatusEnum.UnknownDefaultOpenApi;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EnrolledStatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string? EnrolledStatusEnumToJsonValue(EnrolledStatusEnum? value)
        {
            if (value == null)
                return null;

            if (value == EnrolledStatusEnum.Y)
                return "Y";

            if (value == EnrolledStatusEnum.N)
                return "N";

            if (value == EnrolledStatusEnum.U)
                return "U";

            if (value == EnrolledStatusEnum.UnknownDefaultOpenApi)
                return "unknown_default_open_api";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of EnrolledStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EnrolledStatusEnum?> EnrolledStatusOption { get; private set; }

        /// <summary>
        /// Enrollment status (legacy 3DS1, Verify Enrollment Response). Typical: Y, N, U.
        /// </summary>
        /// <value>Enrollment status (legacy 3DS1, Verify Enrollment Response). Typical: Y, N, U.</value>
        /* <example>Y</example> */
        [JsonPropertyName("enrolledStatus")]
        public EnrolledStatusEnum? EnrolledStatus { get { return this.EnrolledStatusOption.Value; } set { this.EnrolledStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of VarVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VarVersionOption { get; private set; }

        /// <summary>
        /// 3DS protocol version used for the auth result.
        /// </summary>
        /// <value>3DS protocol version used for the auth result.</value>
        /* <example>2.1.0</example> */
        [JsonPropertyName("version")]
        public string? VarVersion { get { return this.VarVersionOption.Value; } set { this.VarVersionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExemptionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExemptionTypeOption { get; private set; }

        /// <summary>
        /// Requested/declared SCA exemption routed to the gateway (e.g., &#39;moto&#39;, &#39;low_value&#39;).
        /// </summary>
        /// <value>Requested/declared SCA exemption routed to the gateway (e.g., &#39;moto&#39;, &#39;low_value&#39;).</value>
        /* <example>low_value</example> */
        [JsonPropertyName("exemptionType")]
        public string? ExemptionType { get { return this.ExemptionTypeOption.Value; } set { this.ExemptionTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Eci
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EciOption { get; private set; }

        /// <summary>
        /// Electronic Commerce Indicator (scheme-specific). Visa: 05/06/07, MC: 02/01/00.
        /// </summary>
        /// <value>Electronic Commerce Indicator (scheme-specific). Visa: 05/06/07, MC: 02/01/00.</value>
        /* <example>05</example> */
        [JsonPropertyName("eci")]
        public string? Eci { get { return this.EciOption.Value; } set { this.EciOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cryptogram
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CryptogramOption { get; private set; }

        /// <summary>
        /// Cardholder Authentication Verification Value (CAVV/AVV/UCAF cryptogram). Base64 of a 20-byte value (28 chars).
        /// </summary>
        /// <value>Cardholder Authentication Verification Value (CAVV/AVV/UCAF cryptogram). Base64 of a 20-byte value (28 chars).</value>
        /* <example>AAABAWFlmQAAAABjRWWWAAAAAA&#x3D;&#x3D;</example> */
        [JsonPropertyName("cryptogram")]
        public string? Cryptogram { get { return this.CryptogramOption.Value; } set { this.CryptogramOption = new(value); } }

        /// <summary>
        /// Used to track the state of DsTransactionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> DsTransactionIdOption { get; private set; }

        /// <summary>
        /// Directory Server transaction ID (UUID, 36 chars).
        /// </summary>
        /// <value>Directory Server transaction ID (UUID, 36 chars).</value>
        /* <example>550e8400-e29b-41d4-a716-446655440000</example> */
        [JsonPropertyName("dsTransactionId")]
        public Guid? DsTransactionId { get { return this.DsTransactionIdOption.Value; } set { this.DsTransactionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of AcsTransactionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> AcsTransactionIdOption { get; private set; }

        /// <summary>
        /// ACS (issuer) transaction ID (UUID, 36 chars).
        /// </summary>
        /// <value>ACS (issuer) transaction ID (UUID, 36 chars).</value>
        /* <example>6ba7b810-9dad-11d1-80b4-00c04fd430c8</example> */
        [JsonPropertyName("acsTransactionId")]
        public Guid? AcsTransactionId { get { return this.AcsTransactionIdOption.Value; } set { this.AcsTransactionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Xid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> XidOption { get; private set; }

        /// <summary>
        /// Authentication transaction ID (legacy 3DS1, Base64 of 20 bytes, 28 chars).
        /// </summary>
        /// <value>Authentication transaction ID (legacy 3DS1, Base64 of 20 bytes, 28 chars).</value>
        /* <example>MDAwMDAwMDAwMDAwMDAwMzIyNzY&#x3D;</example> */
        [JsonPropertyName("xid")]
        public string? Xid { get { return this.XidOption.Value; } set { this.XidOption = new(value); } }

        /// <summary>
        /// Used to track the state of CavvAlgorithm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CavvAlgorithmOption { get; private set; }

        /// <summary>
        /// Algorithm used to generate the cryptogram. Often &#39;1&#39;.
        /// </summary>
        /// <value>Algorithm used to generate the cryptogram. Often &#39;1&#39;.</value>
        /* <example>1</example> */
        [JsonPropertyName("cavvAlgorithm")]
        public string? CavvAlgorithm { get { return this.CavvAlgorithmOption.Value; } set { this.CavvAlgorithmOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServerTransId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ServerTransIdOption { get; private set; }

        /// <summary>
        /// 3DS Server transaction ID (UUID, 36 chars).
        /// </summary>
        /// <value>3DS Server transaction ID (UUID, 36 chars).</value>
        /* <example>6ba7b811-9dad-11d1-80b4-00c04fd430c8</example> */
        [JsonPropertyName("serverTransId")]
        public Guid? ServerTransId { get { return this.ServerTransIdOption.Value; } set { this.ServerTransIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ThreeDS {\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  ExemptionType: ").Append(ExemptionType).Append("\n");
            sb.Append("  Eci: ").Append(Eci).Append("\n");
            sb.Append("  Cryptogram: ").Append(Cryptogram).Append("\n");
            sb.Append("  DsTransactionId: ").Append(DsTransactionId).Append("\n");
            sb.Append("  AcsTransactionId: ").Append(AcsTransactionId).Append("\n");
            sb.Append("  Xid: ").Append(Xid).Append("\n");
            sb.Append("  CavvAlgorithm: ").Append(CavvAlgorithm).Append("\n");
            sb.Append("  DirectoryStatus: ").Append(DirectoryStatus).Append("\n");
            sb.Append("  AuthenticationStatus: ").Append(AuthenticationStatus).Append("\n");
            sb.Append("  EnrolledStatus: ").Append(EnrolledStatus).Append("\n");
            sb.Append("  ServerTransId: ").Append(ServerTransId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ThreeDS" />
    /// </summary>
    public class ThreeDSJsonConverter : JsonConverter<ThreeDS>
    {
        /// <summary>
        /// Deserializes json to <see cref="ThreeDS" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ThreeDS Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> varVersion = default;
            Option<string?> exemptionType = default;
            Option<string?> eci = default;
            Option<string?> cryptogram = default;
            Option<Guid?> dsTransactionId = default;
            Option<Guid?> acsTransactionId = default;
            Option<string?> xid = default;
            Option<string?> cavvAlgorithm = default;
            Option<ThreeDS.DirectoryStatusEnum?> directoryStatus = default;
            Option<ThreeDS.AuthenticationStatusEnum?> authenticationStatus = default;
            Option<ThreeDS.EnrolledStatusEnum?> enrolledStatus = default;
            Option<Guid?> serverTransId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "version":
                            varVersion = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "exemptionType":
                            exemptionType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "eci":
                            eci = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cryptogram":
                            cryptogram = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "dsTransactionId":
                            dsTransactionId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "acsTransactionId":
                            acsTransactionId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "xid":
                            xid = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cavvAlgorithm":
                            cavvAlgorithm = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "directoryStatus":
                            string? directoryStatusRawValue = utf8JsonReader.GetString();
                            directoryStatus = new Option<ThreeDS.DirectoryStatusEnum?>(directoryStatusRawValue == null ? null : ThreeDS.DirectoryStatusEnumFromStringOrDefault(directoryStatusRawValue));
                            break;
                        case "authenticationStatus":
                            string? authenticationStatusRawValue = utf8JsonReader.GetString();
                            authenticationStatus = new Option<ThreeDS.AuthenticationStatusEnum?>(authenticationStatusRawValue == null ? null : ThreeDS.AuthenticationStatusEnumFromStringOrDefault(authenticationStatusRawValue));
                            break;
                        case "enrolledStatus":
                            string? enrolledStatusRawValue = utf8JsonReader.GetString();
                            enrolledStatus = new Option<ThreeDS.EnrolledStatusEnum?>(enrolledStatusRawValue == null ? null : ThreeDS.EnrolledStatusEnumFromStringOrDefault(enrolledStatusRawValue));
                            break;
                        case "serverTransId":
                            serverTransId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ThreeDS(varVersion, exemptionType, eci, cryptogram, dsTransactionId, acsTransactionId, xid, cavvAlgorithm, directoryStatus, authenticationStatus, enrolledStatus, serverTransId);
        }

        /// <summary>
        /// Serializes a <see cref="ThreeDS" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="threeDS"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ThreeDS threeDS, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, threeDS, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ThreeDS" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="threeDS"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ThreeDS threeDS, JsonSerializerOptions jsonSerializerOptions)
        {
            if (threeDS.VarVersionOption.IsSet)
                if (threeDS.VarVersionOption.Value != null)
                    writer.WriteString("version", threeDS.VarVersion);
                else
                    writer.WriteNull("version");

            if (threeDS.ExemptionTypeOption.IsSet)
                if (threeDS.ExemptionTypeOption.Value != null)
                    writer.WriteString("exemptionType", threeDS.ExemptionType);
                else
                    writer.WriteNull("exemptionType");

            if (threeDS.EciOption.IsSet)
                if (threeDS.EciOption.Value != null)
                    writer.WriteString("eci", threeDS.Eci);
                else
                    writer.WriteNull("eci");

            if (threeDS.CryptogramOption.IsSet)
                if (threeDS.CryptogramOption.Value != null)
                    writer.WriteString("cryptogram", threeDS.Cryptogram);
                else
                    writer.WriteNull("cryptogram");

            if (threeDS.DsTransactionIdOption.IsSet)
                if (threeDS.DsTransactionIdOption.Value != null)
                    writer.WriteString("dsTransactionId", threeDS.DsTransactionIdOption.Value!.Value);
                else
                    writer.WriteNull("dsTransactionId");

            if (threeDS.AcsTransactionIdOption.IsSet)
                if (threeDS.AcsTransactionIdOption.Value != null)
                    writer.WriteString("acsTransactionId", threeDS.AcsTransactionIdOption.Value!.Value);
                else
                    writer.WriteNull("acsTransactionId");

            if (threeDS.XidOption.IsSet)
                if (threeDS.XidOption.Value != null)
                    writer.WriteString("xid", threeDS.Xid);
                else
                    writer.WriteNull("xid");

            if (threeDS.CavvAlgorithmOption.IsSet)
                if (threeDS.CavvAlgorithmOption.Value != null)
                    writer.WriteString("cavvAlgorithm", threeDS.CavvAlgorithm);
                else
                    writer.WriteNull("cavvAlgorithm");

            var directoryStatusRawValue = ThreeDS.DirectoryStatusEnumToJsonValue(threeDS.DirectoryStatusOption.Value!.Value);
            if (directoryStatusRawValue != null)
                writer.WriteString("directoryStatus", directoryStatusRawValue);
            else
                writer.WriteNull("directoryStatus");

            var authenticationStatusRawValue = ThreeDS.AuthenticationStatusEnumToJsonValue(threeDS.AuthenticationStatusOption.Value!.Value);
            if (authenticationStatusRawValue != null)
                writer.WriteString("authenticationStatus", authenticationStatusRawValue);
            else
                writer.WriteNull("authenticationStatus");

            var enrolledStatusRawValue = ThreeDS.EnrolledStatusEnumToJsonValue(threeDS.EnrolledStatusOption.Value!.Value);
            if (enrolledStatusRawValue != null)
                writer.WriteString("enrolledStatus", enrolledStatusRawValue);
            else
                writer.WriteNull("enrolledStatus");

            if (threeDS.ServerTransIdOption.IsSet)
                if (threeDS.ServerTransIdOption.Value != null)
                    writer.WriteString("serverTransId", threeDS.ServerTransIdOption.Value!.Value);
                else
                    writer.WriteNull("serverTransId");
        }
    }
}
