// <auto-generated>
/*
 * Revaly
 *
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header.  ## Request tracing  Every API response — success and error alike — carries an `X-Correlation-ID` header. Send your own value (any non-empty string) and it is echoed back verbatim; omit it and the platform generates one. Quote the id when contacting support: it joins the request directly to platform telemetry. Treat it as an opaque string. 
 *
 * The version of the OpenAPI document: 2.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Revaly.Sdk.Core.Client;

namespace Revaly.Sdk.Core.Model
{
    /// <summary>
    /// Detailed transaction processing response information from the payment gateway
    /// </summary>
    public partial class TransactionResponseDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionResponseDetails" /> class.
        /// </summary>
        /// <param name="avsCode">Address Verification System result code</param>
        /// <param name="avsMessage">Address Verification System result message</param>
        /// <param name="cvvCode">Card Verification Value result code</param>
        /// <param name="cvvMessage">Card Verification Value result message</param>
        /// <param name="errorCode">Error code if transaction failed</param>
        /// <param name="errorDetail">Detailed error message if transaction failed</param>
        [JsonConstructor]
        public TransactionResponseDetails(Option<string?> avsCode = default, Option<string?> avsMessage = default, Option<string?> cvvCode = default, Option<string?> cvvMessage = default, Option<string?> errorCode = default, Option<string?> errorDetail = default)
        {
            AvsCodeOption = avsCode;
            AvsMessageOption = avsMessage;
            CvvCodeOption = cvvCode;
            CvvMessageOption = cvvMessage;
            ErrorCodeOption = errorCode;
            ErrorDetailOption = errorDetail;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AvsCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AvsCodeOption { get; private set; }

        /// <summary>
        /// Address Verification System result code
        /// </summary>
        /// <value>Address Verification System result code</value>
        /* <example>Y</example> */
        [JsonPropertyName("avsCode")]
        public string? AvsCode { get { return this.AvsCodeOption.Value; } set { this.AvsCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of AvsMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AvsMessageOption { get; private set; }

        /// <summary>
        /// Address Verification System result message
        /// </summary>
        /// <value>Address Verification System result message</value>
        /* <example>Address verification successful</example> */
        [JsonPropertyName("avsMessage")]
        public string? AvsMessage { get { return this.AvsMessageOption.Value; } set { this.AvsMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of CvvCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CvvCodeOption { get; private set; }

        /// <summary>
        /// Card Verification Value result code
        /// </summary>
        /// <value>Card Verification Value result code</value>
        /* <example>M</example> */
        [JsonPropertyName("cvvCode")]
        public string? CvvCode { get { return this.CvvCodeOption.Value; } set { this.CvvCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of CvvMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CvvMessageOption { get; private set; }

        /// <summary>
        /// Card Verification Value result message
        /// </summary>
        /// <value>Card Verification Value result message</value>
        /* <example>CVV verification successful</example> */
        [JsonPropertyName("cvvMessage")]
        public string? CvvMessage { get { return this.CvvMessageOption.Value; } set { this.CvvMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorCodeOption { get; private set; }

        /// <summary>
        /// Error code if transaction failed
        /// </summary>
        /// <value>Error code if transaction failed</value>
        /* <example>DECLINED</example> */
        [JsonPropertyName("errorCode")]
        public string? ErrorCode { get { return this.ErrorCodeOption.Value; } set { this.ErrorCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorDetail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorDetailOption { get; private set; }

        /// <summary>
        /// Detailed error message if transaction failed
        /// </summary>
        /// <value>Detailed error message if transaction failed</value>
        /* <example>Insufficient funds available</example> */
        [JsonPropertyName("errorDetail")]
        public string? ErrorDetail { get { return this.ErrorDetailOption.Value; } set { this.ErrorDetailOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionResponseDetails {\n");
            sb.Append("  AvsCode: ").Append(AvsCode).Append("\n");
            sb.Append("  AvsMessage: ").Append(AvsMessage).Append("\n");
            sb.Append("  CvvCode: ").Append(CvvCode).Append("\n");
            sb.Append("  CvvMessage: ").Append(CvvMessage).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  ErrorDetail: ").Append(ErrorDetail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TransactionResponseDetails" />
    /// </summary>
    public class TransactionResponseDetailsJsonConverter : JsonConverter<TransactionResponseDetails>
    {
        /// <summary>
        /// Deserializes json to <see cref="TransactionResponseDetails" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TransactionResponseDetails Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> avsCode = default;
            Option<string?> avsMessage = default;
            Option<string?> cvvCode = default;
            Option<string?> cvvMessage = default;
            Option<string?> errorCode = default;
            Option<string?> errorDetail = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "avsCode":
                            avsCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "avsMessage":
                            avsMessage = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cvvCode":
                            cvvCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cvvMessage":
                            cvvMessage = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "errorCode":
                            errorCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "errorDetail":
                            errorDetail = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new TransactionResponseDetails(avsCode, avsMessage, cvvCode, cvvMessage, errorCode, errorDetail);
        }

        /// <summary>
        /// Serializes a <see cref="TransactionResponseDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transactionResponseDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TransactionResponseDetails transactionResponseDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, transactionResponseDetails, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TransactionResponseDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transactionResponseDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TransactionResponseDetails transactionResponseDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            if (transactionResponseDetails.AvsCodeOption.IsSet)
                if (transactionResponseDetails.AvsCodeOption.Value != null)
                    writer.WriteString("avsCode", transactionResponseDetails.AvsCode);
                else
                    writer.WriteNull("avsCode");

            if (transactionResponseDetails.AvsMessageOption.IsSet)
                if (transactionResponseDetails.AvsMessageOption.Value != null)
                    writer.WriteString("avsMessage", transactionResponseDetails.AvsMessage);
                else
                    writer.WriteNull("avsMessage");

            if (transactionResponseDetails.CvvCodeOption.IsSet)
                if (transactionResponseDetails.CvvCodeOption.Value != null)
                    writer.WriteString("cvvCode", transactionResponseDetails.CvvCode);
                else
                    writer.WriteNull("cvvCode");

            if (transactionResponseDetails.CvvMessageOption.IsSet)
                if (transactionResponseDetails.CvvMessageOption.Value != null)
                    writer.WriteString("cvvMessage", transactionResponseDetails.CvvMessage);
                else
                    writer.WriteNull("cvvMessage");

            if (transactionResponseDetails.ErrorCodeOption.IsSet)
                if (transactionResponseDetails.ErrorCodeOption.Value != null)
                    writer.WriteString("errorCode", transactionResponseDetails.ErrorCode);
                else
                    writer.WriteNull("errorCode");

            if (transactionResponseDetails.ErrorDetailOption.IsSet)
                if (transactionResponseDetails.ErrorDetailOption.Value != null)
                    writer.WriteString("errorDetail", transactionResponseDetails.ErrorDetail);
                else
                    writer.WriteNull("errorDetail");
        }
    }
}
