// <auto-generated>
/*
 * Revaly
 *
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header. 
 *
 * The version of the OpenAPI document: 2.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Revaly.Sdk.Core.Client;

namespace Revaly.Sdk.Core.Model
{
    /// <summary>
    /// Vault-issued payment token details for payment processing
    /// </summary>
    public partial class VaultPaymentMethod : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VaultPaymentMethod" /> class.
        /// </summary>
        /// <param name="vaultToken">Vault-issued token (any provider) used to authorize a payment. Valid only on &#x60;/payments/charge&#x60; and &#x60;/payments/authorize&#x60; when &#x60;paymentMethodType&#x60; is &#x60;vaultToken&#x60;. Requires &#x60;paymentMethod.merchantAccountReferenceId&#x60; for gateway routing. Must not be combined with &#x60;creditCard&#x60; or &#x60;gatewayPaymentMethod&#x60;. </param>
        /// <param name="bin">Bank Identification Number (first 6 or 8 digits)</param>
        /// <param name="lastFourDigits">Last four digits of the payment method</param>
        /// <param name="expiryYear">Expiration year (YYYY)</param>
        /// <param name="expiryMonth">Expiration month (01-12)</param>
        [JsonConstructor]
        public VaultPaymentMethod(Option<string?> vaultToken = default, Option<string?> bin = default, Option<string?> lastFourDigits = default, Option<string?> expiryYear = default, Option<string?> expiryMonth = default)
        {
            VaultTokenOption = vaultToken;
            BinOption = bin;
            LastFourDigitsOption = lastFourDigits;
            ExpiryYearOption = expiryYear;
            ExpiryMonthOption = expiryMonth;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of VaultToken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VaultTokenOption { get; private set; }

        /// <summary>
        /// Vault-issued token (any provider) used to authorize a payment. Valid only on &#x60;/payments/charge&#x60; and &#x60;/payments/authorize&#x60; when &#x60;paymentMethodType&#x60; is &#x60;vaultToken&#x60;. Requires &#x60;paymentMethod.merchantAccountReferenceId&#x60; for gateway routing. Must not be combined with &#x60;creditCard&#x60; or &#x60;gatewayPaymentMethod&#x60;. 
        /// </summary>
        /// <value>Vault-issued token (any provider) used to authorize a payment. Valid only on &#x60;/payments/charge&#x60; and &#x60;/payments/authorize&#x60; when &#x60;paymentMethodType&#x60; is &#x60;vaultToken&#x60;. Requires &#x60;paymentMethod.merchantAccountReferenceId&#x60; for gateway routing. Must not be combined with &#x60;creditCard&#x60; or &#x60;gatewayPaymentMethod&#x60;. </value>
        /* <example>vt_01HX5J8QH8N1XK2D3T4B6Q7Z9C</example> */
        [JsonPropertyName("vaultToken")]
        public string? VaultToken { get { return this.VaultTokenOption.Value; } set { this.VaultTokenOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BinOption { get; private set; }

        /// <summary>
        /// Bank Identification Number (first 6 or 8 digits)
        /// </summary>
        /// <value>Bank Identification Number (first 6 or 8 digits)</value>
        /* <example>424242</example> */
        [JsonPropertyName("bin")]
        public string? Bin { get { return this.BinOption.Value; } set { this.BinOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastFourDigits
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastFourDigitsOption { get; private set; }

        /// <summary>
        /// Last four digits of the payment method
        /// </summary>
        /// <value>Last four digits of the payment method</value>
        /* <example>4242</example> */
        [JsonPropertyName("lastFourDigits")]
        public string? LastFourDigits { get { return this.LastFourDigitsOption.Value; } set { this.LastFourDigitsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpiryYear
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExpiryYearOption { get; private set; }

        /// <summary>
        /// Expiration year (YYYY)
        /// </summary>
        /// <value>Expiration year (YYYY)</value>
        /* <example>2025</example> */
        [JsonPropertyName("expiryYear")]
        public string? ExpiryYear { get { return this.ExpiryYearOption.Value; } set { this.ExpiryYearOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpiryMonth
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExpiryMonthOption { get; private set; }

        /// <summary>
        /// Expiration month (01-12)
        /// </summary>
        /// <value>Expiration month (01-12)</value>
        /* <example>12</example> */
        [JsonPropertyName("expiryMonth")]
        public string? ExpiryMonth { get { return this.ExpiryMonthOption.Value; } set { this.ExpiryMonthOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VaultPaymentMethod {\n");
            sb.Append("  VaultToken: ").Append(VaultToken).Append("\n");
            sb.Append("  Bin: ").Append(Bin).Append("\n");
            sb.Append("  LastFourDigits: ").Append(LastFourDigits).Append("\n");
            sb.Append("  ExpiryYear: ").Append(ExpiryYear).Append("\n");
            sb.Append("  ExpiryMonth: ").Append(ExpiryMonth).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // VaultToken (string) maxLength
            if (this.VaultToken != null && this.VaultToken.Length > 200)
            {
                yield return new ValidationResult("Invalid value for VaultToken, length must be less than 200.", new [] { "VaultToken" });
            }

            if (this.BinOption.Value != null) {
                // Bin (string) pattern
                Regex regexBin = new Regex(@"^(?:[0-9]{6}|[0-9]{8})$", RegexOptions.CultureInvariant);

                if (this.BinOption.Value != null &&!regexBin.Match(this.BinOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Bin, must match a pattern of " + regexBin, new [] { "Bin" });
                }
            }

            if (this.LastFourDigitsOption.Value != null) {
                // LastFourDigits (string) pattern
                Regex regexLastFourDigits = new Regex(@"^[0-9]{4}$", RegexOptions.CultureInvariant);

                if (this.LastFourDigitsOption.Value != null &&!regexLastFourDigits.Match(this.LastFourDigitsOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LastFourDigits, must match a pattern of " + regexLastFourDigits, new [] { "LastFourDigits" });
                }
            }

            if (this.ExpiryYearOption.Value != null) {
                // ExpiryYear (string) pattern
                Regex regexExpiryYear = new Regex(@"^20[0-9]{2}$", RegexOptions.CultureInvariant);

                if (this.ExpiryYearOption.Value != null &&!regexExpiryYear.Match(this.ExpiryYearOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ExpiryYear, must match a pattern of " + regexExpiryYear, new [] { "ExpiryYear" });
                }
            }

            if (this.ExpiryMonthOption.Value != null) {
                // ExpiryMonth (string) pattern
                Regex regexExpiryMonth = new Regex(@"^(0[1-9]|1[0-2])$", RegexOptions.CultureInvariant);

                if (this.ExpiryMonthOption.Value != null &&!regexExpiryMonth.Match(this.ExpiryMonthOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ExpiryMonth, must match a pattern of " + regexExpiryMonth, new [] { "ExpiryMonth" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="VaultPaymentMethod" />
    /// </summary>
    public class VaultPaymentMethodJsonConverter : JsonConverter<VaultPaymentMethod>
    {
        /// <summary>
        /// Deserializes json to <see cref="VaultPaymentMethod" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override VaultPaymentMethod Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> vaultToken = default;
            Option<string?> bin = default;
            Option<string?> lastFourDigits = default;
            Option<string?> expiryYear = default;
            Option<string?> expiryMonth = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "vaultToken":
                            vaultToken = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "bin":
                            bin = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastFourDigits":
                            lastFourDigits = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "expiryYear":
                            expiryYear = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "expiryMonth":
                            expiryMonth = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new VaultPaymentMethod(vaultToken, bin, lastFourDigits, expiryYear, expiryMonth);
        }

        /// <summary>
        /// Serializes a <see cref="VaultPaymentMethod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="vaultPaymentMethod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, VaultPaymentMethod vaultPaymentMethod, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, vaultPaymentMethod, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="VaultPaymentMethod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="vaultPaymentMethod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, VaultPaymentMethod vaultPaymentMethod, JsonSerializerOptions jsonSerializerOptions)
        {
            if (vaultPaymentMethod.VaultTokenOption.IsSet)
                if (vaultPaymentMethod.VaultTokenOption.Value != null)
                    writer.WriteString("vaultToken", vaultPaymentMethod.VaultToken);
                else
                    writer.WriteNull("vaultToken");

            if (vaultPaymentMethod.BinOption.IsSet)
                if (vaultPaymentMethod.BinOption.Value != null)
                    writer.WriteString("bin", vaultPaymentMethod.Bin);
                else
                    writer.WriteNull("bin");

            if (vaultPaymentMethod.LastFourDigitsOption.IsSet)
                if (vaultPaymentMethod.LastFourDigitsOption.Value != null)
                    writer.WriteString("lastFourDigits", vaultPaymentMethod.LastFourDigits);
                else
                    writer.WriteNull("lastFourDigits");

            if (vaultPaymentMethod.ExpiryYearOption.IsSet)
                if (vaultPaymentMethod.ExpiryYearOption.Value != null)
                    writer.WriteString("expiryYear", vaultPaymentMethod.ExpiryYear);
                else
                    writer.WriteNull("expiryYear");

            if (vaultPaymentMethod.ExpiryMonthOption.IsSet)
                if (vaultPaymentMethod.ExpiryMonthOption.Value != null)
                    writer.WriteString("expiryMonth", vaultPaymentMethod.ExpiryMonth);
                else
                    writer.WriteNull("expiryMonth");
        }
    }
}
