// <auto-generated>
/*
 * Revaly
 *
 * Payment processing API for transaction and payment method management.  ## API Versioning  RAP supports an explicit, selectable API version so you can build against a stable, pinned contract while existing integrations keep working unchanged.  - **How to select a version:** send the `X-Api-Version` request header   (e.g. `X-Api-Version: 2.0`). The version lives in the header — request   URLs do not change. - **Default when omitted:** requests without the header (or with an   unrecognised header name) bind to the **base version `2.0`**, which is the   current contract. Existing integrations therefore continue unchanged. - **Unsupported versions:** a header naming a version that does not exist   returns **HTTP 400** with a structured error listing the supported   versions — a request is never silently bound to a different contract.   This includes an **empty or whitespace value**: if the `X-Api-Version`   header is present, it must name a supported version. Only a fully   absent header binds to the default. - **Supported versions** are advertised via the `api-supported-versions`   header on every response from the versioned API endpoints (payments,   payment methods, transactions, notify). Currently: `2.0`, `2.1`. - **Which version to use:** new integrations should pin **`2.1`**. It is   behaviourally identical to `2.0` today, and it is where future contract   refinements will land — pinning it now means you never migrate the   header. `2.0` is the frozen launch contract and remains the binding for   requests that send no version header. 
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 * RAP SDK generated core — DO NOT EDIT (ADR-SDK-001; CI regeneration-diff enforced).
 * Regenerate only via pipeline/generate.sh: spec input pinned by spec/pin.yaml
 * (ADR-SDK-006), generator digest-pinned by pipeline/generator-pin.yaml (ADR-SDK-023).
 */

#nullable enable

using System.Linq;
using System.Collections.Generic;

namespace Revaly.Sdk.Core.Client
{
    /// <summary>
    /// A container for a collection of tokens.
    /// </summary>
    /// <typeparam name="TTokenBase"></typeparam>
    public sealed class TokenContainer<TTokenBase> where TTokenBase : TokenBase
    {
        /// <summary>
        /// The collection of tokens
        /// </summary>
        public List<TTokenBase> Tokens { get; } = new List<TTokenBase>();

        /// <summary>
        /// Instantiates a TokenContainer
        /// </summary>
        public TokenContainer()
        {
        }

        /// <summary>
        /// Instantiates a TokenContainer
        /// </summary>
        /// <param name="tokens"></param>
        public TokenContainer(global::System.Collections.Generic.IEnumerable<TTokenBase> tokens)
        {
            Tokens = tokens.ToList();
        }
    }
}
